'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {authenticatedRequest} from '@/lib/api-client';
import PolicyFundingPanel from '@/components/insurance/PolicyFundingPanel';

type PolicyRow={id:string;vehicle_id:string;vehicle_number:string;company_name:string;policy_number:string;customer_pay:number;gross_premium:number;status:string;expiry_date:string;first_name?:string;last_name?:string;archived_at?:string|null};
type PolicyPage={data:PolicyRow[]};
type SettlementInfo={settlement:null|{settlement_type:string;amount:number;payment_date:string}};
type PendingRow=PolicyRow&{settled:boolean};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));

export default function CompanyPaymentsPage(){
 const[rows,setRows]=useState<PendingRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[vehicleId,setVehicleId]=useState(''),[policyId,setPolicyId]=useState(''),[open,setOpen]=useState(false),[search,setSearch]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const page=await authenticatedRequest<PolicyPage>('/policies?per_page=100');const active=(page?.data??[]).filter(p=>!p.archived_at&&!['cancelled','expired','draft'].includes(String(p.status||'').toLowerCase()));const checked=await Promise.all(active.map(async p=>{try{const s=await authenticatedRequest<SettlementInfo>(`/vehicles/${p.vehicle_id}/insurances/${p.id}/settlement`);return {...p,settled:!!s.settlement}}catch{return {...p,settled:false}}}));setRows(checked)}catch(e){setError(e instanceof Error?e.message:'Company payments could not load.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const paid=(e:Event)=>{const d=(e as CustomEvent<{vehicleId:string}>).detail;if(d?.vehicleId)void load()};window.addEventListener('raj:insurance-payment-saved',paid);return()=>window.removeEventListener('raj:insurance-payment-saved',paid)},[load]);
 const pending=useMemo(()=>rows.filter(r=>!r.settled),[rows]);const total=useMemo(()=>pending.reduce((s,r)=>s+Number(r.customer_pay||r.gross_premium||0),0),[pending]);const shown=useMemo(()=>{const q=search.trim().toLowerCase();return pending.filter(r=>!q||[r.vehicle_number,r.company_name,r.policy_number,r.first_name,r.last_name].filter(Boolean).join(' ').toLowerCase().includes(q))},[pending,search]);
 function pay(r:PendingRow){setVehicleId(r.vehicle_id);setPolicyId(r.id);setOpen(true)}
 return <main className="min-h-screen bg-[#f4f7fb] p-4 text-[#071a3c] sm:p-6"><div className="mx-auto max-w-7xl space-y-4">
  <div className="flex items-center justify-between"><div><Link href="/dashboard" className="text-xs font-black text-blue-700">← Dashboard</Link><p className="mt-2 text-[9px] font-black uppercase tracking-[.22em] text-blue-600">Insurance money control</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Company Payments</h1><p className="mt-1 text-sm font-semibold text-slate-500">Policies saved but insurer payment not yet recorded.</p></div></div>
  <section className={`overflow-hidden rounded-[28px] border p-5 shadow-[0_18px_50px_rgba(24,59,110,.08)] sm:p-6 ${pending.length?'border-rose-200 bg-gradient-to-r from-rose-50 to-white':'border-emerald-200 bg-gradient-to-r from-emerald-50 to-white'}`}><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Pending Policies" value={String(pending.length)} danger={pending.length>0}/><Kpi label="Company Payable" value={money(total)} danger={pending.length>0}/><Kpi label="Status" value={pending.length?'Action Required':'All Clear'} danger={pending.length>0}/></div></section>
  {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
  <section className="overflow-hidden rounded-[26px] border border-[#dce6f4] bg-white shadow-[0_14px_40px_rgba(24,59,110,.06)]"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-600">Pending insurer payments</p><h2 className="mt-1 text-xl font-black">Pay directly from here</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vehicle, policy, company..." className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold outline-none focus:border-blue-400 sm:w-80"/></div>
   {loading?<div className="p-8 text-center text-sm font-semibold text-slate-400">Loading pending company payments…</div>:shown.length?<div className="divide-y divide-slate-100">{shown.map(r=><div key={r.id} className="grid gap-3 p-4 sm:grid-cols-[1.25fr_1fr_.8fr_auto] sm:items-center sm:p-5"><div><p className="text-base font-black text-slate-950">{r.vehicle_number}</p><p className="mt-0.5 text-xs font-semibold text-slate-400">{[r.first_name,r.last_name].filter(Boolean).join(' ')||'Customer'} · {r.policy_number}</p></div><div><p className="text-xs font-black text-slate-700">{r.company_name}</p><p className="mt-0.5 text-[10px] font-semibold text-slate-400">Expiry {r.expiry_date}</p></div><div><p className="text-[9px] font-black uppercase tracking-wider text-rose-500">Payable</p><p className="mt-1 text-lg font-black text-rose-700">{money(Number(r.customer_pay||r.gross_premium||0))}</p></div><button onClick={()=>pay(r)} className="h-11 rounded-xl bg-rose-600 px-5 text-sm font-black text-white shadow-lg shadow-rose-600/20 transition hover:bg-rose-700">Pay Company</button></div>)}</div>:<div className="grid min-h-52 place-items-center p-8 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50 text-2xl">✓</div><p className="mt-3 text-lg font-black text-slate-900">No company payment pending</p><p className="mt-1 text-xs font-semibold text-slate-400">All current policy company payments are recorded.</p></div></div>}
  </section>
 </div>{vehicleId&&policyId&&<PolicyFundingPanel vehicleId={vehicleId} open={open} defaultPolicyId={policyId} onClose={()=>{setOpen(false);void load()}}/>}</main>
}
function Kpi({label,value,danger}:{label:string;value:string;danger:boolean}){return <div className="rounded-2xl border border-white/80 bg-white/80 p-4 shadow-sm"><p className={`text-[9px] font-black uppercase tracking-[.16em] ${danger?'text-rose-500':'text-emerald-600'}`}>{label}</p><p className={`mt-1 text-2xl font-black ${danger?'text-rose-700':'text-emerald-700'}`}>{value}</p></div>}
