'use client';

import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { customerApi, Customer } from '@/lib/customers';
import { exportRowsToExcel, exportRowsToPdf } from '@/lib/export-utils';
import { ServiceType, ServiceWork, serviceWorksApi } from '@/lib/service-works';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);

export default function ServiceWorkPage(){
  const params=useParams<{service:string}>();
  const type=(params.service==='passport'?'passport':'driving_licence') as ServiceType;
  const title=type==='passport'?'Passport Work':'Driving Licence Work';
  const [rows,setRows]=useState<ServiceWork[]>([]); const [summary,setSummary]=useState({work_count:0,billing:0,cost:0,received:0,due:0,profit:0});
  const [customers,setCustomers]=useState<Customer[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({customer_id:'',work_type:'',application_number:'',work_date:new Date().toISOString().slice(0,10),amount:'',cost:'',received_amount:'',status:'active',notes:''});
  async function load(){setLoading(true);setError('');try{const [work,cust]=await Promise.all([serviceWorksApi.list(type),customerApi.list('?per_page=200')]);setRows(work.rows);setSummary(work.summary);setCustomers(cust.data);}catch(e){setError(e instanceof Error?e.message:'Data load nahi hua.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[type]);
  const customerOptions=useMemo(()=>customers.map(c=>({id:c.id,label:`${c.first_name} ${c.middle_name||''} ${c.last_name||''} · ${c.mobile}`.replace(/\s+/g,' ')})),[customers]);
  async function save(){if(!form.amount){setError('Customer amount required.');return;}setSaving(true);setError('');try{await serviceWorksApi.create(type,{...form,amount:Number(form.amount||0),cost:Number(form.cost||0),received_amount:Number(form.received_amount||0),customer_id:form.customer_id||null});setForm({customer_id:'',work_type:'',application_number:'',work_date:new Date().toISOString().slice(0,10),amount:'',cost:'',received_amount:'',status:'active',notes:''});await load();}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setSaving(false);}}
  const exportRows=rows.map(r=>({Date:r.work_date,Customer:r.customer_name,Mobile:r.mobile,Work:r.work_type,Application:r.application_number,Amount:r.amount,Cost:r.cost,Received:r.received_amount,Due:r.due_amount,Profit:r.profit,Status:r.status}));
  return <main className="min-h-screen bg-[#f4f7fb] p-4 text-slate-950 md:p-6"><div className="mx-auto max-w-[1500px] space-y-6">
    <section className="rounded-[30px] bg-gradient-to-br from-[#07132f] via-[#12418e] to-[#2b70ec] p-7 text-white shadow-2xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">RTO Services</p><h1 className="mt-2 text-4xl font-black">{title}</h1><p className="mt-2 text-sm text-blue-100">Simple work entry. Income, cost, received, due and profit automatically tracked under RTO business.</p></div><div className="flex gap-2"><button onClick={()=>void exportRowsToPdf(title,type,exportRows,summary)} className="rounded-xl bg-white px-4 py-2.5 font-black text-blue-800">PDF</button><button onClick={()=>void exportRowsToExcel(type,exportRows)} className="rounded-xl bg-cyan-300 px-4 py-2.5 font-black text-slate-950">Excel</button></div></div></section>
    {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Object.entries(summary).map(([k,v])=><article key={k} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{k.replaceAll('_',' ')}</p><p className="mt-2 text-xl font-black text-[#0d2d61]">{k==='work_count'?v:money(v)}</p></article>)}</section>
    <section className="rounded-[28px] border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Add New Work</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-black uppercase text-slate-500">Customer<select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"><option value="">Select Customer</option>{customerOptions.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="text-xs font-black uppercase text-slate-500">Work Type<input value={form.work_type} onChange={e=>setForm({...form,work_type:e.target.value})} placeholder={type==='passport'?'New / Renewal':'New / Renewal / Duplicate'} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Application No<input value={form.application_number} onChange={e=>setForm({...form,application_number:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Date<input type="date" value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Customer Amount<input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Our Cost<input type="number" min="0" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Received<input type="number" min="0" value={form.received_amount} onChange={e=>setForm({...form,received_amount:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="text-xs font-black uppercase text-slate-500 xl:col-span-3">Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"/></label><div className="flex items-end"><button disabled={saving} onClick={()=>void save()} className="w-full rounded-xl bg-blue-700 px-4 py-3 font-black text-white disabled:opacity-50">{saving?'Saving...':'Add Work'}</button></div></div></section>
    <section className="overflow-hidden rounded-[28px] border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black">Work Register</h2><p className="text-sm text-slate-500">{loading?'Loading...':`${rows.length} records`}</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Date','Customer','Mobile','Work','Application','Amount','Cost','Received','Due','Profit','Status','Action'].map(h=><th key={h} className="px-4 py-3 text-[11px] font-black uppercase text-slate-500">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-3">{r.work_date||'—'}</td><td className="px-4 py-3 font-bold">{r.customer_name}</td><td className="px-4 py-3">{r.mobile||'—'}</td><td className="px-4 py-3">{r.work_type||'—'}</td><td className="px-4 py-3">{r.application_number||'—'}</td><td className="px-4 py-3">{money(r.amount)}</td><td className="px-4 py-3">{money(r.cost)}</td><td className="px-4 py-3">{money(r.received_amount)}</td><td className="px-4 py-3">{money(r.due_amount)}</td><td className="px-4 py-3 font-black text-emerald-700">{money(r.profit)}</td><td className="px-4 py-3">{r.status}</td><td className="px-4 py-3"><button onClick={async()=>{if(confirm('Delete this work?')){await serviceWorksApi.remove(type,r.id);await load();}}} className="font-bold text-rose-600">Delete</button></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={12} className="p-12 text-center text-slate-400">No work added.</td></tr>}</tbody></table></div></section>
  </div></main>;
}
