<?php

use App\Features\Accounting\Controllers\AccountingController;
use App\Features\Accounting\Controllers\BusinessReportsController;
use App\Features\Accounting\Controllers\FinanceControlController;
use App\Features\Accounting\Controllers\InsuranceAccountingController;
use App\Features\Accounting\Controllers\InsuranceClaimController;
use App\Features\Accounting\Controllers\InsurancePolicySettlementController;
use App\Features\Accounting\Controllers\LedgerController;
use App\Features\Accounting\Controllers\OtherInsuranceController;
use App\Features\Accounting\Controllers\ServiceWorkController;
use App\Features\BugAgent\Controllers\BugAgentController;
use App\Features\Customers\Controllers\CustomerController;
use App\Features\Identity\Controllers\AuthController;
use App\Features\Identity\Controllers\OrganizationController;
use App\Features\Identity\Controllers\ProfileController;
use App\Features\Identity\Controllers\RoleController;
use App\Features\Identity\Controllers\UserController;
use App\Features\Ocr\Controllers\OcrController;
use App\Features\Vehicles\Controllers\FleetController;
use App\Features\Vehicles\Controllers\PolicyController;
use App\Features\Vehicles\Controllers\RtoWorkAccountingController;
use App\Features\Vehicles\Controllers\RtoWorkRecordController;
use App\Features\Vehicles\Controllers\VehicleController;
use App\Features\Vehicles\Controllers\VehicleInsuranceController;
use App\Features\Vehicles\Controllers\VehicleMasterController;
use App\Features\Vehicles\Controllers\VehicleOperationsController;
use App\Features\Vehicles\Controllers\VehiclePaymentAccountingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Internal\ErpControlHealthController;
use App\Http\Controllers\Internal\ErpControlProvisionController;
use Illuminate\Support\Facades\Route;

Route::get('health', fn () => response()->json(['status' => 'ok']));
Route::get('v1/internal/erp-control/health', ErpControlHealthController::class)->middleware(['auth:sanctum', 'active']);
Route::post('v1/internal/erp-control/provision', ErpControlProvisionController::class)->middleware(['auth:sanctum', 'active']);
Route::post('v1/public-policy-ocr', [OcrController::class, 'publicPolicyScan'])->middleware('throttle:12,1');

Route::prefix('v1/auth')->group(function () {
    Route::post('login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('forgot-password', [AuthController::class, 'forgot'])->middleware('throttle:passwords');
    Route::post('reset-password', [AuthController::class, 'reset'])->middleware('throttle:passwords');
});

Route::prefix('v1')->middleware(['auth:sanctum', 'active', 'erp.active', 'erp.entitlements'])->group(function () {
    Route::get('organization', [OrganizationController::class, 'show']);
    Route::post('organization', [OrganizationController::class, 'update']);
    Route::get('profile', [ProfileController::class, 'show']);
    Route::post('profile', [ProfileController::class, 'update']);
    Route::get('dashboard/summary', [DashboardController::class, 'summary']);

    Route::get('bug-agent', [BugAgentController::class, 'index']);
    Route::post('bug-agent/reports', [BugAgentController::class, 'store'])->middleware('throttle:20,1');
    Route::post('bug-agent/reports/{report}/analyze', [BugAgentController::class, 'analyze'])->middleware('throttle:20,1');
    Route::post('bug-agent/reports/{report}/safe-fix', [BugAgentController::class, 'safeFix']);
    Route::post('bug-agent/reports/{report}/resolve', [BugAgentController::class, 'resolve']);
    Route::get('bug-agent/reports/{report}/screenshot', [BugAgentController::class, 'screenshot']);
    Route::post('bug-agent/scan', [BugAgentController::class, 'scanNow'])->middleware('throttle:10,1');

    Route::get('policies', [PolicyController::class, 'index'])->middleware('erp.module:POLICIES');
    Route::get('policies/{policy}', [PolicyController::class, 'show'])->middleware('erp.module:POLICIES');
    Route::get('reports/policies/summary', [PolicyController::class, 'summary'])->middleware('erp.module:REPORTS');
    Route::get('reports/business/overview', [BusinessReportsController::class, 'overview']);
    Route::get('reports/expiry', [BusinessReportsController::class, 'expiry']);
    Route::get('reports/agents', [BusinessReportsController::class, 'agents']);
    Route::get('reports/brokers', [BusinessReportsController::class, 'brokers']);
    Route::get('reports/insurance', [BusinessReportsController::class, 'insurance']);
    Route::get('reports/insurance-commission', [BusinessReportsController::class, 'insuranceCommission']);
    Route::get('reports/insurance-due', [BusinessReportsController::class, 'insuranceDue']);
    Route::get('reports/rto-work', [BusinessReportsController::class, 'rtoWork']);
    Route::get('reports/rto-profit', [BusinessReportsController::class, 'rtoProfit']);
    Route::get('reports/hsrp', [BusinessReportsController::class, 'hsrp']);
    Route::get('reports/vehicles', [BusinessReportsController::class, 'vehicles']);
    Route::get('reports/agent-work', [BusinessReportsController::class, 'agentWork']);

    Route::apiResource('fleets', FleetController::class)->except(['create','edit'])->middleware('erp.module:FLEET');
    Route::get('other-insurance/{line}', [OtherInsuranceController::class, 'index']);
    Route::post('other-insurance/{line}', [OtherInsuranceController::class, 'store']);
    Route::put('other-insurance/{line}/{id}', [OtherInsuranceController::class, 'update']);
    Route::delete('other-insurance/{line}/{id}', [OtherInsuranceController::class, 'destroy']);
    Route::get('service-works/{type}', [ServiceWorkController::class, 'index']);
    Route::post('service-works/{type}', [ServiceWorkController::class, 'store']);
    Route::put('service-works/{type}/{id}', [ServiceWorkController::class, 'update']);
    Route::delete('service-works/{type}/{id}', [ServiceWorkController::class, 'destroy']);
    Route::post('ocr', [OcrController::class, 'scan'])->middleware(['throttle:30,1', 'erp.module:RC_API']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::post('auth/refresh', [AuthController::class, 'refresh'])->middleware('throttle:60,1');
    Route::put('auth/password', [AuthController::class, 'change'])->middleware('throttle:passwords');
    Route::get('roles', [RoleController::class, 'index']);
    Route::apiResource('users', UserController::class);

    Route::get('ledgers', [LedgerController::class, 'index']);
    Route::post('ledgers', [LedgerController::class, 'store']);
    Route::get('accounting/vouchers', [AccountingController::class, 'vouchers']);
    Route::post('accounting/vouchers', [AccountingController::class, 'storeVoucher']);
    Route::get('accounting/day-book', [AccountingController::class, 'dayBook']);
    Route::get('accounting/ledger-statement/{ledgerId}', [AccountingController::class, 'ledgerStatement']);
    Route::get('accounting/trial-balance', [AccountingController::class, 'trialBalance']);
    Route::get('accounting/profit-loss', [AccountingController::class, 'profitLoss']);
    Route::get('accounting/balance-sheet', [AccountingController::class, 'balanceSheet']);
    Route::post('accounting/simple-entry', [FinanceControlController::class, 'simpleEntry']);
    Route::get('accounting/outstanding', [FinanceControlController::class, 'outstanding']);
    Route::get('accounting/outstanding/export', [FinanceControlController::class, 'outstandingExport']);
    Route::get('accounting/opening-balances', [FinanceControlController::class, 'openingBalances']);
    Route::put('accounting/opening-balances/{ledgerId}', [FinanceControlController::class, 'updateOpeningBalance']);
    Route::get('accounting/financial-year', [FinanceControlController::class, 'yearStatus']);
    Route::post('accounting/financial-year/lock', [FinanceControlController::class, 'lockYear']);
    Route::post('accounting/financial-year/unlock', [FinanceControlController::class, 'unlockYear']);

    Route::get('insurance-accounting/companies', [InsuranceAccountingController::class, 'companies']);
    Route::post('insurance-accounting/companies', [InsuranceAccountingController::class, 'storeCompany']);
    Route::put('insurance-accounting/companies/{id}', [InsuranceAccountingController::class, 'updateCompany']);
    Route::delete('insurance-accounting/companies/{id}', [InsuranceAccountingController::class, 'destroyCompany']);
    Route::get('insurance-accounting/purchase-sources', [InsuranceAccountingController::class, 'purchaseSources']);
    Route::post('insurance-accounting/purchase-sources', [InsuranceAccountingController::class, 'storePurchaseSource']);
    Route::put('insurance-accounting/purchase-sources/{id}', [InsuranceAccountingController::class, 'updatePurchaseSource']);
    Route::delete('insurance-accounting/purchase-sources/{id}', [InsuranceAccountingController::class, 'destroyPurchaseSource']);
    Route::get('insurance-accounting/commissions', [InsuranceAccountingController::class, 'commissions']);
    Route::post('insurance-accounting/commissions', [InsuranceAccountingController::class, 'storeCommission']);
    Route::post('insurance-accounting/commissions/{id}/receive', [InsuranceAccountingController::class, 'receiveCommission']);
    Route::get('insurance-accounting/summary', [InsuranceAccountingController::class, 'summary']);

    Route::get('claims', [InsuranceClaimController::class, 'index']);
    Route::post('claims', [InsuranceClaimController::class, 'store']);
    Route::get('claims/{id}', [InsuranceClaimController::class, 'show']);
    Route::put('claims/{id}', [InsuranceClaimController::class, 'update']);
    Route::post('claims/{id}/updates', [InsuranceClaimController::class, 'addNote']);
    Route::post('claims/{id}/documents', [InsuranceClaimController::class, 'saveDocument']);
    Route::post('claims/{id}/documents/{document}/verify', [InsuranceClaimController::class, 'verifyDocument']);
    Route::get('claims/{id}/documents/{document}/download', [InsuranceClaimController::class, 'downloadDocument']);
    Route::delete('claims/{id}/documents/{document}', [InsuranceClaimController::class, 'destroyDocument']);
    Route::delete('claims/{id}', [InsuranceClaimController::class, 'destroy']);

    Route::get('vehicles/export', [VehicleController::class, 'export']);
    Route::get('vehicle-masters/{type}', [VehicleMasterController::class, 'index']);
    Route::post('vehicle-masters/{type}', [VehicleMasterController::class, 'store']);
    Route::put('vehicle-masters/{type}/{id}', [VehicleMasterController::class, 'update']);
    Route::delete('vehicle-masters/{type}/{id}', [VehicleMasterController::class, 'destroy']);
    Route::post('vehicles/bulk-delete', [VehicleController::class, 'bulkDelete']);
    Route::post('vehicles/bulk-update', [VehicleController::class, 'bulkUpdate']);
    Route::post('vehicles/{vehicle}/archive', [VehicleController::class, 'archive']);
    Route::get('vehicles/{vehicle}/timeline', [VehicleController::class, 'timeline']);
    Route::get('vehicles/{vehicle}/operational-profile', [VehicleOperationsController::class, 'profile']);
    Route::get('vehicle-operation-masters/{type}', [VehicleOperationsController::class, 'index']);
    Route::post('vehicle-operation-masters/{type}', [VehicleOperationsController::class, 'storeMaster']);
    Route::put('vehicles/{vehicle}/module-override', [VehicleOperationsController::class, 'override']);
    Route::post('vehicles/{vehicle}/rto-work-accounting', [RtoWorkAccountingController::class, 'store']);
    Route::delete('vehicles/{vehicle}/rto-work-records/{record}', [RtoWorkRecordController::class, 'destroy']);
    Route::post('vehicles/{vehicle}/operations/payment', [VehiclePaymentAccountingController::class, 'store']);
    Route::delete('vehicles/{vehicle}/operations/payment/{record}', [VehiclePaymentAccountingController::class, 'destroy']);
    Route::get('vehicles/{vehicle}/operations/{module}', [VehicleOperationsController::class, 'index']);
    Route::post('vehicles/{vehicle}/operations/{module}', [VehicleOperationsController::class, 'store']);
    Route::put('vehicles/{vehicle}/operations/{module}/{record}', [VehicleOperationsController::class, 'update']);
    Route::delete('vehicles/{vehicle}/operations/{module}/{record}', [VehicleOperationsController::class, 'destroy']);
    Route::post('vehicles/{vehicle}/operations/{module}/{record}/documents', [VehicleOperationsController::class, 'uploadDocument']);
    Route::get('vehicles/{vehicle}/operation-documents/{document}', [VehicleOperationsController::class, 'downloadDocument']);
    Route::delete('vehicles/{vehicle}/operation-documents/{document}', [VehicleOperationsController::class, 'deleteDocument']);
    Route::get('vehicles/{vehicle}/insurances', [VehicleInsuranceController::class, 'index']);
    Route::post('vehicles/{vehicle}/insurance-calculation', [VehicleInsuranceController::class, 'calculate']);
    Route::post('vehicles/{vehicle}/insurances', [VehicleInsuranceController::class, 'store']);
    Route::put('vehicles/{vehicle}/insurances/{insurance}', [VehicleInsuranceController::class, 'update']);
    Route::delete('vehicles/{vehicle}/insurances/{insurance}', [VehicleInsuranceController::class, 'destroy']);
    Route::post('vehicles/{vehicle}/insurances/{insurance}/archive', [VehicleInsuranceController::class, 'archive']);
    Route::post('vehicles/{vehicle}/insurances/{insurance}/cancel', [VehicleInsuranceController::class, 'cancel']);
    Route::get('vehicles/{vehicle}/insurances/{insurance}/document', [VehicleInsuranceController::class, 'document']);
    Route::get('vehicles/{vehicle}/insurances/{insurance}/settlement', [InsurancePolicySettlementController::class, 'show']);
    Route::post('vehicles/{vehicle}/insurances/{insurance}/settlement', [InsurancePolicySettlementController::class, 'store']);
    Route::apiResource('vehicles', VehicleController::class)->middleware('erp.module:VEHICLES');

    Route::get('customers/export', [CustomerController::class, 'export']);
    Route::post('customers/bulk-delete', [CustomerController::class, 'bulkDelete']);
    Route::post('customers/bulk-assign', [CustomerController::class, 'bulkAssign']);
    Route::get('customers/{customer}/timeline', [CustomerController::class, 'timeline']);
    Route::apiResource('customers', CustomerController::class)->middleware('erp.module:CUSTOMERS');
});
