"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { DASHBOARD_REFRESH_EVENT } from "@/lib/dashboard-refresh";
import { PolicyReportSummary, policyApi } from "@/lib/policies";

const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(value||0));
export default function ReportsPage(){const [data,setData]=useState<PolicyReportSummary>(),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await policyApi.summary())}catch(caught){setError(caught instanceof Error?caught.message:"Report could not load.")}finally{setLoading(false)}},[]);useEffect(()=>{void load();const refresh=()=>void load();addEventListener(DASHBOARD_REFRESH_EVENT,refresh);addEventListener("focus",refresh);return()=>{removeEventListener(DASHBOARD_REFRESH_EVENT,refresh);removeEventListener("focus",refresh)}},[load]);const cards=[['Policies',data?.policy_count??0],['Gross Premium',money(data?.gross_premium??0)],['Gross Commission',money(data?.gross_commission??0)],['TDS',money(data?.tds??0)],['Agent Commission',money(data?.agent_commission??0)],['Commission Received',money(data?.commission_received??0)],['Commission Outstanding',money(data?.commission_outstanding??0)]];return <main className="space-y-6 p-4 md:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Reports</h1><p className="text-slate-500">Live policy and commission totals. Cancelled policies are excluded.</p></div><Link href="/policies" className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">View Policies</Link></header>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{loading?'…':value}</p></article>)}</section><p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-800">This report uses saved policy amounts and synchronized commission-register records; it never treats premium as business revenue.</p></main>}
