'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {BugReport,bugAgentApi} from '@/lib/bug-agent';

const severityStyle:Record<string,string>={critical:'bg-rose-100 text-rose-800 border-rose-200',high:'bg-orange-100 text-orange-800 border-orange-200',medium:'bg-amber-100 text-amber-800 border-amber-200',low:'bg-emerald-100 text-emerald-800 border-emerald-200',unknown:'bg-slate-100 text-slate-600 border-slate-200'};

export default function BugAgentPage(){
 const [reports,setReports]=useState<BugReport[]>([]);const [stats,setStats]=useState({total:0,open:0,critical:0,safe_fix:0});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [scanning,setScanning]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [pageUrl,setPageUrl]=useState('');const [file,setFile]=useState<File|null>(null);const [selected,setSelected]=useState<BugReport|null>(null);
 async function load(){try{const data=await bugAgentApi.list();setReports(data.reports);setStats(data.stats)}catch(e){setError(e instanceof Error?e.message:'Bug Agent could not load.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const latest=useMemo(()=>reports[0]??null,[reports]);
 async function submit(e:FormEvent){e.preventDefault();if(!file){setError('Upload a screenshot first.');return}setSaving(true);setError('');setSuccess('');try{const form=new FormData();form.set('title',title.trim()||'ERP screenshot bug');form.set('description',description.trim());form.set('page_url',pageUrl.trim()||location.href);form.set('screenshot',file);const report=await bugAgentApi.report(form);setSelected(report);setSuccess('Screenshot received. Bug Agent analysis completed.');setTitle('');setDescription('');setPageUrl('');setFile(null);const input=document.getElementById('bug-screenshot') as HTMLInputElement|null;if(input)input.value='';await load()}catch(e){setError(e instanceof Error?e.message:'Screenshot could not be analyzed.')}finally{setSaving(false)}}
 async function scan(){setScanning(true);setError('');setSuccess('');try{const result=await bugAgentApi.scanNow();setSuccess(result.healthy?'Health scan complete — no deterministic issue found.':`Health scan found ${result.findings.length} issue(s).`);await load()}catch(e){setError(e instanceof Error?e.message:'Health scan failed.')}finally{setScanning(false)}}
 async function reanalyze(r:BugReport){setError('');try{const updated=await bugAgentApi.analyze(r.id);setSelected(updated);setSuccess('Bug re-analyzed.');await load()}catch(e){setError(e instanceof Error?e.message:'Re-analysis failed.')}}
 async function resolve(r:BugReport){setError('');try{await bugAgentApi.resolve(r.id);setSuccess('Issue marked resolved.');setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Could not resolve issue.')}}
 async function safeFix(r:BugReport){if(!confirm('Run the approved safe repair for this issue?'))return;setError('');try{const result=await bugAgentApi.safeFix(r.id);setSuccess(result.result.message);setSelected(result.report);await load()}catch(e){setError(e instanceof Error?e.message:'Safe repair failed.')}}
 if(loading)return <main className="min-h-screen bg-[#f4f7fc] p-6 text-sm font-semibold text-slate-500">Loading Bug Agent…</main>;
 return <main className="min-h-screen bg-[#f4f7fc] pb-12 text-[#071a3c]"><div className="mx-auto max-w-7xl space-y-4 p-3 sm:p-5 lg:p-7">
  <section className="relative overflow-hidden rounded-[30px] bg-[#061936] p-6 text-white shadow-[0_24px_70px_rgba(7,26,60,.22)] sm:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_90%_0%,rgba(36,123,255,.55),transparent_34%),linear-gradient(130deg,#06152f,#0a285c_62%,#0d47b8)]"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/dashboard" className="text-xs font-bold text-blue-200">← Dashboard</Link><p className="mt-6 text-[9px] font-black uppercase tracking-[.24em] text-cyan-300">ERP Reliability · Internal only</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-5xl">Bug Agent</h1><p className="mt-3 max-w-2xl text-sm font-semibold leading-6 text-blue-100/75">Screenshot upload karo → AI visible bug ko triage karega. Major bugs review queue me jayenge. Safe low-risk repair hi auto-fix eligible hoga.</p></div><button onClick={()=>void scan()} disabled={scanning} className="h-12 rounded-2xl border border-white/15 bg-white/10 px-5 text-sm font-black text-white transition hover:bg-white/15 disabled:opacity-50">{scanning?'Scanning…':'↻ Scan ERP now'}</button></div>
   <div className="relative mt-6 grid grid-cols-2 overflow-hidden rounded-2xl border border-white/10 bg-black/10 sm:grid-cols-4"><TopStat label="Reports" value={stats.total}/><TopStat label="Open" value={stats.open}/><TopStat label="Critical" value={stats.critical} alert={stats.critical>0}/><TopStat label="Safe Fix Ready" value={stats.safe_fix}/></div>
  </section>
  {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}{success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">✓ {success}</div>}
  <section className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]">
   <form onSubmit={submit} className="overflow-hidden rounded-[26px] border border-[#dce6f4] bg-white shadow-[0_16px_45px_rgba(24,59,110,.07)]"><div className="border-b border-slate-100 bg-gradient-to-r from-white to-blue-50/50 p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Instant visual triage</p><h2 className="mt-1 text-2xl font-black">Report with screenshot</h2><p className="mt-1 text-xs font-semibold text-slate-500">Error message, wrong date/value, broken UI or unexpected screen — screenshot upload karo.</p></div><div className="grid gap-4 p-5">
    <label className="grid gap-1.5 text-xs font-black text-slate-600">Bug title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. PUC expiry one day wrong" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold outline-none focus:border-blue-400"/></label>
    <label className="grid gap-1.5 text-xs font-black text-slate-600">What happened<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="Expected kya tha aur actual kya dikh raha hai?" className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-semibold outline-none focus:border-blue-400"/></label>
    <label className="grid gap-1.5 text-xs font-black text-slate-600">Page URL<input value={pageUrl} onChange={e=>setPageUrl(e.target.value)} placeholder="Optional — current ERP page URL" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold outline-none focus:border-blue-400"/></label>
    <label className="grid gap-2 rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/40 p-5 text-center"><span className="text-3xl">📸</span><span className="text-sm font-black">Upload screenshot</span><span className="text-[10px] font-semibold text-slate-400">PNG / JPG / WEBP · max 12 MB</span><input id="bug-screenshot" type="file" accept="image/png,image/jpeg,image/webp" required onChange={e=>setFile(e.target.files?.[0]??null)} className="mx-auto max-w-full text-xs"/>{file&&<span className="text-xs font-black text-blue-700">{file.name}</span>}</label>
    <button disabled={saving||!file} className="h-13 rounded-2xl bg-[#0b2b62] px-5 py-4 text-sm font-black text-white shadow-[0_12px_28px_rgba(11,43,98,.22)] disabled:opacity-50">{saving?'Agent analyzing screenshot…':'⚡ Analyze Bug'}</button>
   </div></form>
   <article className="overflow-hidden rounded-[26px] border border-[#dce6f4] bg-white shadow-[0_16px_45px_rgba(24,59,110,.07)]"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-violet-600">Agent output</p><h2 className="mt-1 text-2xl font-black">{selected?'Selected diagnosis':'Latest diagnosis'}</h2></div>{(selected||latest)&&<Severity value={(selected||latest)!.severity}/>}</div>{selected||latest?<ReportDetail report={(selected||latest)!} onAnalyze={reanalyze} onResolve={resolve} onSafeFix={safeFix}/>:<div className="grid min-h-[420px] place-items-center p-8 text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-violet-50 text-3xl">🤖</div><p className="mt-4 font-black">No bug report yet</p><p className="mt-1 text-xs font-semibold text-slate-400">First screenshot upload karte hi diagnosis yaha dikhega.</p></div></div>}</article>
  </section>
  <section className="overflow-hidden rounded-[26px] border border-[#dce6f4] bg-white shadow-[0_16px_45px_rgba(24,59,110,.06)]"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Audit trail</p><h2 className="mt-1 text-2xl font-black">Bug history</h2></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-[10px] font-black text-blue-700">6 scans / day</span></div><div className="divide-y divide-slate-100">{reports.length?reports.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="grid w-full gap-2 p-4 text-left transition hover:bg-blue-50/40 sm:grid-cols-[110px_1fr_120px_120px] sm:items-center"><div><Severity value={r.severity}/></div><div className="min-w-0"><p className="truncate text-sm font-black text-slate-900">{r.title}</p><p className="mt-1 truncate text-[10px] font-semibold text-slate-400">{r.source==='scan'?'Automated scan':'Screenshot report'} · {r.category||'general'} · {formatDate(r.created_at)}</p></div><span className="text-[10px] font-black uppercase text-slate-500">{r.status.replaceAll('_',' ')}</span><span className="text-right text-[10px] font-black text-blue-600">View →</span></button>):<div className="p-8 text-center text-sm font-semibold text-slate-400">No reports yet.</div>}</div></section>
 </div></main>
}
function TopStat({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className="border-r border-white/10 p-4 last:border-r-0"><p className="text-[8px] font-black uppercase tracking-wider text-blue-200/60">{label}</p><p className={`mt-1 text-2xl font-black ${alert?'text-rose-300':'text-white'}`}>{value}</p></div>}
function Severity({value}:{value:string}){const v=value||'unknown';return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[9px] font-black uppercase tracking-wide ${severityStyle[v]||severityStyle.unknown}`}>{v}</span>}
function ReportDetail({report,onAnalyze,onResolve,onSafeFix}:{report:BugReport;onAnalyze:(r:BugReport)=>void;onResolve:(r:BugReport)=>void;onSafeFix:(r:BugReport)=>void}){return <div className="space-y-4 p-5"><div><p className="text-lg font-black text-slate-950">{report.title}</p><p className="mt-1 text-xs font-semibold text-slate-400">{report.category||'general'} · confidence {report.confidence??0}% · {formatDate(report.created_at)}</p></div><Block label="Diagnosis" value={report.diagnosis}/><Block label="Likely root cause" value={report.root_cause}/><Block label="Suggested developer fix" value={report.suggested_fix}/><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black">Automation gate</p><p className="mt-1 text-[10px] font-semibold text-slate-500">{report.auto_fix_eligible?'Whitelisted safe repair available.':'Code/data change needs developer review — no blind production edit.'}</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${report.auto_fix_eligible?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}`}>{report.auto_fix_eligible?'Safe fix':'Review'}</span></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>onAnalyze(report)} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-blue-700">Re-analyze</button>{report.auto_fix_eligible&&report.status!=='resolved'&&<button onClick={()=>onSafeFix(report)} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-black text-white">Run safe fix</button>}{report.status!=='resolved'&&<button onClick={()=>onResolve(report)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-600">Mark resolved</button>}</div></div>}
function Block({label,value}:{label:string;value?:string|null}){return <div><p className="text-[9px] font-black uppercase tracking-[.16em] text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm font-semibold leading-6 text-slate-700">{value||'—'}</p></div>}
function formatDate(v?:string|null){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}
