'use client';

import {FormEvent,useEffect,useState} from 'react';
import {InsuranceCompany,insuranceAccountingApi} from '@/lib/insurance-accounting';

const blank={company_name:'',short_code:'',agency_code_name:'',tds_percent:'0',contact_person:'',mobile:'',email:'',notes:'',status:'active'};

export default function InsuranceCompaniesPage(){
 const [rows,setRows]=useState<InsuranceCompany[]>([]),[search,setSearch]=useState(''),[form,setForm]=useState({...blank}),[editing,setEditing]=useState<InsuranceCompany>(),[viewing,setViewing]=useState<InsuranceCompany>(),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function load(){try{setRows(await insuranceAccountingApi.companies())}catch(e){setError(e instanceof Error?e.message:'Companies load nahi hui.')}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!saving){setOpen(false);setViewing(undefined)}};addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[saving]);
 function add(){setEditing(undefined);setForm({...blank});setOpen(true)}
 function edit(c:InsuranceCompany){setEditing(c);setForm({company_name:c.company_name,short_code:c.short_code||'',agency_code_name:c.agency_code_name||'',tds_percent:String(c.tds_percent),contact_person:c.contact_person||'',mobile:c.mobile||'',email:c.email||'',notes:c.notes||'',status:c.status});setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{const body={...form,tds_percent:Number(form.tds_percent),default_commission_percent:editing?.default_commission_percent||0,settlement_days:editing?.settlement_days||30};if(editing)await insuranceAccountingApi.updateCompany(editing.id,body);else await insuranceAccountingApi.addCompany(body);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Company save nahi hui.')}finally{setSaving(false)}}
 const filtered=rows.filter(c=>`${c.company_name} ${c.short_code||''} ${c.agency_code_name||''} ${c.mobile||''}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="space-y-5 p-4 md:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Insurance Companies</h1><p className="text-slate-500">Company codes and future commission-statement TDS settings.</p></div><button onClick={add} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">+ Add Company</button></header>{error&&<Alert>{error}</Alert>}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, short name, agency code or mobile" className="w-full rounded-xl border bg-white px-4 py-3"/><section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Company','Short Name','Agency Code / Code Name','TDS %','Contact','Mobile','Status','Actions'].map(h=><th className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(c=><tr className="border-t" key={c.id}><td className="p-4 font-bold">{c.company_name}</td><td>{c.short_code||'—'}</td><td>{c.agency_code_name||'—'}</td><td>{c.tds_percent}</td><td>{c.contact_person||'—'}</td><td>{c.mobile||'—'}</td><td><Badge active={c.status==='active'}/></td><td className="space-x-2"><button onClick={()=>setViewing(c)} className="rounded-lg border px-3 py-2">View</button><button onClick={()=>edit(c)} className="rounded-lg border px-3 py-2">Edit</button><button onClick={()=>void insuranceAccountingApi.updateCompany(c.id,{status:c.status==='active'?'inactive':'active'}).then(load)} className="rounded-lg border px-3 py-2">{c.status==='active'?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></section>{open&&<Modal title={editing?'Edit Insurance Company':'Add Insurance Company'} saving={saving} cancel={()=>setOpen(false)}><form onSubmit={save} className="grid gap-4 md:grid-cols-2">{Object.entries({company_name:'Company Name',short_code:'Short Name',agency_code_name:'Agency Code / Code Name',tds_percent:'TDS Percentage',contact_person:'Contact Person',mobile:'Mobile',email:'Email',notes:'Notes'}).map(([k,l])=><Field key={k} label={l} value={form[k as keyof typeof form]} set={v=>setForm(x=>({...x,[k]:v}))} required={k==='company_name'} type={k==='tds_percent'?'number':k==='email'?'email':'text'}/>)}<div className="flex justify-end gap-2 md:col-span-2"><button type="button" disabled={saving} onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{saving?'Saving…':'Save Company'}</button></div></form></Modal>}{viewing&&<Modal title="Insurance Company" saving={false} cancel={()=>setViewing(undefined)}><Details values={viewing}/></Modal>}</main>
}
function Modal({title,children,cancel,saving}:{title:string;children:React.ReactNode;cancel:()=>void;saving:boolean}){return <div onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)cancel()}} className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4"><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button disabled={saving} onClick={cancel} aria-label="Close">✕</button></div>{children}</section></div>}
function Field({label,value,set,type='text',required=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input required={required} min={type==='number'?0:undefined} max={type==='number'?100:undefined} step={type==='number'?'0.001':undefined} type={type} value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>}
function Badge({active}:{active:boolean}){return <span className={`rounded-full px-3 py-1 font-semibold ${active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{active?'Active':'Inactive'}</span>}
function Alert({children}:{children:React.ReactNode}){return <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{children}</div>}
function Details({values}:{values:InsuranceCompany}){return <dl className="grid gap-4 md:grid-cols-2">{Object.entries(values).filter(([k])=>!['id'].includes(k)).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold uppercase text-slate-400">{k.replaceAll('_',' ')}</dt><dd className="mt-1 font-semibold">{String(v??'—')}</dd></div>)}</dl>}
