'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { authenticatedRequest } from '@/lib/api-client';
import { vehicleInsuranceApi, type VehicleInsurancePolicy } from '@/lib/vehicle-insurance';

type Ledger={id:string;ledger_name:string;ledger_group:string};
type Settlement={settlement_type:string;bank_ledger_id?:string;party_name?:string;amount:number;payment_date:string;reference_number?:string}|null;
type Detail={policy:VehicleInsurancePolicy;settlement:Settlement;banks:Ledger[]};
const money=(n:number|string|undefined)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function PolicyFundingPanel(){
 const {vehicleId}=useParams<{vehicleId:string}>();
 const[policies,setPolicies]=useState<VehicleInsurancePolicy[]>([]);const[selected,setSelected]=useState('');const[detail,setDetail]=useState<Detail|null>(null);const[type,setType]=useState<'office_bank'|'direct_party'>('office_bank');const[bank,setBank]=useState('');const[party,setParty]=useState('');const[amount,setAmount]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[ref,setRef]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
 useEffect(()=>{if(!vehicleId)return;vehicleInsuranceApi.list(vehicleId).then(rows=>{const active=rows.filter(p=>p.status!=='cancelled');setPolicies(active);if(active[0])setSelected(active[0].id)}).catch(()=>undefined)},[vehicleId]);
 useEffect(()=>{if(!selected||!vehicleId){setDetail(null);return}authenticatedRequest<Detail>(`/vehicles/${vehicleId}/insurances/${selected}/settlement`).then(d=>{setDetail(d);setAmount(String(Number(d.policy.customer_pay||0)));if(d.settlement){setType(d.settlement.settlement_type as typeof type);setBank(d.settlement.bank_ledger_id||'');setParty(d.settlement.party_name||'');setAmount(String(d.settlement.amount||d.policy.customer_pay||0));setDate(d.settlement.payment_date||date);setRef(d.settlement.reference_number||'')}}).catch(e=>setErr(e instanceof Error?e.message:'Funding details could not load.'))},[selected,vehicleId]);
 const policy=useMemo(()=>policies.find(p=>p.id===selected),[policies,selected]);
 async function save(){if(!selected||!vehicleId)return;setBusy(true);setErr('');setMsg('');try{const d=await authenticatedRequest<Detail>(`/vehicles/${vehicleId}/insurances/${selected}/settlement`,{method:'POST',body:JSON.stringify({settlement_type:type,bank_ledger_id:type==='office_bank'?bank:null,party_name:type==='direct_party'?party:null,amount:Number(amount||0),payment_date:date,reference_number:ref||null})});setDetail(d);setMsg(type==='office_bank'?'Company premium payment recorded. Customer receivable remains until customer pays you.':'Direct company payment recorded. Customer premium due cleared for this policy.')}catch(e){setErr(e instanceof Error?e.message:'Payment could not be recorded.')}finally{setBusy(false)}}
 if(!policies.length)return null;
 return <section className="mx-auto mb-8 max-w-[1500px] rounded-[28px] border border-[#dbe6f3] bg-white p-5 shadow-[0_16px_46px_rgba(15,23,42,.07)] md:p-6">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Policy Funding</p><h2 className="mt-1 text-2xl font-black text-[#0b2754]">Who paid the insurance company?</h2><p className="mt-1 max-w-3xl text-xs font-semibold leading-5 text-slate-500">Company payment and customer recovery are two different things. Recording company payment does not automatically mean the customer has paid you.</p></div><div className="rounded-2xl bg-blue-50 px-4 py-3 text-right"><p className="text-[9px] font-black uppercase text-blue-500">Customer Pay</p><p className="text-xl font-black text-blue-900">{money(policy?.customer_pay)}</p></div></div>
  {err&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{err}</div>}{msg&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{msg}</div>}
  <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-6">
   <label className="grid gap-1.5 text-xs font-black text-slate-600 xl:col-span-2">Policy<select value={selected} onChange={e=>setSelected(e.target.value)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold">{policies.map(p=><option key={p.id} value={p.id}>{p.policy_number} · {money(p.customer_pay)}</option>)}</select></label>
   <label className="grid gap-1.5 text-xs font-black text-slate-600 xl:col-span-2">Company Payment Mode<select value={type} onChange={e=>setType(e.target.value as typeof type)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"><option value="office_bank">Paid by us — Bank / Cash</option><option value="direct_party">Paid directly by customer / party</option></select></label>
   <label className="grid gap-1.5 text-xs font-black text-slate-600">Amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0" step="0.01" className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>
   <label className="grid gap-1.5 text-xs font-black text-slate-600">Date<input value={date} onChange={e=>setDate(e.target.value)} type="date" className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>
   {type==='office_bank'?<label className="grid gap-1.5 text-xs font-black text-slate-600 xl:col-span-3">Bank / Cash Account<select value={bank} onChange={e=>setBank(e.target.value)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"><option value="">Select account</option>{detail?.banks.map(b=><option key={b.id} value={b.id}>{b.ledger_name} · {b.ledger_group}</option>)}</select></label>:<label className="grid gap-1.5 text-xs font-black text-slate-600 xl:col-span-3">Party who paid company<input value={party} onChange={e=>setParty(e.target.value)} placeholder="Customer / agent / broker / fleet" className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>}
   <label className="grid gap-1.5 text-xs font-black text-slate-600 xl:col-span-2">Reference / UTR<input value={ref} onChange={e=>setRef(e.target.value)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>
   <div className="flex items-end"><button type="button" disabled={busy} onClick={()=>void save()} className="h-12 w-full rounded-2xl bg-gradient-to-r from-[#0b2f6b] to-[#2563eb] px-5 text-sm font-black text-white shadow-lg disabled:opacity-50">{busy?'Saving…':'Record Company Payment'}</button></div>
  </div>
  {detail?.settlement&&<div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50/70 px-4 py-3 text-xs font-bold text-emerald-800">Recorded: {detail.settlement.settlement_type==='office_bank'?'Office paid company':'Party paid company directly'} · {money(detail.settlement.amount)} · {detail.settlement.payment_date}</div>}
 </section>
}
