'use client';

import { useEffect, useMemo, useState } from 'react';
import { authenticatedRequest } from '@/lib/api-client';
import { vehicleInsuranceApi, type VehicleInsurancePolicy } from '@/lib/vehicle-insurance';

type Ledger={id:string;ledger_name:string;ledger_group:string};
type Settlement={settlement_type:string;bank_ledger_id?:string;party_name?:string;amount:number;payment_date:string;reference_number?:string}|null;
type Detail={policy:VehicleInsurancePolicy;settlement:Settlement;banks:Ledger[]};
const money=(n:number|string|undefined)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function PolicyFundingPanel({vehicleId,open,onClose,defaultPolicyId}:{vehicleId:string;open:boolean;onClose:()=>void;defaultPolicyId?:string}){
 const[policies,setPolicies]=useState<VehicleInsurancePolicy[]>([]);const[selected,setSelected]=useState('');const[detail,setDetail]=useState<Detail|null>(null);const[type,setType]=useState<'office_bank'|'direct_party'>('office_bank');const[bank,setBank]=useState('');const[party,setParty]=useState('');const[amount,setAmount]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[ref,setRef]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
 useEffect(()=>{if(!open)return;vehicleInsuranceApi.list(vehicleId).then(rows=>{const live=rows.filter(p=>p.status!=='cancelled'&&!p.archived_at);setPolicies(live);const pick=defaultPolicyId&&live.some(p=>p.id===defaultPolicyId)?defaultPolicyId:live[0]?.id||'';setSelected(pick)}).catch(e=>setErr(e instanceof Error?e.message:'Policies could not load.'))},[open,vehicleId,defaultPolicyId]);
 useEffect(()=>{if(!open||!selected)return;authenticatedRequest<Detail>(`/vehicles/${vehicleId}/insurances/${selected}/settlement`).then(d=>{setDetail(d);setAmount(String(Number(d.policy.customer_pay||0)));setMsg('');setErr('');if(d.settlement){setType(d.settlement.settlement_type as typeof type);setBank(d.settlement.bank_ledger_id||'');setParty(d.settlement.party_name||'');setAmount(String(d.settlement.amount||d.policy.customer_pay||0));setDate(d.settlement.payment_date||date);setRef(d.settlement.reference_number||'')}}).catch(e=>setErr(e instanceof Error?e.message:'Payment details could not load.'))},[open,selected,vehicleId]);
 const policy=useMemo(()=>policies.find(p=>p.id===selected),[policies,selected]);
 async function save(){if(!selected)return;setBusy(true);setErr('');setMsg('');try{const d=await authenticatedRequest<Detail>(`/vehicles/${vehicleId}/insurances/${selected}/settlement`,{method:'POST',body:JSON.stringify({settlement_type:type,bank_ledger_id:type==='office_bank'?bank:null,party_name:type==='direct_party'?party:null,amount:Number(amount||0),payment_date:date,reference_number:ref||null})});setDetail(d);setMsg(type==='office_bank'?'Company payment saved. Customer outstanding remains until collection.':'Direct party payment saved. Customer premium due is cleared.');window.dispatchEvent(new CustomEvent('raj:insurance-payment-saved',{detail:{vehicleId,policyId:selected}}))}catch(e){setErr(e instanceof Error?e.message:'Payment could not be recorded.')}finally{setBusy(false)}}
 if(!open)return null;
 return <div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/55 p-3 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
  <div className="w-full max-w-3xl overflow-hidden rounded-[28px] border border-white/20 bg-white shadow-[0_30px_100px_rgba(2,12,35,.35)]">
   <div className="flex items-start justify-between bg-gradient-to-r from-[#071a3c] via-[#0b2f6b] to-[#2563eb] px-5 py-5 text-white md:px-7"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-cyan-200">Insurance payment</p><h2 className="mt-1 text-2xl font-black">Pay company / mark direct payment</h2><p className="mt-1 text-xs font-semibold text-blue-100">Company funding and customer collection stay separate.</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full border border-white/20 bg-white/10 text-xl font-bold">×</button></div>
   <div className="p-5 md:p-7">{err&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{err}</div>}{msg&&<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{msg}</div>}
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-1.5 text-xs font-black text-slate-600">Policy<select value={selected} onChange={e=>setSelected(e.target.value)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold">{policies.map(p=><option key={p.id} value={p.id}>{p.policy_number} · {money(p.customer_pay)}</option>)}</select></label><div className="rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3"><p className="text-[9px] font-black uppercase text-blue-500">Customer Pay</p><p className="text-2xl font-black text-blue-950">{money(policy?.customer_pay)}</p></div>
     <label className="grid gap-1.5 text-xs font-black text-slate-600">Payment Mode<select value={type} onChange={e=>setType(e.target.value as typeof type)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"><option value="office_bank">Paid by us — Bank / Cash</option><option value="direct_party">Paid directly by customer / party</option></select></label><label className="grid gap-1.5 text-xs font-black text-slate-600">Date<input value={date} onChange={e=>setDate(e.target.value)} type="date" className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>
     {type==='office_bank'?<label className="grid gap-1.5 text-xs font-black text-slate-600">Bank / Cash Account<select value={bank} onChange={e=>setBank(e.target.value)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"><option value="">Select account</option>{detail?.banks.map(b=><option key={b.id} value={b.id}>{b.ledger_name} · {b.ledger_group}</option>)}</select></label>:<label className="grid gap-1.5 text-xs font-black text-slate-600">Party who paid company<input value={party} onChange={e=>setParty(e.target.value)} placeholder="Customer / broker / fleet" className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>}
     <label className="grid gap-1.5 text-xs font-black text-slate-600">Amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0" step="0.01" className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label><label className="grid gap-1.5 text-xs font-black text-slate-600 md:col-span-2">Reference / UTR<input value={ref} onChange={e=>setRef(e.target.value)} className="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold"/></label>
    </div>
    <div className="mt-6 flex justify-end gap-3"><button onClick={onClose} className="h-12 rounded-2xl border border-slate-200 px-5 text-sm font-black text-slate-600">Close</button><button disabled={busy||!!detail?.settlement} onClick={()=>void save()} className="h-12 rounded-2xl bg-gradient-to-r from-[#0b2f6b] to-[#2563eb] px-6 text-sm font-black text-white shadow-lg disabled:opacity-50">{detail?.settlement?'Payment Already Recorded':busy?'Saving…':'Save Payment'}</button></div>
    {detail?.settlement&&<div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-800">✓ {detail.settlement.settlement_type==='office_bank'?'Company paid from office account':'Company paid directly by party'} · {money(detail.settlement.amount)} · {detail.settlement.payment_date}</div>}
   </div>
  </div>
 </div>
}
