'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CommissionRow, CommissionSummary, InsuranceCompany, PurchaseSource, insuranceAccountingApi } from '@/lib/insurance-accounting';

const money = (value:number) => `₹${Number(value || 0).toFixed(2)}`;

export default function InsuranceAccountingPage() {
  const [companies,setCompanies]=useState<InsuranceCompany[]>([]);
  const [sources,setSources]=useState<PurchaseSource[]>([]);
  const [rows,setRows]=useState<CommissionRow[]>([]);
  const [summary,setSummary]=useState<CommissionSummary>({gross_commission:0,tds_receivable:0,net_receivable:0,received:0,outstanding:0});
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [saving,setSaving]=useState(false);
  const [companySearch,setCompanySearch]=useState('');

  async function load(){
    try { const [c,p,r,s]=await Promise.all([insuranceAccountingApi.companies(),insuranceAccountingApi.purchaseSources(),insuranceAccountingApi.commissions(),insuranceAccountingApi.summary()]); setCompanies(c);setSources(p);setRows(r);setSummary(s); }
    catch(e){ const m=e instanceof Error?e.message:'Data load nahi hua.'; if(/unauthenticated|401/i.test(m)){sessionStorage.removeItem('raj_erp_token');location.href='/login';} else setError(m); }
  }
  useEffect(()=>{void load();},[]);

  async function addCompany(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget;const f=new FormData(el);setSaving(true);setError('');setSuccess('');try{await insuranceAccountingApi.addCompany({company_name:f.get('company_name'),short_code:f.get('short_code'),agency_code_name:f.get('agency_code_name'),default_commission_percent:Number(f.get('default_commission_percent')||0),tds_percent:Number(f.get('tds_percent')||0),settlement_days:Number(f.get('settlement_days')||30),gst_number:f.get('gst_number'),pan_number:f.get('pan_number'),contact_person:f.get('contact_person'),mobile:f.get('mobile'),email:f.get('email'),notes:f.get('notes')});el.reset();setSuccess('Insurance company aur uska ledger create ho gaya.');await load();}catch(x){setError(x instanceof Error?x.message:'Company create nahi hui.');}finally{setSaving(false)}}
  async function addSource(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setSaving(true);try{await insuranceAccountingApi.addPurchaseSource({name:f.get('name'),source_type:f.get('source_type'),mobile:f.get('mobile'),email:f.get('email'),linked_company_id:f.get('linked_company_id')||null,tds_applicable:false,tds_percent:0,is_active:true,notes:f.get('notes')});el.reset();setSuccess('Purchase source created.');await load()}catch(x){setError(x instanceof Error?x.message:'Purchase source create nahi hua.')}finally{setSaving(false)}}

  async function addCommission(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget;const f=new FormData(el);setSaving(true);setError('');setSuccess('');try{await insuranceAccountingApi.addCommission({insurance_company_id:f.get('insurance_company_id'),statement_number:f.get('statement_number'),statement_date:f.get('statement_date'),policy_number:f.get('policy_number'),customer_name:f.get('customer_name'),gross_premium:Number(f.get('gross_premium')||0),commission_percent:Number(f.get('commission_percent')||0),gross_commission:Number(f.get('gross_commission')||0),tds_percent:Number(f.get('tds_percent')||0),remarks:f.get('remarks')});el.reset();setSuccess('Commission entry save ho gayi. TDS aur net receivable automatic calculate hua.');await load();}catch(x){setError(x instanceof Error?x.message:'Commission save nahi hui.');}finally{setSaving(false)}}

  return <main className="space-y-6 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Insurance Company Accounting</h1><p className="text-slate-500">Company, commission statement, TDS aur receipt management.</p></div><div className="flex gap-2"><a href="/accounts" className="rounded-xl border px-4 py-2">Accounts</a><a href="/dashboard" className="rounded-xl border px-4 py-2">Dashboard</a></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{success}</div>}
    <div className="grid gap-4 md:grid-cols-5">{[['Gross Commission',summary.gross_commission],['TDS Receivable',summary.tds_receivable],['Net Receivable',summary.net_receivable],['Received',summary.received],['Outstanding',summary.outstanding]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-xl font-bold">{money(Number(v))}</p></div>)}</div>

    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Add Insurance Company</h2><form onSubmit={addCompany} className="mt-4 grid gap-4 md:grid-cols-4">
      <Input name="company_name" label="Company Name" required/><Input name="short_code" label="Short Name"/><Input name="agency_code_name" label="Company / Agency Code Name"/><Input name="default_commission_percent" label="Default Commission %" type="number" step="0.001"/><Input name="tds_percent" label="TDS %" type="number" step="0.001" required/>
      <Input name="settlement_days" label="Settlement Days" type="number" defaultValue="30"/><Input name="gst_number" label="GST Number"/><Input name="pan_number" label="PAN Number"/><Input name="contact_person" label="Contact Person"/><Input name="mobile" label="Mobile"/><Input name="email" label="Email" type="email"/><Input name="notes" label="Notes"/>
      <div className="md:col-span-2"><button disabled={saving} className="rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white disabled:opacity-60">Create Company</button></div></form><input value={companySearch} onChange={e=>setCompanySearch(e.target.value)} placeholder="Search company, short name or agency code" className="mt-6 w-full rounded-xl border px-4 py-3"/><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Company</th><th>Short Name</th><th>Agency Code</th><th>TDS</th><th>Status</th><th>Action</th></tr></thead><tbody>{companies.filter(c=>`${c.company_name} ${c.short_code||''} ${c.agency_code_name||''}`.toLowerCase().includes(companySearch.toLowerCase())).map(c=><tr className="border-t" key={c.id}><td className="p-3 font-semibold">{c.company_name}</td><td>{c.short_code||'—'}</td><td>{c.agency_code_name||'—'}</td><td>{c.tds_percent}%</td><td>{c.status}</td><td><button onClick={()=>void insuranceAccountingApi.updateCompany(c.id,{status:c.status==='active'?'inactive':'active'}).then(load)} className="rounded-lg border px-3 py-2">{c.status==='active'?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></section>

    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Purchase Source / Agent Master</h2><form onSubmit={addSource} className="mt-4 grid gap-4 md:grid-cols-4"><Input name="name" label="Name" required/><label className="text-sm font-semibold">Source Type<select name="source_type" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="individual_agent">Individual Agent</option><option value="insurance_broker">Insurance Broker</option><option value="agency">Agency</option><option value="other">Other</option></select></label><Input name="mobile" label="Mobile"/><Input name="email" label="Email" type="email"/><label className="text-sm font-semibold">Company Association<select name="linked_company_id" className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">None</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><Input name="notes" label="Notes"/><button disabled={saving} className="rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white">Create Source</button></form><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Name</th><th>Type</th><th>Mobile</th><th>TDS</th><th>Status</th><th>Action</th></tr></thead><tbody>{sources.map(s=><tr className="border-t" key={s.id}><td className="p-3 font-semibold">{s.name}</td><td>{s.source_type.replaceAll('_',' ')}</td><td>{s.mobile||'—'}</td><td>{s.tds_applicable?`${s.tds_percent}%`:'Not Applicable'}</td><td>{s.is_active?'Active':'Inactive'}</td><td><button onClick={()=>void insuranceAccountingApi.updatePurchaseSource(s.id,{name:s.name,source_type:s.source_type,mobile:s.mobile||null,email:s.email||null,linked_company_id:s.linked_company_id||null,tds_applicable:s.tds_applicable,tds_percent:s.tds_percent,is_active:!s.is_active,notes:s.notes||null}).then(load)} className="rounded-lg border px-3 py-2">{s.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></section>

    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Commission Entry</h2><form onSubmit={addCommission} className="mt-4 grid gap-4 md:grid-cols-4">
      <label className="text-sm font-semibold">Insurance Company<select name="insurance_company_id" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3 font-normal"><option value="">Select Company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label>
      <Input name="statement_number" label="Statement Number"/><Input name="statement_date" label="Statement Date" type="date" required/><Input name="policy_number" label="Policy Number"/><Input name="customer_name" label="Customer Name"/><Input name="gross_premium" label="Gross Premium" type="number" step="0.01"/><Input name="commission_percent" label="Commission %" type="number" step="0.001" required/><Input name="gross_commission" label="Gross Commission (optional)" type="number" step="0.01"/><Input name="tds_percent" label="TDS %" type="number" step="0.001" required/><Input name="remarks" label="Remarks"/>
      <div className="md:col-span-2"><button disabled={saving} className="rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white disabled:opacity-60">Save Commission</button></div></form></section>

    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-lg font-bold">Commission Statement</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Date','Company','Policy','Gross Commission','TDS','Net','Received','Outstanding','Status'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.statement_date}</td><td className="p-3 font-semibold">{r.company_name}</td><td className="p-3">{r.policy_number||'-'}</td><td className="p-3">{money(r.gross_commission)}</td><td className="p-3">{money(r.tds_amount)}</td><td className="p-3">{money(r.net_receivable)}</td><td className="p-3">{money(r.received_amount)}</td><td className="p-3 font-semibold">{money(r.net_receivable-r.received_amount)}</td><td className="p-3 uppercase">{r.status}</td></tr>)}</tbody></table></div></section>
  </main>;
}

function Input({name,label,type='text',required=false,step,defaultValue}:{name:string;label:string;type?:string;required?:boolean;step?:string;defaultValue?:string}){return <label className="text-sm font-semibold">{label}{required&&<span className="text-red-500"> *</span>}<input name={name} type={type} required={required} step={step} defaultValue={defaultValue} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>}
