<?php
namespace App\Support\ErpControl;
enum ErpModule:string { case CUSTOMERS='CUSTOMERS'; case VEHICLES='VEHICLES'; case POLICIES='POLICIES'; case RENEWALS='RENEWALS'; case CLAIMS='CLAIMS'; case RTO='RTO'; case ACCOUNTING='ACCOUNTING'; case DOCUMENTS='DOCUMENTS'; case REPORTS='REPORTS'; case AGENTS='AGENTS'; case DEALERS='DEALERS'; case FLEET='FLEET'; case WHATSAPP='WHATSAPP'; case RC_API='RC_API'; case PAYMENTS='PAYMENTS'; }
