'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Icon} from '@/components/dashboard/Icon';
import {DashboardSummary,getDashboardSummary} from '@/lib/dashboard-api';

const masters=[
 {category:'Vehicle',key:'manufacturers',title:'Vehicle Manufacturers',description:'Brands used throughout vehicle entry',href:'/vehicle-manufacturers',icon:'factory'},
 {category:'Vehicle',key:'models',title:'Vehicle Models',description:'Manufacturer-linked model catalogue',href:'/vehicle-models',icon:'vehicle'},
 {category:'Vehicle',key:'variants',title:'Vehicle Variants',description:'Model-linked vehicle variants',href:'/vehicle-variants',icon:'vehicle'},
 {category:'Vehicle',key:'colours',title:'Vehicle Colours',description:'Standard colours for vehicle records',href:'/vehicle-colours',icon:'palette'},
 {category:'Vehicle',key:'vehicle_types',title:'Vehicle Types',description:'Private, two-wheeler and commercial vehicle types',href:'/vehicle-types',icon:'grid'},
 {category:'Vehicle',key:'vehicle_classes',title:'Vehicle Classes',description:'Transport and registration classes',href:'/vehicle-classes',icon:'grid'},
 {category:'Vehicle',key:'body_types',title:'Body Types & Categories',description:'Vehicle shapes and operating categories',href:'/vehicle-body-types',icon:'vehicle'},
 {category:'Vehicle',key:'fuel_types',title:'Fuel Types',description:'Approved fuel and powertrain options',href:'/fuel-types',icon:'fuel'},
 {category:'Vehicle',key:'rto_offices',title:'RTO Offices',description:'Gujarat registration authorities used in vehicle and RTO work',href:'/rto-offices',icon:'building'},
 {category:'Vehicle',key:'rto_work_types',title:'RTO Work Types',description:'Work types used in the vehicle RTO process desk',href:'/rto-work-types',icon:'settings'},
 {category:'Insurance',key:'insurance_companies',title:'Insurance Companies',description:'Insurers, agency codes and contacts',href:'/insurance-companies',icon:'shield'},
 {category:'Insurance',key:'insurance_purchase_sources',title:'Purchase Sources',description:'Agents and intermediaries used in policies',href:'/purchase-sources',icon:'handshake'},
 {category:'Accounts',key:'ledgers',title:'Ledgers',description:'Accounting ledgers and opening balances',href:'/accounts/ledgers',icon:'book'},
];
export default function MastersPage(){const [summary,setSummary]=useState<DashboardSummary>();const [search,setSearch]=useState('');const [category,setCategory]=useState('All');const [status,setStatus]=useState('All');const [error,setError]=useState('');useEffect(()=>{getDashboardSummary().then(setSummary).catch(e=>setError(e instanceof Error?e.message:'Master counts could not load.'))},[]);const filtered=useMemo(()=>masters.filter(item=>(category==='All'||item.category===category)&&(`${item.title} ${item.description} ${item.category}`.toLowerCase().includes(search.toLowerCase()))&&(status==='All'||(status==='Active'?(summary?.master_counts[item.key]?.active??0)>0:(summary?.master_counts[item.key]?.total??0)>(summary?.master_counts[item.key]?.active??0)))),[search,category,status,summary]);return <div className="mx-auto max-w-[1600px] space-y-6 p-4 sm:p-6 lg:p-8">
<section className="overflow-hidden rounded-[28px] bg-gradient-to-r from-blue-950 via-blue-800 to-indigo-700 p-7 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-200">Configuration centre</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Masters Hub</h1><p className="mt-2 max-w-2xl text-sm text-blue-100/80">One reliable place to maintain the data used across vehicle, RTO, insurance and accounts workflows.</p></section>
<section className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 md:grid-cols-[1fr_auto_auto]"><label className="relative"><Icon name="search" className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search masters, e.g. RTO or model" className="w-full rounded-xl border py-3 pl-10 pr-3 outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-800"/></label><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-800"><option>All</option><option>Vehicle</option><option>Insurance</option><option>Accounts</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-800"><option>All</option><option>Active</option><option>Inactive</option></select></section>
{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</div>}
{['Vehicle','Insurance','Accounts'].map(group=>{const items=filtered.filter(x=>x.category===group);return items.length?<section key={group}><div className="mb-3 flex items-end justify-between"><div><h2 className="text-xl font-black">{group} Masters</h2><p className="text-sm text-slate-500">{items.length} management modules</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item,index)=><MasterCard key={item.key} item={item} count={summary?.master_counts[item.key]} featured={index<2}/>)}</div></section>:null})}
{!filtered.length&&<div className="rounded-2xl border border-dashed p-12 text-center"><h2 className="font-black">No masters found</h2><p className="mt-1 text-sm text-slate-500">Try a different search or filter.</p></div>}
<section className="rounded-2xl border border-dashed border-slate-300 bg-slate-100/50 p-5 dark:border-slate-700 dark:bg-slate-900/40"><h2 className="font-bold">Planned master modules</h2><p className="mt-1 text-sm text-slate-500">Banks, Payment Modes, GST Rates, Branches, Employees, Departments and Document Types will appear here when their management routes are implemented.</p></section>
</div>}
function MasterCard({item,count,featured}:{item:typeof masters[number];count?:{total:number;active:number};featured:boolean}){return <article className={`group relative overflow-hidden rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900 ${featured?'xl:min-h-56':''}`}><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-blue-50 text-blue-700 dark:bg-blue-500/10"><Icon name={item.icon} className="h-6 w-6"/></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-800">{item.category}</span></div><h3 className="mt-4 font-black">{item.title}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-slate-500">{item.description}</p><div className="mt-4 flex gap-5 text-xs"><span><strong className="block text-lg text-slate-900 dark:text-white">{count?.total??0}</strong>Total</span><span><strong className="block text-lg text-emerald-600">{count?.active??0}</strong>Active</span></div><div className="mt-5 flex gap-2"><Link href={`${item.href}?add=1`} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">+ Add</Link><Link href={item.href} className="rounded-lg border px-3 py-2 text-xs font-bold">View all</Link></div></article>}
