<?php
namespace Tests\Feature;
use App\Models\Branch; use App\Models\ErpModuleEntitlement; use App\Models\Tenant; use App\Models\User; use App\Support\ErpControl\BranchContext; use Illuminate\Foundation\Testing\RefreshDatabase; use Laravel\Sanctum\Sanctum; use Tests\TestCase;
class ErpControlFoundationTest extends TestCase { use RefreshDatabase;
 private function tenant(string $status='ACTIVE'):Tenant{return Tenant::query()->create(['name'=>'Vimawallah','code'=>'VIMAWALLAH','slug'=>'vimawallah','tenant_type'=>'VIMAWALLAH_INTERNAL','erp_status'=>$status,'erp_environment'=>'DEVELOPMENT','erp_base_url'=>'https://erp.vimawallah.com','erp_tenant_url'=>'https://erp.vimawallah.com']);}
 public function test_protected_health_reports_control_state_without_secrets():void{$tenant=$this->tenant();$user=User::factory()->create(['tenant_id'=>$tenant->id]);Branch::query()->create(['tenant_id'=>$tenant->id,'name'=>'Dhanera','code'=>'VIMA-DHN-001']);ErpModuleEntitlement::query()->create(['tenant_id'=>$tenant->id,'module_key'=>'CUSTOMERS','is_enabled'=>true]);Sanctum::actingAs($user);$this->getJson('/api/v1/internal/erp-control/health')->assertOk()->assertJsonPath('tenant_code','VIMAWALLAH')->assertJsonPath('tenant_status','ACTIVE')->assertJsonFragment(['VIMA-DHN-001'])->assertJsonMissing(['secret']);}
 public function test_suspended_tenant_is_blocked_from_normal_routes_but_health_remains_available():void{$tenant=$this->tenant('SUSPENDED');$user=User::factory()->create(['tenant_id'=>$tenant->id]);Sanctum::actingAs($user);$this->getJson('/api/v1/dashboard/summary')->assertStatus(423)->assertJsonPath('error.code','ERP_SUSPENDED');$this->getJson('/api/v1/internal/erp-control/health')->assertOk();}
 public function test_disabled_module_is_enforced_server_side():void{$tenant=$this->tenant();$user=User::factory()->create(['tenant_id'=>$tenant->id]);ErpModuleEntitlement::query()->create(['tenant_id'=>$tenant->id,'module_key'=>'CUSTOMERS','is_enabled'=>false]);Sanctum::actingAs($user);$this->getJson('/api/v1/customers')->assertForbidden();}
 public function test_branch_context_rejects_cross_tenant_branches():void{$tenant=$this->tenant();$other=Tenant::query()->create(['name'=>'Other','code'=>'OTHER','slug'=>'other']);$user=User::factory()->create(['tenant_id'=>$tenant->id,'has_tenant_wide_branch_access'=>false]);Branch::query()->create(['tenant_id'=>$other->id,'name'=>'Other','code'=>'OTHER-001']);$this->expectException(\Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException::class);app(BranchContext::class)->resolve($user,'OTHER-001');}
}
