<?php
namespace Tests\Feature;
use App\Models\Permission; use App\Models\Role; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Hash; use Tests\TestCase;
class IdentityManagementTest extends TestCase { use RefreshDatabase; private function admin(string $tenant):User{$permission=Permission::create(['name'=>'users.view']);$role=Role::create(['tenant_id'=>$tenant,'name'=>'Manager','slug'=>'manager']);$role->permissions()->attach($permission);$user=User::factory()->create(['tenant_id'=>$tenant,'is_admin'=>true]);return $user;}
 public function test_login_is_tenant_aware_and_refresh_rotates_token():void{$tenant='00000000-0000-4000-8000-000000000001';User::factory()->create(['tenant_id'=>$tenant,'email'=>'person@example.com','password'=>'Password12345']);$login=$this->postJson('/api/v1/auth/login',['tenant_id'=>$tenant,'email'=>'person@example.com','password'=>'Password12345']);$token=$login->assertOk()->json('data.token');$this->withToken($token)->postJson('/api/v1/auth/refresh')->assertOk()->assertJsonStructure(['data'=>['token','token_type']]);$this->withToken($token)->postJson('/api/v1/auth/logout')->assertUnauthorized();}
 public function test_admin_crud_is_tenant_scoped_and_audited():void{$tenant='00000000-0000-4000-8000-000000000001';$admin=$this->admin($tenant);$response=$this->actingAs($admin)->postJson('/api/v1/users',['name'=>'Operator','email'=>'operator@example.com','password'=>'SecurePassword123','password_confirmation'=>'SecurePassword123','is_active'=>true]);$id=$response->assertCreated()->json('data.id');$this->assertDatabaseHas('users',['id'=>$id,'tenant_id'=>$tenant]);$this->assertDatabaseHas('audit_logs',['action'=>'user.created','auditable_id'=>$id]);}
 public function test_disabled_users_cannot_login():void{$tenant='00000000-0000-4000-8000-000000000001';User::factory()->create(['tenant_id'=>$tenant,'email'=>'disabled@example.com','password'=>'Password12345','is_active'=>false]);$this->postJson('/api/v1/auth/login',['tenant_id'=>$tenant,'email'=>'disabled@example.com','password'=>'Password12345'])->assertUnprocessable();}
 public function test_change_password_revokes_other_tokens():void{$user=User::factory()->create(['password'=>'OldPassword123']);$user->createToken('mobile');$token=$user->createToken('web')->plainTextToken;$this->withToken($token)->putJson('/api/v1/auth/password',['current_password'=>'OldPassword123','password'=>'NewPassword1234','password_confirmation'=>'NewPassword1234'])->assertOk();$this->assertTrue(Hash::check('NewPassword1234',$user->refresh()->password));$this->assertCount(1,$user->tokens);}
}
