"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {InsuranceLine,OtherInsuranceInput,OtherInsuranceRow,otherInsuranceApi} from "@/lib/other-insurance";
import {Customer,customerApi} from "@/lib/customers";
import {authenticatedRequest} from "@/lib/api-client";

type Company={id:string;company_name:string;default_commission_percent:number|string;status:string};
type PurchaseSource={id:string;name:string;source_type:string;linked_company_id?:string|null;is_active:boolean};

const config:Record<InsuranceLine,{title:string;subtitle:string;products:string[]}>= {
 non_motor:{title:"Non-Motor Insurance",subtitle:"Property, fire, marine, liability and business covers.",products:["Fire Insurance","Bharat Griha Raksha / Home Insurance","Shopkeeper Insurance","Burglary Insurance","Marine Cargo","Machinery Breakdown","Contractor All Risk (CAR)","Erection All Risk (EAR)","Liability Insurance","Workmen Compensation","Group Personal Accident","Personal Accident","Travel Insurance","Other Non-Motor"]},
 health:{title:"Health Insurance",subtitle:"Retail, family and group health policies.",products:["Individual Health","Family Floater","Senior Citizen Health","Group Health","Super Top-up","Top-up","Critical Illness","Personal Accident","Maternity Cover","Other Health"]},
 life:{title:"Life Insurance",subtitle:"Protection, savings and pension policies.",products:["Term Insurance","Endowment","Money Back","Whole Life","ULIP","Child Plan","Pension / Annuity","Savings Plan","Group Life","Other Life"]},
};
const money=(v:unknown)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v||0));
const customerName=(c:Customer)=>[c.first_name,c.middle_name,c.last_name].filter(Boolean).join(" ");

export default function OtherInsurancePage(){
 const raw=useParams<{line:string}>().line; const line=(raw==="health"||raw==="life"?raw:"non_motor") as InsuranceLine; const c=config[line];
 const [rows,setRows]=useState<OtherInsuranceRow[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [companies,setCompanies]=useState<Company[]>([]);const [sources,setSources]=useState<PurchaseSource[]>([]);
 const [summary,setSummary]=useState({policy_count:0,retail_count:0,wholesale_count:0,premium:0,received:0,due:0,company_payable:0,gross_commission:0,agent_commission:0,net_commission:0});
 const [search,setSearch]=useState("");const [channel,setChannel]=useState("all");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [open,setOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams();if(search)q.set("search",search);if(channel!=="all")q.set("channel",channel);const [p,crm,cos,src]=await Promise.all([otherInsuranceApi.list(line,q.toString()),customerApi.list("?per_page=500"),authenticatedRequest<Company[]>("/insurance-accounting/companies"),authenticatedRequest<PurchaseSource[]>("/insurance-accounting/purchase-sources")]);setRows(p.rows);setSummary(p.summary);setCustomers(crm.data.filter(x=>x.status!=="inactive"));setCompanies(cos.filter(x=>x.status!=="inactive"));setSources(src.filter(x=>x.is_active!==false))}catch(e){setError(e instanceof Error?e.message:"Insurance records could not load.")}finally{setLoading(false)}},[line,search,channel]);
 useEffect(()=>{void load()},[load]);
 const statusCount=useMemo(()=>rows.filter(r=>r.status==="active").length,[rows]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");setSuccess("");const f=new FormData(e.currentTarget);const customer=customers.find(x=>x.id===String(f.get("customer_id")||""));const company=companies.find(x=>x.id===String(f.get("insurance_company_id")||""));if(!customer){setSaving(false);setError("Select customer from CRM.");return;}if(!company){setSaving(false);setError("Select insurance company from master.");return;}const purchaseType=String(f.get("purchase_from_type")||"direct_company") as "direct_company"|"agent";const commissionRaw=String(f.get("commission_amount")||"").trim();const commissionPercentRaw=String(f.get("commission_percent")||"").trim();const input:OtherInsuranceInput={business_channel:String(f.get("business_channel")||"retail") as "retail"|"wholesale",customer_id:customer.id,product_type:String(f.get("product_type")||""),customer_name:customerName(customer),mobile:customer.mobile,insurance_company_id:company.id,company_name:company.company_name,purchase_from_type:purchaseType,purchase_source_id:purchaseType==="agent"?String(f.get("purchase_source_id")||"")||null:null,policy_number:String(f.get("policy_number")||""),proposal_number:String(f.get("proposal_number")||""),issue_date:String(f.get("issue_date")||""),expiry_date:String(f.get("expiry_date")||""),sum_insured:Number(f.get("sum_insured")||0),gross_premium:Number(f.get("gross_premium")||0),customer_pay:Number(f.get("customer_pay")||f.get("gross_premium")||0),company_payable:Number(f.get("company_payable")||f.get("customer_pay")||f.get("gross_premium")||0),...(commissionPercentRaw?{commission_percent:Number(commissionPercentRaw)}:{}),...(commissionRaw?{commission_amount:Number(commissionRaw)}:{}),agent_commission:Number(f.get("agent_commission")||0),received_amount:Number(f.get("received_amount")||0),status:"active",notes:String(f.get("notes")||"")};try{await otherInsuranceApi.create(line,input);setOpen(false);setSuccess("Policy saved. Customer due, company payable and commission are synced automatically.");await load()}catch(err){setError(err instanceof Error?err.message:"Policy could not save.")}finally{setSaving(false)}}
 async function remove(row:OtherInsuranceRow){if(!confirm(`Delete ${row.policy_number||"this policy"}?`))return;try{await otherInsuranceApi.remove(line,row.id);await load()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}}
 return <main className="min-h-screen bg-[#f4f7fb] p-4 md:p-6 dark:bg-[#050914]"><div className="mx-auto max-w-[1550px] space-y-5">
 <section className="rounded-[30px] bg-gradient-to-br from-[#07162f] via-[#103579] to-[#2872ef] p-6 text-white shadow-xl md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-200">Insurance Workspace</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">{c.title}</h1><p className="mt-2 max-w-3xl text-sm font-semibold text-blue-100/80">{c.subtitle} Retail aur wholesale dono me same guided flow: customer → company/source → premium → collection → commission → renewal → claim.</p></div><div className="flex gap-2"><Link href="/claims" className="rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-black">Claims</Link><button onClick={()=>setOpen(true)} className="rounded-xl bg-white px-5 py-3 text-sm font-black text-blue-800">+ Add Policy</button></div></div></section>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Kpi label="Policies" value={String(summary.policy_count)}/><Kpi label="Retail" value={String(summary.retail_count)}/><Kpi label="Wholesale" value={String(summary.wholesale_count)}/><Kpi label="Premium" value={money(summary.premium)}/><Kpi label="Customer Due" value={money(summary.due)}/><Kpi label="Net Commission" value={money(summary.net_commission)}/></section>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-semibold text-emerald-700">{success}</div>}
 <section className="rounded-[24px] border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap gap-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, policy, company or product" className="min-w-[280px] flex-1 rounded-xl border px-4 py-3 dark:border-slate-700 dark:bg-slate-800"/><select value={channel} onChange={e=>setChannel(e.target.value)} className="rounded-xl border bg-white px-4 py-3 font-bold dark:border-slate-700 dark:bg-slate-800"><option value="all">All channels</option><option value="retail">Retail</option><option value="wholesale">Wholesale</option></select><button onClick={()=>void load()} className="rounded-xl bg-blue-700 px-5 py-3 font-black text-white">Search</button></div></section>
 <section className="overflow-x-auto rounded-[24px] border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><table className="w-full min-w-[1450px] text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{["Channel","Customer","Product","Company / Source","Policy No","Dates","Premium","Customer Due","Company Payable","Commission","Status","Action"].map(h=><th key={h} className="p-4 text-xs font-black uppercase tracking-wider text-slate-500">{h}</th>)}</tr></thead><tbody>{loading&&<tr><td colSpan={12} className="p-10 text-center text-slate-400">Loading...</td></tr>}{!loading&&!rows.length&&<tr><td colSpan={12} className="p-10 text-center text-slate-400">No policies added.</td></tr>}{rows.map(r=><tr key={r.id} className="border-t dark:border-slate-800"><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${r.business_channel==="wholesale"?"bg-violet-50 text-violet-700":"bg-blue-50 text-blue-700"}`}>{r.business_channel}</span></td><td className="p-4"><b>{r.customer_name}</b><div className="text-xs text-slate-400">{r.mobile||"—"}</div></td><td className="p-4 font-semibold">{r.product_type||"—"}</td><td className="p-4"><b>{r.company_name||"—"}</b><div className="text-xs text-slate-400">{r.purchase_from_type==="agent"?"Via purchase source":"Direct company"}</div></td><td className="p-4 font-bold">{r.policy_number||"—"}</td><td className="p-4">{r.issue_date||"—"}<div className="text-xs text-slate-400">to {r.expiry_date||"—"}</div></td><td className="p-4">{money(r.gross_premium)}</td><td className="p-4 font-bold text-amber-700">{money(r.customer_due)}</td><td className="p-4 font-bold text-blue-700">{money(r.company_payable)}</td><td className="p-4"><b className="text-emerald-700">{money(r.net_commission)}</b><div className="text-xs text-slate-400">Gross {money(r.commission_amount)}</div></td><td className="p-4">{r.payment_status}</td><td className="p-4"><button onClick={()=>void remove(r)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Delete</button></td></tr>)}</tbody></table></section><p className="text-xs text-slate-400">Active policies: {statusCount}</p></div>{open&&<PolicyModal line={line} products={c.products} customers={customers} companies={companies} sources={sources} saving={saving} close={()=>setOpen(false)} submit={submit}/>}</main>}

function Kpi({label,value}:{label:string;value:string}){return <article className="rounded-2xl border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-xl font-black text-slate-950 dark:text-white">{value}</p></article>}
function PolicyModal({line,products,customers,companies,sources,saving,close,submit}:{line:InsuranceLine;products:string[];customers:Customer[];companies:Company[];sources:PurchaseSource[];saving:boolean;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){const life=line==="life";const [purchaseType,setPurchaseType]=useState("direct_company");const [companyId,setCompanyId]=useState("");const selectedCompany=companies.find(x=>x.id===companyId);return <div className="fixed inset-0 z-[120] overflow-y-auto bg-slate-950/65 p-4"><form onSubmit={submit} className="mx-auto my-5 max-w-6xl rounded-[28px] bg-white p-6 shadow-2xl dark:bg-[#101722]"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Guided policy entry</p><h2 className="mt-1 text-2xl font-black">Add {config[line].title} Policy</h2><p className="mt-1 text-xs text-slate-500">Fill from top to bottom. Finance and commission will sync automatically.</p></div><button type="button" onClick={close} className="rounded-xl border px-4 py-2 dark:border-white/10">Close</button></div>
 <Step n="1" title="Business channel"><div className="grid gap-3 sm:grid-cols-2"><Radio name="business_channel" value="retail" title="Retail" desc="Direct customer / normal office business" defaultChecked/><Radio name="business_channel" value="wholesale" title="Wholesale" desc="Agent, broker, dealer or bulk sourced business"/></div></Step>
 <Step n="2" title="Customer & product"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold md:col-span-2">Customer from CRM<select name="customer_id" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3 dark:bg-[#111827]"><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{customerName(c)} · {c.mobile}</option>)}</select></label><div className="flex items-end"><Link href="/customers/new" target="_blank" className="w-full rounded-xl border border-blue-200 px-4 py-3 text-center text-sm font-black text-blue-700">+ New Customer</Link></div><label className="text-sm font-bold">Product Type<select name="product_type" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3 dark:bg-[#111827]"><option value="">Select product</option>{products.map(p=><option key={p}>{p}</option>)}</select></label><Field label="Policy Number" name="policy_number"/><Field label="Proposal Number" name="proposal_number"/></div></Step>
 <Step n="3" title="Insurance company & purchase source"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Insurance Company<select name="insurance_company_id" value={companyId} onChange={e=>setCompanyId(e.target.value)} required className="mt-2 w-full rounded-xl border bg-white px-4 py-3 dark:bg-[#111827]"><option value="">Select company</option>{companies.map(x=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select></label><label className="text-sm font-bold">Policy purchased from<select name="purchase_from_type" value={purchaseType} onChange={e=>setPurchaseType(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3 dark:bg-[#111827]"><option value="direct_company">Direct insurance company</option><option value="agent">Agent / broker / other source</option></select></label>{purchaseType==="agent"?<label className="text-sm font-bold">Purchase Source<select name="purchase_source_id" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3 dark:bg-[#111827]"><option value="">Select source</option>{sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>:<div className="rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">Commission receivable: selected company</div>}</div></Step>
 <Step n="4" title="Policy dates & cover"><div className="grid gap-4 md:grid-cols-4"><Field label="Issue Date" name="issue_date" type="date"/><Field label={life?"Maturity / Renewal Date":"Expiry Date"} name="expiry_date" type="date"/><Field label={life?"Sum Assured":"Sum Insured"} name="sum_insured" type="number"/><Field label="Gross Premium" name="gross_premium" type="number" required/></div></Step>
 <Step n="5" title="Money flow & commission"><div className="grid gap-4 md:grid-cols-4"><Field label="Customer Payable" name="customer_pay" type="number"/><Field label="Customer Amount Received" name="received_amount" type="number"/><Field label="Company Payable" name="company_payable" type="number"/><Field key={companyId||"commission-rate"} label="Commission %" name="commission_percent" type="number" defaultValue={selectedCompany?String(selectedCompany.default_commission_percent||0):""}/><Field label="Gross Commission (optional manual)" name="commission_amount" type="number"/><Field label="Agent Commission / Payout" name="agent_commission" type="number"/><label className="text-sm font-bold md:col-span-2">Notes<textarea name="notes" className="mt-2 min-h-20 w-full rounded-xl border px-4 py-3 dark:border-white/10 dark:bg-[#111827]"/></label></div><p className="mt-3 text-xs text-slate-500">Customer payable blank ho to gross premium use hoga. Commission amount blank ho to insurer default / Commission % se calculate hoga. GST mapping existing logic se separate rahegi abhi.</p></Step>
 <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-5 py-3 dark:border-white/10">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-700 px-6 py-3 font-black text-white disabled:opacity-50">{saving?"Saving...":"Save & Sync Policy"}</button></div></form></div>}
function Step({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="mt-5 rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="mb-4 flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#12386d] text-xs font-black text-white">{n}</span><h3 className="font-black">{title}</h3></div>{children}</section>}
function Radio({name,value,title,desc,defaultChecked=false}:{name:string;value:string;title:string;desc:string;defaultChecked?:boolean}){return <label className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-4 has-[:checked]:border-blue-500 has-[:checked]:bg-blue-50 dark:border-white/10 dark:has-[:checked]:bg-blue-500/10"><input type="radio" name={name} value={value} defaultChecked={defaultChecked}/><span><b className="block">{title}</b><small className="mt-1 block text-slate-500">{desc}</small></span></label>}
function Field({label,name,type="text",required=false,defaultValue}:{label:string;name:string;type?:string;required?:boolean;defaultValue?:string}){return <label className="text-sm font-bold">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} min={type==="number"?0:undefined} step={type==="number"?"0.01":undefined} className="mt-2 w-full rounded-xl border px-4 py-3 dark:border-white/10 dark:bg-[#111827]"/></label>}
