"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {InsuranceLine,OtherInsuranceInput,OtherInsuranceRow,otherInsuranceApi} from "@/lib/other-insurance";
import {Customer,customerApi} from "@/lib/customers";

const config:Record<InsuranceLine,{title:string;subtitle:string;products:string[]}>= {
 non_motor:{title:"Non-Motor Insurance",subtitle:"Property, fire, home and business insurance.",products:["Fire Insurance","Bharat Griha Raksha / Home Insurance","Shopkeeper Insurance","Burglary Insurance","Marine Cargo","Machinery Breakdown","Contractor All Risk (CAR)","Erection All Risk (EAR)","Liability Insurance","Workmen Compensation","Group Personal Accident","Personal Accident","Travel Insurance","Other Non-Motor"]},
 health:{title:"Health Insurance",subtitle:"Retail and group health insurance management.",products:["Individual Health","Family Floater","Senior Citizen Health","Group Health","Super Top-up","Top-up","Critical Illness","Personal Accident","Maternity Cover","Other Health"]},
 life:{title:"Life Insurance",subtitle:"Life protection, savings and pension policies.",products:["Term Insurance","Endowment","Money Back","Whole Life","ULIP","Child Plan","Pension / Annuity","Savings Plan","Group Life","Other Life"]},
};
const money=(v:unknown)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v||0));
const customerName=(c:Customer)=>[c.first_name,c.middle_name,c.last_name].filter(Boolean).join(" ");

export default function OtherInsurancePage(){
 const raw=useParams<{line:string}>().line; const line=(raw==="health"||raw==="life"?raw:"non_motor") as InsuranceLine; const c=config[line];
 const [rows,setRows]=useState<OtherInsuranceRow[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [summary,setSummary]=useState({policy_count:0,premium:0,received:0,due:0,gross_commission:0,agent_commission:0,net_commission:0});const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [open,setOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams();if(search)q.set("search",search);const [p,crm]=await Promise.all([otherInsuranceApi.list(line,q.toString()),customerApi.list("?per_page=500")]);setRows(p.rows);setSummary(p.summary);setCustomers(crm.data.filter(x=>x.status!=="inactive"))}catch(e){setError(e instanceof Error?e.message:"Insurance records could not load.")}finally{setLoading(false)}},[line,search]);
 useEffect(()=>{void load()},[load]);
 const statusCount=useMemo(()=>rows.filter(r=>r.status==="active").length,[rows]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");setSuccess("");const f=new FormData(e.currentTarget);const customer=customers.find(x=>x.id===String(f.get("customer_id")||""));if(!customer){setSaving(false);setError("Select customer from CRM.");return;}const input:OtherInsuranceInput={customer_id:customer.id,product_type:String(f.get("product_type")||""),customer_name:customerName(customer),mobile:customer.mobile,company_name:String(f.get("company_name")||""),policy_number:String(f.get("policy_number")||""),proposal_number:String(f.get("proposal_number")||""),issue_date:String(f.get("issue_date")||""),expiry_date:String(f.get("expiry_date")||""),sum_insured:Number(f.get("sum_insured")||0),gross_premium:Number(f.get("gross_premium")||0),commission_amount:Number(f.get("commission_amount")||0),agent_commission:Number(f.get("agent_commission")||0),received_amount:Number(f.get("received_amount")||0),status:"active",notes:String(f.get("notes")||"")};try{await otherInsuranceApi.create(line,input);setOpen(false);setSuccess("Insurance policy saved and linked with CRM customer.");await load()}catch(err){setError(err instanceof Error?err.message:"Policy could not save.")}finally{setSaving(false)}}
 async function remove(row:OtherInsuranceRow){if(!confirm(`Delete ${row.policy_number||"this policy"}?`))return;try{await otherInsuranceApi.remove(line,row.id);await load()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}}
 return <main className="min-h-screen bg-[#f4f7fb] p-4 md:p-6 dark:bg-[#050914]"><div className="mx-auto max-w-[1550px] space-y-5"><section className="rounded-[30px] bg-gradient-to-br from-[#07162f] via-[#103579] to-[#2872ef] p-6 text-white shadow-xl md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-200">Insurance Workspace</p><h1 className="mt-2 text-4xl font-black">{c.title}</h1><p className="mt-2 text-sm font-semibold text-blue-100/80">CRM-linked customer selection. Commission is earning; premium remains customer/insurer money flow.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl bg-white px-5 py-3 text-sm font-black text-blue-800">+ Add Policy</button></div></section>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Policies" value={String(summary.policy_count)}/><Kpi label="Premium" value={money(summary.premium)}/><Kpi label="Customer Due" value={money(summary.due)}/><Kpi label="Net Commission" value={money(summary.net_commission)}/></section>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-semibold text-emerald-700">{success}</div>}
 <section className="rounded-[24px] border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap gap-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, policy, company or product" className="min-w-[280px] flex-1 rounded-xl border px-4 py-3 dark:border-slate-700 dark:bg-slate-800"/><button onClick={()=>void load()} className="rounded-xl bg-blue-700 px-5 py-3 font-black text-white">Search</button></div></section>
 <section className="overflow-x-auto rounded-[24px] border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{["Customer","Product","Company","Policy No","Dates","Sum Insured","Premium","Received","Due","Net Commission","Status","Action"].map(h=><th key={h} className="p-4 text-xs font-black uppercase tracking-wider text-slate-500">{h}</th>)}</tr></thead><tbody>{loading&&<tr><td colSpan={12} className="p-10 text-center text-slate-400">Loading...</td></tr>}{!loading&&!rows.length&&<tr><td colSpan={12} className="p-10 text-center text-slate-400">No policies added.</td></tr>}{rows.map(r=><tr key={r.id} className="border-t dark:border-slate-800"><td className="p-4"><b>{r.customer_name}</b><div className="text-xs text-slate-400">{r.mobile||"—"}</div></td><td className="p-4 font-semibold">{r.product_type||"—"}</td><td className="p-4">{r.company_name||"—"}</td><td className="p-4 font-bold">{r.policy_number||"—"}</td><td className="p-4">{r.issue_date||"—"}<div className="text-xs text-slate-400">to {r.expiry_date||"—"}</div></td><td className="p-4">{money(r.sum_insured)}</td><td className="p-4">{money(r.gross_premium)}</td><td className="p-4">{money(r.received_amount)}</td><td className="p-4 font-bold text-amber-700">{money(r.due_amount)}</td><td className="p-4 font-bold text-emerald-700">{money(r.net_commission)}</td><td className="p-4">{r.status}</td><td className="p-4"><button onClick={()=>void remove(r)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Delete</button></td></tr>)}</tbody></table></section><p className="text-xs text-slate-400">Active policies: {statusCount}</p></div>{open&&<PolicyModal line={line} products={c.products} customers={customers} saving={saving} close={()=>setOpen(false)} submit={submit}/>}</main>}

function Kpi({label,value}:{label:string;value:string}){return <article className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-slate-950 dark:text-white">{value}</p></article>}
function PolicyModal({line,products,customers,saving,close,submit}:{line:InsuranceLine;products:string[];customers:Customer[];saving:boolean;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){const life=line==="life";return <div className="fixed inset-0 z-[120] overflow-y-auto bg-slate-950/65 p-4"><form onSubmit={submit} className="mx-auto my-5 max-w-5xl rounded-[28px] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">New Insurance</p><h2 className="mt-1 text-2xl font-black">Add {config[line].title} Policy</h2></div><button type="button" onClick={close} className="rounded-xl border px-4 py-2">Close</button></div><div className="mt-6 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold md:col-span-2">Customer from CRM<select name="customer_id" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{customerName(c)} · {c.mobile}</option>)}</select></label><div className="flex items-end"><Link href="/customers/new" target="_blank" className="w-full rounded-xl border border-blue-200 px-4 py-3 text-center text-sm font-black text-blue-700">+ New Customer</Link></div><label className="text-sm font-bold">Product Type<select name="product_type" required className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Select product</option>{products.map(p=><option key={p}>{p}</option>)}</select></label><Field label="Insurance Company" name="company_name" required/><Field label="Policy Number" name="policy_number"/><Field label="Proposal Number" name="proposal_number"/><Field label="Issue Date" name="issue_date" type="date"/><Field label={life?"Maturity / Renewal Date":"Expiry Date"} name="expiry_date" type="date"/><Field label={life?"Sum Assured":"Sum Insured"} name="sum_insured" type="number"/><Field label="Gross Premium" name="gross_premium" type="number" required/><Field label="Gross Commission" name="commission_amount" type="number"/><Field label="Agent Commission" name="agent_commission" type="number"/><Field label="Customer Amount Received" name="received_amount" type="number"/><label className="text-sm font-bold md:col-span-2">Notes<textarea name="notes" className="mt-2 min-h-24 w-full rounded-xl border px-4 py-3"/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-5 py-3">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-700 px-6 py-3 font-black text-white disabled:opacity-50">{saving?"Saving...":"Save Policy"}</button></div></form></div>}
function Field({label,name,type="text",required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label className="text-sm font-bold">{label}<input name={name} type={type} required={required} min={type==="number"?0:undefined} step={type==="number"?"0.01":undefined} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>}
