"use client";
import { FormEvent, useEffect, useState } from "react";
import { Organization, organizationApi } from "@/lib/organization";

const fields: Array<[keyof Organization,string]> = [["name","Legal organization name"],["brand_name","Brand name"],["tagline","Tagline"],["address","Address"],["city","City"],["state","State"],["pin_code","PIN code"],["phone","Phone"],["email","Email"],["gst_number","GST number"]];
export default function OrganizationSettings(){
 const [organization,setOrganization]=useState<Organization>(); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{organizationApi.get().then(setOrganization).catch(e=>setError(e instanceof Error?e.message:"Unable to load organization.")).finally(()=>setLoading(false));},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");setMessage("");try{const updated=await organizationApi.update(new FormData(event.currentTarget));setOrganization(updated);setMessage("Organization settings saved.");}catch(e){setError(e instanceof Error?e.message:"Unable to save organization.");}finally{setSaving(false);}}
 if(loading)return <Card><p>Loading organization settings…</p></Card>;
 return <Card><div className="flex items-center gap-4">{organization?.logo_url?<img src={organization.logo_url} alt="Organization logo" className="h-16 w-16 rounded-2xl object-cover"/>:<div className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-600 text-2xl font-black text-white">{(organization?.brand_name??"V").slice(0,1)}</div>}<div><h2 className="text-xl font-black">Organization identity</h2><p className="text-sm text-slate-500">Used across the application and generated documents.</p></div></div>{error&&<Notice error text={error}/>} {message&&<Notice text={message}/>}<form onSubmit={submit} className="mt-6 grid gap-5 md:grid-cols-2">{fields.map(([name,label])=><label key={name} className={name==="address"?"md:col-span-2":""}><span className="mb-2 block text-sm font-bold">{label}</span><input name={name} required={name==="name"||name==="brand_name"} defaultValue={String(organization?.[name]??"")} className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500"/></label>)}<label className="md:col-span-2"><span className="mb-2 block text-sm font-bold">Logo (PNG, JPG or WebP, max 2 MB)</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" className="w-full rounded-xl border p-3"/></label><div className="md:col-span-2"><button disabled={saving} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-60">{saving?"Saving…":"Save organization"}</button></div></form></Card>;
}
function Card({children}:{children:React.ReactNode}){return <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-8">{children}</section>};
function Notice({text,error=false}:{text:string;error?:boolean}){return <div role={error?"alert":"status"} className={`mt-5 rounded-xl p-3 text-sm ${error?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{text}</div>}
