'use client';

import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {authenticatedRequest} from '@/lib/api-client';

type Commission={id:string;insurance_company_id:string;company_name:string;statement_number?:string|null;statement_date:string;policy_number?:string|null;customer_name?:string|null;gross_premium:number;commission_percent:number;gross_commission:number;tds_percent:number;tds_amount:number;net_receivable:number;received_amount:number;received_date?:string|null;bank_reference?:string|null;status:string;remarks?:string|null};
type Summary={gross_commission:number;tds_receivable:number;net_receivable:number;received:number;outstanding:number};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));

export default function InsuranceCommissionsPage(){
 const[rows,setRows]=useState<Commission[]>([]),[summary,setSummary]=useState<Summary>({gross_commission:0,tds_receivable:0,net_receivable:0,received:0,outstanding:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('pending'),[selected,setSelected]=useState<Commission|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[r,s]=await Promise.all([authenticatedRequest<Commission[]>('/insurance-accounting/commissions'),authenticatedRequest<Summary>('/insurance-accounting/summary')]);setRows(r);setSummary(s)}catch(e){setError(e instanceof Error?e.message:'Commission data could not load.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const shown=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>{const due=Math.max(0,Number(r.net_receivable)-Number(r.received_amount));if(status==='pending'&&due<=.009)return false;if(status==='received'&&due>.009)return false;if(status!=='all'&&status!=='pending'&&status!=='received'&&r.status!==status)return false;return !q||[r.company_name,r.policy_number,r.customer_name,r.statement_number].filter(Boolean).join(' ').toLowerCase().includes(q)})},[rows,search,status]);
 return <main className="min-h-screen bg-[#f4f7fb] p-4 text-[#0c203f] md:p-6 dark:bg-[#060a13] dark:text-white"><div className="mx-auto max-w-[1480px] space-y-5">
  <section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#11123a] via-[#34227a] to-[#6b3ee8] p-6 text-white shadow-xl md:p-8"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><Link href="/insurance" className="text-xs font-black text-violet-200">← Insurance Operations</Link><p className="mt-3 text-[9px] font-black uppercase tracking-[.22em] text-violet-200">Income control</p><h1 className="mt-1 text-4xl font-black tracking-[-.04em]">Commission Receivable</h1><p className="mt-2 max-w-3xl text-sm font-semibold text-violet-100/80">Policy save hote hi expected commission sync hoti hai. Yahan insurer / purchase source se actual receipt, TDS aur balance control karo.</p></div><div className="flex gap-2"><Link href="/insurance/company-payments" className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-black">Company Payments</Link><Link href="/reports/insurance-commission" className="rounded-2xl bg-white px-4 py-3 text-sm font-black text-violet-800">Detailed Report</Link></div></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Gross Commission" value={money(summary.gross_commission)}/><Kpi label="TDS" value={money(summary.tds_receivable)}/><Kpi label="Net Receivable" value={money(summary.net_receivable)}/><Kpi label="Received" value={money(summary.received)} good/><Kpi label="Outstanding" value={money(summary.outstanding)} warn={summary.outstanding>0}/></section>
  {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
  <section className="overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-white/[.04]"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center lg:justify-between dark:border-white/10"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-violet-600">Employee queue</p><h2 className="mt-1 text-xl font-black">Match every commission receipt</h2></div><div className="flex flex-col gap-2 sm:flex-row"><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm font-bold dark:border-white/10 dark:bg-[#111827]"><option value="pending">Pending / Partial</option><option value="received">Received</option><option value="all">All</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Company, policy, customer…" className="h-11 w-full rounded-xl border bg-slate-50 px-4 text-sm font-semibold outline-none sm:w-80 dark:border-white/10 dark:bg-white/[.05]"/></div></div>
   {loading?<div className="p-10 text-center text-sm text-slate-400">Loading commission receivables…</div>:shown.length?<div className="divide-y divide-slate-100 dark:divide-white/10">{shown.map(r=>{const due=Math.max(0,Number(r.net_receivable)-Number(r.received_amount));return <div key={r.id} className="grid gap-3 p-4 lg:grid-cols-[1.15fr_1fr_.75fr_.75fr_.75fr_auto] lg:items-center lg:p-5"><div><p className="text-sm font-black">{r.company_name}</p><p className="mt-1 text-[10px] text-slate-400">{r.policy_number||'Manual statement'} · {r.customer_name||'Customer'}</p></div><Cell label="Gross" value={money(r.gross_commission)}/><Cell label={`TDS ${Number(r.tds_percent||0)}%`} value={money(r.tds_amount)}/><Cell label="Net" value={money(r.net_receivable)}/><div><p className="text-[9px] font-black uppercase tracking-wider text-rose-500">Balance</p><p className={`mt-1 text-base font-black ${due>0?'text-rose-700 dark:text-rose-300':'text-emerald-700 dark:text-emerald-300'}`}>{money(due)}</p>{r.received_amount>0&&<p className="text-[9px] text-slate-400">Received {money(r.received_amount)}</p>}</div>{due>0?<button onClick={()=>setSelected(r)} className="h-11 rounded-xl bg-violet-700 px-5 text-sm font-black text-white">Receive</button>:<span className="rounded-xl bg-emerald-50 px-4 py-3 text-center text-xs font-black text-emerald-700">✓ Received</span>}</div>})}</div>:<div className="p-12 text-center"><p className="text-lg font-black">No commission in this queue</p><p className="mt-1 text-xs text-slate-400">Change filter or add/sync policies first.</p></div>}
  </section>
 </div>{selected&&<ReceiveModal row={selected} close={()=>setSelected(null)} saved={()=>{setSelected(null);void load()}}/>}</main>
}

function ReceiveModal({row,close,saved}:{row:Commission;close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false),[err,setErr]=useState('');const due=Math.max(0,Number(row.net_receivable)-Number(row.received_amount));async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const f=new FormData(e.currentTarget);try{await authenticatedRequest(`/insurance-accounting/commissions/${row.id}/receive`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({received_amount:Number(f.get('received_amount')||0),received_date:String(f.get('received_date')||''),bank_reference:String(f.get('bank_reference')||'')})});saved()}catch(x){setErr(x instanceof Error?x.message:'Commission receipt could not save.')}finally{setBusy(false)}}return <div className="fixed inset-0 z-[130] grid place-items-center bg-slate-950/60 p-3 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-lg rounded-[28px] bg-white p-6 shadow-2xl dark:bg-[#101722]"><div className="flex justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-violet-600">Receive Commission</p><h2 className="mt-1 text-2xl font-black">{row.company_name}</h2><p className="mt-1 text-xs text-slate-500">{row.policy_number||'Statement'} · Balance {money(due)}</p></div><button type="button" onClick={close} className="h-10 rounded-xl bg-slate-100 px-3 font-black dark:bg-white/10">×</button></div>{err&&<div className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{err}</div>}<div className="mt-5 grid gap-4"><label className="text-xs font-black">Amount received<input name="received_amount" type="number" min="0.01" max={due} step="0.01" defaultValue={due} required className="mt-2 h-12 w-full rounded-xl border px-3 dark:border-white/10 dark:bg-white/[.05]"/></label><label className="text-xs font-black">Received date<input name="received_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className="mt-2 h-12 w-full rounded-xl border px-3 dark:border-white/10 dark:bg-white/[.05]"/></label><label className="text-xs font-black">Bank reference / UTR<input name="bank_reference" className="mt-2 h-12 w-full rounded-xl border px-3 dark:border-white/10 dark:bg-white/[.05]"/></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border px-5 py-3 text-sm font-black dark:border-white/10">Cancel</button><button disabled={busy} className="rounded-xl bg-violet-700 px-6 py-3 text-sm font-black text-white disabled:opacity-50">{busy?'Saving…':'Save Receipt'}</button></div></form></div>}
function Kpi({label,value,good=false,warn=false}:{label:string;value:string;good?:boolean;warn?:boolean}){return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-white/[.04]"><p className={`text-[9px] font-black uppercase tracking-wider ${good?'text-emerald-600':warn?'text-rose-500':'text-slate-400'}`}>{label}</p><p className={`mt-2 text-xl font-black ${good?'text-emerald-700 dark:text-emerald-300':warn?'text-rose-700 dark:text-rose-300':'text-slate-950 dark:text-white'}`}>{value}</p></article>}
function Cell({label,value}:{label:string;value:string}){return <div><p className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
