"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {Customer,customerApi} from "@/lib/customers";
import {Vehicle,vehicleApi} from "@/lib/vehicles";

const CHANNEL_KEY="vimawallah_motor_business_channel";
const customerName=(c:Customer)=>[c.first_name,c.middle_name,c.last_name].filter(Boolean).join(" ");
const vehicleLabel=(v:Vehicle)=>`${v.vehicle_number} · ${[v.manufacturer,v.model].filter(Boolean).join(" ")||v.vehicle_class||"Vehicle"}`;

export default function MotorInsuranceEntry(){
 const [businessChannel,setBusinessChannel]=useState<"retail"|"wholesale">("retail");const [customers,setCustomers]=useState<Customer[]>([]);const [customerId,setCustomerId]=useState("");const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [vehicleType,setVehicleType]=useState("");const [vehicleId,setVehicleId]=useState("");const [loading,setLoading]=useState(true);const [vehicleLoading,setVehicleLoading]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const saved=sessionStorage.getItem(CHANNEL_KEY);if(saved==="wholesale")setBusinessChannel("wholesale");void customerApi.list("?per_page=500").then(r=>setCustomers(r.data.filter(c=>c.status!=="inactive"))).catch(e=>setError(e instanceof Error?e.message:"Customers could not load.")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{sessionStorage.setItem(CHANNEL_KEY,businessChannel)},[businessChannel]);
 useEffect(()=>{setVehicles([]);setVehicleType("");setVehicleId("");if(!customerId)return;setVehicleLoading(true);const q=new URLSearchParams({customer_id:customerId,per_page:"100"});void vehicleApi.list(`?${q}`).then(r=>setVehicles(r.data||[])).catch(e=>setError(e instanceof Error?e.message:"Customer vehicles could not load.")).finally(()=>setVehicleLoading(false))},[customerId]);
 const types=useMemo(()=>Array.from(new Set(vehicles.map(v=>v.vehicle_type||v.vehicle_class||"other").filter(Boolean))),[vehicles]);
 const filtered=useMemo(()=>vehicleType?vehicles.filter(v=>(v.vehicle_type||v.vehicle_class||"other")===vehicleType):vehicles,[vehicles,vehicleType]);
 const selectedCustomer=customers.find(c=>c.id===customerId);
 return <main className="min-h-screen bg-[#f4f7fb] p-4 md:p-6 dark:bg-[#050914]"><div className="mx-auto max-w-5xl space-y-5"><section className="rounded-[30px] bg-gradient-to-br from-[#07162f] via-[#0d3478] to-[#2872ef] p-7 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-200">Motor Insurance · Guided Entry</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Add Motor Policy</h1><p className="mt-2 max-w-3xl text-sm font-semibold text-blue-100/80">Channel → customer → vehicle → policy engine. Existing GST, premium, company/purchase-source, settlement and commission calculation stays intact.</p></section>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">{error}</div>}
 <section className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
 <div className="mb-6"><p className="text-[10px] font-black uppercase tracking-[.18em] text-blue-600">1. Business Channel</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setBusinessChannel("retail")} className={`rounded-2xl border p-4 text-left transition ${businessChannel==="retail"?"border-blue-500 bg-blue-50 ring-2 ring-blue-100 dark:bg-blue-500/10":"border-slate-200 dark:border-white/10"}`}><b className="block text-base">Retail</b><span className="mt-1 block text-xs text-slate-500">Direct customer / normal office policy.</span></button><button type="button" onClick={()=>setBusinessChannel("wholesale")} className={`rounded-2xl border p-4 text-left transition ${businessChannel==="wholesale"?"border-violet-500 bg-violet-50 ring-2 ring-violet-100 dark:bg-violet-500/10":"border-slate-200 dark:border-white/10"}`}><b className="block text-base">Wholesale</b><span className="mt-1 block text-xs text-slate-500">Agent, broker, dealer or bulk sourced business.</span></button></div></div>
 <div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-black text-slate-700 dark:text-slate-200">2. Customer from CRM<select disabled={loading} value={customerId} onChange={e=>setCustomerId(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-800"><option value="">{loading?"Loading customers...":"Select customer"}</option>{customers.map(c=><option key={c.id} value={c.id}>{customerName(c)} · {c.mobile}</option>)}</select></label><div className="flex items-end"><Link href="/customers/new" target="_blank" className="w-full rounded-xl border border-blue-200 px-4 py-3 text-center text-sm font-black text-blue-700">+ Create New Customer</Link></div>
 <label className="text-sm font-black text-slate-700 dark:text-slate-200">3. Vehicle Type<select disabled={!customerId||vehicleLoading||!vehicles.length} value={vehicleType} onChange={e=>{setVehicleType(e.target.value);setVehicleId("")}} className="mt-2 w-full rounded-xl border bg-white px-4 py-3 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-800"><option value="">{vehicleLoading?"Loading vehicles...":"Select vehicle type"}</option>{types.map(t=><option key={t} value={t}>{String(t).replaceAll("_"," ").toUpperCase()}</option>)}</select></label>
 <label className="text-sm font-black text-slate-700 dark:text-slate-200">4. Vehicle<select disabled={!vehicleType} value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-800"><option value="">Select vehicle</option>{filtered.map(v=><option key={v.id} value={v.id}>{vehicleLabel(v)}</option>)}</select></label></div>
 {customerId&&!vehicleLoading&&!vehicles.length&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>No vehicle linked with {selectedCustomer?customerName(selectedCustomer):"this customer"}.</b><p className="mt-1">Motor policy vehicle se linked rehna zaruri hai for RC, renewal, claim and accounting integrity.</p><Link href={`/vehicles/new?customer_id=${customerId}`} className="mt-3 inline-block rounded-xl bg-amber-700 px-4 py-2 font-black text-white">Add Vehicle for Customer</Link></div>}
 <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t pt-5 dark:border-slate-800"><div><p className="text-xs font-bold text-slate-700 dark:text-slate-200">Selected channel: <span className={businessChannel==="wholesale"?"text-violet-600":"text-blue-600"}>{businessChannel.toUpperCase()}</span></p><p className="mt-1 text-[10px] text-slate-500">Next form automatically stores this channel with the policy.</p></div>{vehicleId?<Link href={`/vehicles/${vehicleId}/insurance`} onClick={()=>sessionStorage.setItem(CHANNEL_KEY,businessChannel)} className="rounded-xl bg-blue-700 px-6 py-3 font-black text-white">Continue to Policy Form →</Link>:<button disabled className="rounded-xl bg-slate-200 px-6 py-3 font-black text-slate-500">Select Customer + Vehicle</button>}</div></section>
 </div></main>}
