'use client';

import { FormEvent, useEffect, useState } from 'react';
import { accountingApi } from '@/lib/accounting';
import { businessReportsApi, BusinessOverview } from '@/lib/business-reports';
import { Ledger, ledgerApi } from '@/lib/ledgers';
import { DASHBOARD_REFRESH_EVENT } from '@/lib/dashboard-refresh';

const money=(n:number|string|undefined)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function AccountsPage(){
  const [ledgers,setLedgers]=useState<Ledger[]>([]); const [pl,setPl]=useState<{income:number;expense:number;net_profit:number}|null>(null); const [bs,setBs]=useState<{assets:number;liabilities:number;difference:number}|null>(null); const [business,setBusiness]=useState<BusinessOverview|null>(null);
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [saving,setSaving]=useState(false);
  async function load(){try{const [l,p,b,r]=await Promise.all([ledgerApi.list(),accountingApi.profitLoss(),accountingApi.balanceSheet(),businessReportsApi.overview()]);setLedgers(l);setPl(p);setBs(b);setBusiness(r)}catch(e){setError(e instanceof Error?e.message:'Accounts load nahi hua.')}}
  useEffect(()=>{void load()},[]); useEffect(()=>{const refresh=()=>void load();addEventListener(DASHBOARD_REFRESH_EVENT,refresh);return()=>removeEventListener(DASHBOARD_REFRESH_EVENT,refresh)},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');setSuccess('');const f=new FormData(e.currentTarget);const form=e.currentTarget;const amount=Number(f.get('amount')||0);try{await accountingApi.createVoucher({voucher_type:String(f.get('voucher_type')),voucher_date:String(f.get('voucher_date')),reference_number:String(f.get('reference_number')||''),narration:String(f.get('narration')||''),entries:[{ledger_id:String(f.get('debit_ledger')),entry_type:'debit',amount},{ledger_id:String(f.get('credit_ledger')),entry_type:'credit',amount}]});form.reset();setSuccess('Voucher successfully post ho gaya.');await load()}catch(e){setError(e instanceof Error?e.message:'Voucher save nahi hua.')}finally{setSaving(false)}}
  const nav=[['Ledger Master','/accounts/ledgers','Customers, suppliers, bank, cash and account heads'],['Insurance Accounting','/accounts/insurance','Insurance companies and commission settlement'],['Report Master','/reports','All business and financial reports are kept separately here']];
  return <main className="min-h-screen bg-[#eef4fb] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1550px] space-y-6">
    <section className="rounded-[30px] bg-[linear-gradient(125deg,#06152f,#0b2f6b_55%,#1769e0)] p-7 text-white shadow-[0_28px_75px_rgba(7,26,60,.22)]"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-300">Financial Control Center</p><h1 className="mt-2 text-4xl font-black">Accounts</h1><p className="mt-2 text-sm text-blue-100/80">Daily accounting, ledgers and vouchers. Detailed reports are under Report Master.</p></div><div className="flex gap-2"><a href="/reports" className="rounded-2xl bg-white px-4 py-3 text-sm font-black text-[#0b2f6b]">Report Master</a><a href="/dashboard" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-black">Dashboard</a></div></div></section>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{success}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card title="Total Business Profit" value={money(business?.total_business_profit)} sub="Insurance + RTO"/><Card title="Insurance Profit" value={money(business?.insurance_profit)} sub={`${business?.policy_count||0} policies`}/><Card title="RTO Profit" value={money(business?.rto_profit)} sub={`${business?.rto_work_count||0} works`}/><Card title="Accounting P&L" value={money(pl?.net_profit)} sub={`Income ${money(pl?.income)}`}/><Card title="Balance Difference" value={money(bs?.difference)} sub={`Assets ${money(bs?.assets)}`}/></section>
    <section className="grid gap-4 md:grid-cols-3">{nav.map(([title,href,sub])=><a key={title} href={href} className="group rounded-[24px] border border-[#dce7f4] bg-white p-5 shadow-[0_12px_35px_rgba(20,53,102,.07)] transition hover:-translate-y-1 hover:shadow-xl"><p className="text-lg font-black text-[#0a2147]">{title} <span className="text-blue-500">→</span></p><p className="mt-2 text-xs font-semibold text-slate-400">{sub}</p></a>)}</section>
    <section className="rounded-[26px] border border-[#dce7f4] bg-white p-5 shadow-sm"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-blue-500">Accounting Voucher</p><h2 className="mt-1 text-xl font-black text-[#10213f]">Create Voucher</h2><p className="mt-1 text-sm text-slate-400">Receipt, payment, contra and journal entries post with equal debit/credit.</p></div><form onSubmit={submit} className="mt-4 grid gap-4 md:grid-cols-3">
      <Field label="Voucher Type"><select name="voucher_type" className="input"><option value="receipt">Receipt</option><option value="payment">Payment</option><option value="contra">Contra</option><option value="journal">Journal</option><option value="sales">Sales</option><option value="purchase">Purchase</option></select></Field>
      <Field label="Date"><input name="voucher_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className="input"/></Field><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" required className="input"/></Field>
      <Field label="Debit Ledger"><select name="debit_ledger" required className="input"><option value="">Select</option>{ledgers.map(l=><option key={l.id} value={l.id}>{l.ledger_name}</option>)}</select></Field><Field label="Credit Ledger"><select name="credit_ledger" required className="input"><option value="">Select</option>{ledgers.map(l=><option key={l.id} value={l.id}>{l.ledger_name}</option>)}</select></Field><Field label="Reference"><input name="reference_number" className="input"/></Field>
      <label className="md:col-span-3 text-sm font-semibold">Narration<textarea name="narration" rows={3} className="input"/></label><div className="md:col-span-3"><button disabled={saving} className="rounded-2xl bg-gradient-to-r from-[#0b2f6b] to-[#2563eb] px-6 py-3 font-black text-white disabled:opacity-60">{saving?'Posting...':'Post Voucher'}</button></div>
    </form></section>
    <style jsx>{`.input{margin-top:.5rem;width:100%;border:1px solid #d9e4f1;border-radius:16px;padding:.85rem 1rem;background:#f8fbff;outline:none}.input:focus{border-color:#60a5fa;box-shadow:0 0 0 4px rgba(96,165,250,.14)}`}</style>
  </div></main>
}
function Card({title,value,sub}:{title:string;value:string;sub:string}){return <div className="rounded-[24px] border border-[#dce7f4] bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.15em] text-blue-500">{title}</p><p className="mt-2 text-2xl font-black text-[#0a2147]">{value}</p><p className="mt-1 text-xs font-semibold text-slate-400">{sub}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-bold text-slate-600">{label}{children}</label>}
