'use client';

import {useEffect,useState} from 'react';
import {authenticatedRequest} from '@/lib/api-client';
import {exportRowsCsv,printReport,tableHtml} from '@/lib/report-export';

type Type='driving_licence'|'passport';
type Row={id:string;work_type?:string;application_number?:string;work_date?:string;customer_name?:string;mobile?:string;amount:number;cost:number;received_amount:number;due_amount:number;profit:number;status?:string;notes?:string};
type Payload={rows:Row[];summary:{work_count:number;billing:number;cost:number;received:number;due:number;profit:number}};
type Customer={id:string;first_name?:string;middle_name?:string;last_name?:string;mobile?:string};
type CustomerResponse=Customer[]|{data:Customer[]};
const money=(n:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const defaults={work_type:'',application_number:'',work_date:new Date().toISOString().slice(0,10),customer_id:'',amount:'',cost:'',received_amount:'',status:'active',notes:''};

export default function ServiceWorkPage({type,title}:{type:Type;title:string}){
 const [data,setData]=useState<Payload>({rows:[],summary:{work_count:0,billing:0,cost:0,received:0,due:0,profit:0}});const [customers,setCustomers]=useState<Customer[]>([]);const [form,setForm]=useState(defaults);const [show,setShow]=useState(false);const [error,setError]=useState('');
 const load=()=>authenticatedRequest<Payload>(`/service-works/${type}`).then(setData).catch(e=>setError(e instanceof Error?e.message:'Data load nahi hua'));
 useEffect(()=>{load();authenticatedRequest<CustomerResponse>('/customers?per_page=200').then(r=>setCustomers(Array.isArray(r)?r:r.data)).catch(()=>undefined)},[]);
 const save=async()=>{setError('');try{await authenticatedRequest(`/service-works/${type}`,{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount||0),cost:Number(form.cost||0),received_amount:Number(form.received_amount||0),customer_id:form.customer_id||null})});setForm(defaults);setShow(false);load()}catch(e){setError(e instanceof Error?e.message:'Save failed')}};
 const del=async(id:string)=>{if(!confirm('Delete this work?'))return;await authenticatedRequest(`/service-works/${type}/${id}`,{method:'DELETE'});load()};
 const rows=data.rows as unknown as Array<Record<string,unknown>>;
 return <main className="min-h-screen bg-[#f3f7fc] p-4 md:p-6"><div className="mx-auto max-w-[1600px] space-y-5"><section className="rounded-[30px] bg-gradient-to-br from-[#07162f] via-[#103579] to-[#2872ef] p-7 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.22em] text-cyan-200">RTO Service</p><h1 className="mt-2 text-4xl font-black">{title}</h1><p className="mt-2 text-sm text-blue-100">Billing, direct cost, received, due and profit automatically count in RTO business.</p></div><button onClick={()=>setShow(!show)} className="rounded-2xl bg-white px-5 py-3 font-black text-blue-700">+ Add Work</button></div></section>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[['Work',data.summary.work_count],['Billing',money(data.summary.billing)],['Cost',money(data.summary.cost)],['Received',money(data.summary.received)],['Due',money(data.summary.due)],['Profit',money(data.summary.profit)]].map(([k,v])=><article key={String(k)} className="rounded-2xl border bg-white p-4"><p className="text-[10px] font-black uppercase text-slate-400">{k}</p><p className="mt-2 text-xl font-black text-[#0d2d61]">{v}</p></article>)}</section>
 {show&&<section className="rounded-[24px] border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} className="rounded-xl border p-3"><option value="">Select Customer</option>{customers.map(c=><option key={c.id} value={c.id}>{[c.first_name,c.middle_name,c.last_name].filter(Boolean).join(' ')} {c.mobile?`- ${c.mobile}`:''}</option>)}</select><input placeholder="Work Type" value={form.work_type} onChange={e=>setForm({...form,work_type:e.target.value})} className="rounded-xl border p-3"/><input placeholder="Application / Reference No" value={form.application_number} onChange={e=>setForm({...form,application_number:e.target.value})} className="rounded-xl border p-3"/><input type="date" value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})} className="rounded-xl border p-3"/><input type="number" placeholder="Customer Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="rounded-xl border p-3"/><input type="number" placeholder="Direct Cost / Govt Fee" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})} className="rounded-xl border p-3"/><input type="number" placeholder="Received Amount" value={form.received_amount} onChange={e=>setForm({...form,received_amount:e.target.value})} className="rounded-xl border p-3"/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border p-3"><option value="active">Active</option><option value="completed">Completed</option><option value="pending">Pending</option></select><input placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="rounded-xl border p-3"/></div><div className="mt-4 flex gap-3"><button onClick={save} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Save</button><button onClick={()=>setShow(false)} className="rounded-xl border px-6 py-3 font-bold">Cancel</button></div></section>}
 {error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}<div className="flex gap-3"><button onClick={()=>exportRowsCsv(`${type}-report`,rows)} className="rounded-xl border bg-white px-5 py-3 font-bold">Excel</button><button onClick={()=>printReport(title,`<h1>${title}</h1><div class="summary"><div class="card"><div class="label">Billing</div><div class="value">${money(data.summary.billing)}</div></div><div class="card"><div class="label">Cost</div><div class="value">${money(data.summary.cost)}</div></div><div class="card"><div class="label">Profit</div><div class="value">${money(data.summary.profit)}</div></div></div>${tableHtml(rows)}`)} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">PDF / Print</button></div>
 <section className="overflow-x-auto rounded-[24px] border bg-white p-4 shadow-sm"><table className="min-w-full text-sm"><thead><tr className="bg-blue-50 text-left text-xs uppercase text-blue-900"><th className="p-3">Date</th><th className="p-3">Customer</th><th className="p-3">Work</th><th className="p-3">Reference</th><th className="p-3">Billing</th><th className="p-3">Cost</th><th className="p-3">Received</th><th className="p-3">Due</th><th className="p-3">Profit</th><th className="p-3">Action</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.work_date}</td><td className="p-3 font-semibold">{r.customer_name}<div className="text-xs text-slate-400">{r.mobile}</div></td><td className="p-3">{r.work_type||'—'}</td><td className="p-3">{r.application_number||'—'}</td><td className="p-3">{money(r.amount)}</td><td className="p-3">{money(r.cost)}</td><td className="p-3">{money(r.received_amount)}</td><td className="p-3">{money(r.due_amount)}</td><td className="p-3 font-black text-emerald-700">{money(r.profit)}</td><td className="p-3"><button onClick={()=>del(r.id)} className="text-red-600">Delete</button></td></tr>)}</tbody></table></section></div></main>
}
