'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { OperationalRecord, vehicleOperationsApi } from '@/lib/vehicle-operations';
import { Ledger, ledgerApi } from '@/lib/ledgers';

const input = 'h-12 w-full rounded-xl border border-slate-200 bg-slate-50/80 px-3 text-sm font-semibold text-slate-900 outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50';
const label = 'grid gap-1.5 text-[11px] font-black uppercase tracking-[.04em] text-slate-500';
const money=(n:number)=>`₹${n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

type GovtPayer='owner'|'us'|'agent';
type Master={id:string;name:string};
type LinkedRecord=OperationalRecord&{notes?:string;account?:string};

function addMonths(date:string,months:number){if(!date||!months)return'';const d=new Date(`${date}T00:00:00`);const day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()!==day)d.setDate(0);return d.toISOString().slice(0,10)}
function notePart(notes:unknown,label:string){const text=String(notes??'');const match=text.match(new RegExp(`${label}:?\\s*([^|]+)`,'i'));return match?.[1]?.trim()||''}
function noteMoney(notes:unknown,label:string){const raw=notePart(notes,label).replace(/[^0-9.-]/g,'');return Number(raw||0)}
function formatDate(value:unknown){if(!value)return'—';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}

export default function FitnessPage(){
 const {vehicleId}=useParams<{vehicleId:string}>();
 const [rows,setRows]=useState<OperationalRecord[]>([]);
 const [centers,setCenters]=useState<Master[]>([]);
 const [selectedCenter,setSelectedCenter]=useState('');
 const [centerModalOpen,setCenterModalOpen]=useState(false);
 const [newCenterName,setNewCenterName]=useState('');
 const [addingCenter,setAddingCenter]=useState(false);
 const [ledgers,setLedgers]=useState<Ledger[]>([]);
 const [period,setPeriod]=useState(''); const [issueDate,setIssueDate]=useState(''); const [receiptNo,setReceiptNo]=useState(''); const [receiptDate,setReceiptDate]=useState('');
 const [totalAmount,setTotalAmount]=useState(''); const [govtFee,setGovtFee]=useState(''); const [govtPaidBy,setGovtPaidBy]=useState<GovtPayer>('owner'); const [bankLedgerId,setBankLedgerId]=useState('');
 const [outsourced,setOutsourced]=useState(false); const [agentLedgerId,setAgentLedgerId]=useState(''); const [agentCost,setAgentCost]=useState('');
 const [formOpen,setFormOpen]=useState(false); const [editingId,setEditingId]=useState(''); const [deletingId,setDeletingId]=useState('');
 const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
 const expiry=useMemo(()=>addMonths(issueDate,Number(period||0)),[issueDate,period]);
 const total=Number(totalAmount||0),govt=Number(govtFee||0),agent=Number(agentCost||0); const service=Math.max(0,total-govt);
 const splitInvalid=govt>total&&total>0;
 const customerReceivable=govtPaidBy==='owner'?service:total;
 const creditorLedgers=useMemo(()=>ledgers.filter(l=>l.status==='active'&&l.ledger_group==='Sundry Creditors').sort((a,b)=>a.ledger_name.localeCompare(b.ledger_name)),[ledgers]);
 const bankLedgers=useMemo(()=>ledgers.filter(l=>l.status==='active'&&['Bank Accounts','Cash-in-Hand'].includes(l.ledger_group)).sort((a,b)=>a.ledger_name.localeCompare(b.ledger_name)),[ledgers]);
 const selectedAgent=creditorLedgers.find(l=>l.id===agentLedgerId);
 const load=()=>vehicleOperationsApi.list(vehicleId,'fitness').then(setRows).catch(e=>setError(e instanceof Error?e.message:'Fitness history could not be loaded.'));
 const loadMasters=async()=>{setCenters((await vehicleOperationsApi.masters('fitness_center')).sort((a,b)=>a.name.localeCompare(b.name)));setLedgers(await ledgerApi.list())};
 useEffect(()=>{void load();void loadMasters().catch(()=>undefined)},[vehicleId]);

 function resetForm(){setPeriod('');setIssueDate('');setReceiptNo('');setReceiptDate('');setSelectedCenter('');setTotalAmount('');setGovtFee('');setGovtPaidBy('owner');setBankLedgerId('');setOutsourced(false);setAgentLedgerId('');setAgentCost('');setEditingId('')}
 function openNew(){resetForm();setError('');setSuccess('');setFormOpen(true);window.setTimeout(()=>document.getElementById('fitness-entry-form')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
 function closeForm(){if(saving)return;resetForm();setFormOpen(false);setError('')}

 async function editRow(row:OperationalRecord){
  setError('');setSuccess('');
  const notes=String(row.notes??'');
  const payer=(notePart(notes,'Govt paid by').toLowerCase()||'owner') as GovtPayer;
  const agentName=String(row.vendor??'');
  setEditingId(row.id);setPeriod(String(row.period??''));setIssueDate(String(row.issue_date??'').slice(0,10));setReceiptNo(String(row.reference_number??''));setReceiptDate(String(row.receipt_date??'').slice(0,10));
  setSelectedCenter(notePart(notes,'Fitness Center'));setTotalAmount(String(Number(row.amount??0)));setGovtFee(String(noteMoney(notes,'Govt Fee')));setGovtPaidBy(['owner','us','agent'].includes(payer)?payer:'owner');
  const cost=noteMoney(notes,'Agent cost');setAgentCost(String(cost));setOutsourced(/Agent cost/i.test(notes));
  const matchedAgent=creditorLedgers.find(l=>l.ledger_name===agentName);setAgentLedgerId(matchedAgent?.id||'');
  if(payer==='us'){
   const payments=await linkedRecords('payment',row.id);const govtPayment=payments.find(x=>String(x.notes??'').includes('Government fee'));
   setBankLedgerId(String(govtPayment?.account??''));
  } else setBankLedgerId('');
  setFormOpen(true);window.setTimeout(()=>document.getElementById('fitness-entry-form')?.scrollIntoView({behavior:'smooth',block:'start'}),50);
 }

 async function addCenter(e?:FormEvent<HTMLFormElement>){e?.preventDefault();const name=newCenterName.trim();if(!name)return;setAddingCenter(true);setError('');try{const duplicate=centers.find(c=>c.name.trim().toLowerCase()===name.toLowerCase());if(duplicate){setSelectedCenter(duplicate.name);setCenterModalOpen(false);setNewCenterName('');return}const added=await vehicleOperationsApi.addMaster('fitness_center',name);setCenters(c=>[...c.filter(x=>x.id!==added.id),added].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedCenter(added.name);setCenterModalOpen(false);setNewCenterName('')}catch(err){setError(err instanceof Error?err.message:'Fitness / Inspection center could not be added. Please try again.')}finally{setAddingCenter(false)}}
 async function addAgentLedger(){const name=prompt('Fitness agent / vendor name');if(!name?.trim())return;const added=await ledgerApi.create({ledger_name:name.trim(),ledger_group:'Sundry Creditors',opening_balance:0,balance_type:'credit',credit_limit:0,credit_days:30,gst_applicable:false,status:'active'});setLedgers(c=>[...c,added]);setAgentLedgerId(added.id)}
 async function ensureClearing(){if(govt<=0||govtPaidBy==='owner')return;const exists=ledgers.find(l=>l.ledger_name.toUpperCase()==='GOVERNMENT FEE CLEARING');if(!exists){const added=await ledgerApi.create({ledger_name:'GOVERNMENT FEE CLEARING',ledger_group:'Current Assets',opening_balance:0,balance_type:'debit',credit_limit:0,credit_days:0,gst_applicable:false,status:'active'});setLedgers(c=>[...c,added])}}
 async function linkedRecords(module:'payment'|'agent_payment',fitnessId:string){const all=await vehicleOperationsApi.list(vehicleId,module).catch(()=>[]);return(all as LinkedRecord[]).filter(record=>String(record.notes??'').includes(`record ${fitnessId}`))}
 async function removeLinked(fitnessId:string){const [payments,agentPayments]=await Promise.all([linkedRecords('payment',fitnessId),linkedRecords('agent_payment',fitnessId)]);for(const row of payments)await vehicleOperationsApi.remove(vehicleId,'payment',row.id);for(const row of agentPayments)await vehicleOperationsApi.remove(vehicleId,'agent_payment',row.id)}
 async function createLinked(fitnessId:string){
  if(customerReceivable>0)await vehicleOperationsApi.create(vehicleId,'payment',{payment_type:'Fitness Bill',account:'FITNESS SERVICE',issue_date:issueDate,billed_amount:customerReceivable,reference_number:`FIT-${fitnessId}`,notes:`Fitness customer bill | record ${fitnessId}`});
  if(outsourced&&agent>0)await vehicleOperationsApi.create(vehicleId,'agent_payment',{party_name:selectedAgent?.ledger_name,account:'FITNESS AGENT PAYABLE',issue_date:issueDate,billed_amount:agent,paid_amount:0,reference_number:`FIT-${fitnessId}`,notes:`Fitness outsourced cost accrued | record ${fitnessId}`});
  if(govt>0&&govtPaidBy==='agent')await vehicleOperationsApi.create(vehicleId,'agent_payment',{party_name:selectedAgent?.ledger_name,account:'GOVERNMENT FEE CLEARING',issue_date:issueDate,billed_amount:govt,paid_amount:0,reference_number:`FIT-GOVT-${fitnessId}`,notes:`Fitness government fee paid by agent | record ${fitnessId}`});
  if(govt>0&&govtPaidBy==='us')await vehicleOperationsApi.create(vehicleId,'payment',{payment_type:'Fitness Government Fee',account:bankLedgerId,issue_date:issueDate,billed_amount:0,paid_amount:govt,reference_number:`FIT-GOVT-${fitnessId}`,notes:`Government fee via GOVERNMENT FEE CLEARING | record ${fitnessId}`});
 }

 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();if(splitInvalid){setError('Government fee cannot be more than total amount.');return}if(!selectedCenter){setError('Select Fitness / Inspection Center.');return}if((outsourced||govtPaidBy==='agent')&&!agentLedgerId){setError('Select Fitness Agent ledger.');return}if(govtPaidBy==='us'&&!bankLedgerId){setError('Select Bank / Cash source for government fee.');return}
  setSaving(true);setError('');setSuccess('');let createdId='';
  try{
   await ensureClearing();
   const body={period,issue_date:issueDate,expiry_date:expiry,reference_number:receiptNo,receipt_date:receiptDate,party_amount:customerReceivable,amount:total,vendor:selectedAgent?.ledger_name||undefined,notes:`Fitness Center: ${selectedCenter} | Total ${money(total)} | Govt Fee ${money(govt)} | Service ${money(service)} | Govt paid by ${govtPaidBy}${outsourced?` | Agent cost ${money(agent)}`:''}`};
   const record=editingId?await vehicleOperationsApi.update(vehicleId,'fitness',editingId,body):await vehicleOperationsApi.create(vehicleId,'fitness',body);createdId=editingId?'':record.id;
   if(editingId)await removeLinked(record.id);await createLinked(record.id);
   await load();setSuccess(editingId?'Fitness record and linked accounting updated.':'Fitness added successfully.');resetForm();setFormOpen(false);
  }catch(err){if(createdId){try{await removeLinked(createdId);await vehicleOperationsApi.remove(vehicleId,'fitness',createdId)}catch{}}setError(err instanceof Error?err.message:'Fitness record could not be saved.')}finally{setSaving(false)}
 }

 async function deleteRow(row:OperationalRecord){if(!confirm('Delete this Fitness record? Linked Fitness billing / agent accounting entries created by this record will also be removed.'))return;setDeletingId(row.id);setError('');setSuccess('');try{await removeLinked(row.id);await vehicleOperationsApi.remove(vehicleId,'fitness',row.id);if(editingId===row.id){resetForm();setFormOpen(false)}await load();setSuccess('Fitness record deleted with its linked accounting entries.')}catch(err){setError(err instanceof Error?err.message:'Fitness record could not be deleted.')}finally{setDeletingId('')}}

 return <main className="min-h-screen bg-[#f4f7fc] p-3 text-[#081a3a] sm:p-5 md:p-7"><div className="mx-auto max-w-7xl space-y-4">
  <section className="relative overflow-hidden rounded-[28px] border border-[#173d78] bg-[#071a3c] p-6 text-white shadow-[0_24px_70px_rgba(7,26,60,.20)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_88%_12%,rgba(48,143,255,.48),transparent_35%),linear-gradient(135deg,#06152f,#0a2555_60%,#0c3478)]"/><div className="relative flex items-center justify-between"><div><a href={`/vehicles/${vehicleId}`} className="text-xs font-bold text-blue-200">← Vehicle Profile</a><p className="mt-5 text-[9px] font-black uppercase tracking-[.24em] text-[#63d4ff]">Commercial compliance</p><h1 className="mt-1 text-3xl font-black">Fitness</h1><p className="mt-2 text-xs text-blue-100/70">Existing Fitness first. Open the form only when you need to add or edit a record.</p></div><div className="grid h-20 w-20 place-items-center rounded-[24px] border border-white/10 bg-white/10 text-4xl">✓</div></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">✓ {success}</div>}

  {!formOpen&&<section className="flex flex-col gap-3 rounded-[22px] border border-blue-200 bg-[linear-gradient(135deg,#ffffff,#eff6ff)] p-4 shadow-[0_10px_30px_rgba(37,99,235,.07)] sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Fitness Action</p><h2 className="mt-1 text-base font-black">Need another Fitness entry?</h2><p className="mt-1 text-xs font-semibold text-slate-500">Existing records stay visible. Open the form only when required.</p></div><button type="button" onClick={openNew} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-[#0b2b62] px-5 text-sm font-black text-white shadow-[0_10px_24px_rgba(11,43,98,.20)]"><span className="text-xl leading-none">＋</span> Add Fitness</button></section>}

  {formOpen&&<form id="fitness-entry-form" onSubmit={submit} className="overflow-hidden rounded-[26px] border border-[#d9e5f7] bg-white shadow-[0_14px_40px_rgba(26,64,120,.08)]">
   <div className="flex items-center justify-between border-b border-slate-100 bg-gradient-to-r from-white to-blue-50/70 px-6 py-4"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-blue-500">{editingId?'Edit Fitness':'New Fitness'}</p><h2 className="mt-1 text-xl font-black">{editingId?'Update Fitness Entry':'Fitness Entry'}</h2></div><button type="button" onClick={closeForm} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-lg font-black text-slate-500 hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600">×</button></div>
   <div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6"><label className={label}>Period *<select required value={period} onChange={e=>setPeriod(e.target.value)} className={input}><option value="">Select Period</option><option value="12">12 Month</option><option value="24">2 Year</option><option value="60">5 Year</option><option value="180">15 Year</option></select></label><label className={label}>Issue Date *<input type="date" required value={issueDate} onChange={e=>setIssueDate(e.target.value)} className={input}/></label><label className={label}>Expire Date<input type="date" readOnly value={expiry} className={`${input} bg-blue-50/60`}/></label><label className={label}>Receipt No *<input required value={receiptNo} onChange={e=>setReceiptNo(e.target.value)} className={input}/></label><label className={label}>Receipt Date *<input type="date" required value={receiptDate} onChange={e=>setReceiptDate(e.target.value)} className={input}/></label><label className={label}>Fitness / Inspection Center *<div className="flex gap-2"><select required value={selectedCenter} onChange={e=>setSelectedCenter(e.target.value)} className={input}><option value="">Select center</option>{centers.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select><button type="button" onClick={()=>{setNewCenterName('');setCenterModalOpen(true)}} className="h-12 min-w-12 rounded-xl border border-blue-200 bg-blue-50 font-black text-blue-700">+</button></div></label></div>
   <section className="mx-5 mb-5 rounded-[22px] border border-slate-200 bg-[#fbfdff] p-5 sm:mx-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-600">Billing</p><h3 className="mt-1 text-lg font-black">Customer & Government Fee</h3></div><div className="rounded-xl bg-[#081f49] px-4 py-2.5 text-right text-white"><p className="text-[8px] font-black uppercase text-blue-200">Receivable</p><p className="text-xl font-black">{money(customerReceivable)}</p></div></div><div className="grid gap-4 lg:grid-cols-3"><label className={label}>Total Amount Charged *<input type="number" min="0" step="0.01" required value={totalAmount} onChange={e=>setTotalAmount(e.target.value)} className={input}/></label><label className={label}>Government Fee<input type="number" min="0" step="0.01" value={govtFee} onChange={e=>{setGovtFee(e.target.value);if(Number(e.target.value||0)<=0)setGovtPaidBy('owner')}} className={input}/></label><div className="rounded-xl border border-emerald-200 bg-emerald-50/50 px-4 py-3"><p className="text-[9px] font-black uppercase text-emerald-700">Service + Other</p><p className="mt-1 text-2xl font-black">{money(service)}</p><p className="text-[10px] font-semibold text-slate-500">Auto: Total − Govt Fee</p></div></div>{govt>0&&<div className="mt-4 border-t border-slate-200 pt-4"><div className="grid gap-4 lg:grid-cols-2"><label className={label}>Government Fee Paid By<select value={govtPaidBy} onChange={e=>setGovtPaidBy(e.target.value as GovtPayer)} className={input}><option value="owner">Customer / Owner</option><option value="us">Office / Us</option><option value="agent">Fitness Agent</option></select></label>{govtPaidBy==='us'?<label className={label}>Source of Funds *<select required value={bankLedgerId} onChange={e=>setBankLedgerId(e.target.value)} className={input}><option value="">Select Bank / Cash</option>{bankLedgers.map(l=><option key={l.id} value={l.id}>{l.ledger_name}</option>)}</select></label>:<div className="grid gap-1.5"><span className="text-[11px] font-black uppercase tracking-[.04em] text-slate-500">Source of Funds</span><div className="flex h-12 items-center rounded-xl border border-slate-200 bg-slate-100 px-3 text-sm font-bold text-slate-500">{govtPaidBy==='owner'?'Customer / Owner funds':'Fitness Agent funds'}</div></div>}</div></div>}</section>
   <section className="mx-5 mb-5 rounded-[22px] border border-amber-200 bg-amber-50/30 p-5 sm:mx-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-amber-700">Outsource</p><h3 className="mt-1 text-lg font-black">Fitness Agent</h3></div><button type="button" onClick={()=>setOutsourced(v=>!v)} className={`rounded-full px-4 py-2 text-xs font-black ${outsourced?'bg-amber-600 text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{outsourced?'YES':'NO'}</button></div>{(outsourced||govtPaidBy==='agent')&&<div className="grid gap-4 lg:grid-cols-2"><label className={label}>Agent Ledger *<div className="flex gap-2"><select required value={agentLedgerId} onChange={e=>setAgentLedgerId(e.target.value)} className={input}><option value="">Select agent</option>{creditorLedgers.map(l=><option key={l.id} value={l.id}>{l.ledger_name}</option>)}</select><button type="button" onClick={()=>void addAgentLedger()} className="h-12 min-w-12 rounded-xl border border-amber-200 bg-white font-black text-amber-700">+</button></div></label>{outsourced&&<label className={label}>Agent Cost *<input type="number" min="0" step="0.01" required value={agentCost} onChange={e=>setAgentCost(e.target.value)} className={input}/></label>}</div>}</section>
   <div className="flex flex-col gap-3 border-t border-slate-100 bg-[#f8fbff] p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="grid gap-1 text-[10px] font-semibold text-slate-500"><span>Fitness income: {money(service)}</span><span>Agent payable: {money(agent+(govtPaidBy==='agent'?govt:0))}</span></div><button disabled={saving||!expiry||splitInvalid} className="min-w-[210px] rounded-2xl bg-gradient-to-r from-[#0b2b62] to-[#2563eb] px-6 py-3.5 text-sm font-black text-white disabled:opacity-50">{saving?'Saving…':editingId?'✓ Update Fitness':'+ Add Fitness'}</button></div>
  </form>}

  <section className="overflow-hidden rounded-[26px] border border-[#d9e5f7] bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-blue-500">History</p><h2 className="mt-1 text-xl font-black">Fitness Records</h2></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-[10px] font-black text-blue-700">{rows.length} record{rows.length===1?'':'s'}</span></div><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="bg-[#f8fbff] text-[9px] font-black uppercase text-slate-400"><tr><th className="p-4 text-left">Period</th><th className="p-4 text-left">Issue</th><th className="p-4 text-left">Expiry</th><th className="p-4 text-left">Receipt</th><th className="p-4 text-left">Center / Details</th><th className="p-4 text-left">Customer Due</th><th className="p-4 text-left">Total</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100 transition hover:bg-blue-50/30"><td className="p-4 font-black">{String(r.period??'—')} Mo</td><td className="p-4">{formatDate(r.issue_date)}</td><td className="p-4">{formatDate(r.expiry_date)}</td><td className="p-4">{String(r.reference_number??'—')}</td><td className="p-4 max-w-[340px]"><p className="font-bold text-slate-800">{notePart(r.notes,'Fitness Center')||'—'}</p><p className="mt-1 truncate text-[11px] text-slate-400">{String(r.notes??'')}</p></td><td className="p-4 font-black text-blue-700">{money(Number(r.party_amount??0))}</td><td className="p-4 font-black">{money(Number(r.amount??0))}</td><td className="p-4"><div className="flex justify-end gap-2"><button type="button" onClick={()=>void editRow(r)} className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-black text-blue-700 hover:bg-blue-100">✎ Edit</button><button type="button" disabled={deletingId===r.id} onClick={()=>void deleteRow(r)} className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-700 hover:bg-rose-100 disabled:opacity-50">{deletingId===r.id?'Deleting…':'Delete'}</button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="grid place-items-center gap-3 p-10 text-center"><p className="text-sm font-semibold text-slate-400">No fitness records added yet.</p><button type="button" onClick={openNew} className="rounded-xl bg-[#0b2b62] px-4 py-2.5 text-xs font-black text-white">＋ Add first Fitness</button></div>}</div></section>
 </div>
 {centerModalOpen&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm" onMouseDown={()=>!addingCenter&&setCenterModalOpen(false)}><form onSubmit={addCenter} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-md overflow-hidden rounded-[24px] border border-white/70 bg-white shadow-[0_28px_90px_rgba(15,23,42,.28)]"><div className="border-b border-slate-100 px-6 py-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Fitness Master</p><h3 className="mt-1 text-xl font-black text-slate-950">Add Inspection Center</h3></div><div className="p-6"><label className={label}>Center Name *<input autoFocus value={newCenterName} onChange={e=>setNewCenterName(e.target.value)} placeholder="e.g. Palanpur Fitness Center" className={input}/></label></div><div className="flex justify-end gap-2 border-t border-slate-100 bg-slate-50/70 px-6 py-4"><button type="button" disabled={addingCenter} onClick={()=>setCenterModalOpen(false)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black text-slate-600">Cancel</button><button type="submit" disabled={addingCenter||!newCenterName.trim()} className="rounded-xl bg-[#0b2b62] px-5 py-2.5 text-sm font-black text-white disabled:opacity-40">{addingCenter?'Adding…':'Add Center'}</button></div></form></div>}
 </main>
}