'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { OperationalRecord, vehicleOperationsApi } from '@/lib/vehicle-operations';
import { Ledger, ledgerApi } from '@/lib/ledgers';

const input = 'h-12 w-full rounded-xl border border-slate-200 bg-slate-50/80 px-3 text-sm font-semibold text-slate-900 outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50';
const label = 'grid gap-1.5 text-[11px] font-black uppercase tracking-[.04em] text-slate-500';
const money=(n:number)=>`₹${n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

type GovtPayer='owner'|'us'|'agent';
type Master={id:string;name:string};

function addMonths(date:string,months:number){if(!date||!months)return'';const d=new Date(`${date}T00:00:00`);const day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()!==day)d.setDate(0);return d.toISOString().slice(0,10)}

export default function FitnessPage(){
 const {vehicleId}=useParams<{vehicleId:string}>();
 const [rows,setRows]=useState<OperationalRecord[]>([]);
 const [centers,setCenters]=useState<Master[]>([]);
 const [ledgers,setLedgers]=useState<Ledger[]>([]);
 const [period,setPeriod]=useState(''); const [issueDate,setIssueDate]=useState('');
 const [totalAmount,setTotalAmount]=useState(''); const [govtFee,setGovtFee]=useState(''); const [govtPaidBy,setGovtPaidBy]=useState<GovtPayer>('owner');
 const [outsourced,setOutsourced]=useState(false); const [agentLedgerId,setAgentLedgerId]=useState(''); const [agentCost,setAgentCost]=useState('');
 const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const expiry=useMemo(()=>addMonths(issueDate,Number(period||0)),[issueDate,period]);
 const total=Number(totalAmount||0),govt=Number(govtFee||0),agent=Number(agentCost||0); const service=Math.max(0,total-govt);
 const splitInvalid=govt>total&&total>0;
 const customerReceivable=govtPaidBy==='owner'?service:total;
 const creditorLedgers=useMemo(()=>ledgers.filter(l=>l.status==='active'&&l.ledger_group==='Sundry Creditors').sort((a,b)=>a.ledger_name.localeCompare(b.ledger_name)),[ledgers]);
 const bankLedgers=useMemo(()=>ledgers.filter(l=>l.status==='active'&&['Bank Accounts','Cash-in-Hand'].includes(l.ledger_group)).sort((a,b)=>a.ledger_name.localeCompare(b.ledger_name)),[ledgers]);
 const selectedAgent=creditorLedgers.find(l=>l.id===agentLedgerId);
 const load=()=>vehicleOperationsApi.list(vehicleId,'fitness').then(setRows).catch(e=>setError(e instanceof Error?e.message:'Fitness history could not be loaded.'));
 const loadMasters=async()=>{setCenters((await vehicleOperationsApi.masters('fitness_center')).sort((a,b)=>a.name.localeCompare(b.name)));setLedgers(await ledgerApi.list())};
 useEffect(()=>{void load();void loadMasters().catch(()=>undefined)},[vehicleId]);
 async function addCenter(){const name=prompt('Fitness / Inspection center name');if(!name?.trim())return;const added=await vehicleOperationsApi.addMaster('fitness_center',name.trim());setCenters(c=>[...c.filter(x=>x.id!==added.id),added].sort((a,b)=>a.name.localeCompare(b.name)))}
 async function addAgentLedger(){const name=prompt('Fitness agent / vendor name');if(!name?.trim())return;const added=await ledgerApi.create({ledger_name:name.trim(),ledger_group:'Sundry Creditors',opening_balance:0,balance_type:'credit',credit_limit:0,credit_days:30,gst_applicable:false,status:'active'});setLedgers(c=>[...c,added]);setAgentLedgerId(added.id)}
 async function ensureClearing(){if(govt<=0||govtPaidBy==='owner')return;const exists=ledgers.find(l=>l.ledger_name.toUpperCase()==='GOVERNMENT FEE CLEARING');if(!exists){const added=await ledgerApi.create({ledger_name:'GOVERNMENT FEE CLEARING',ledger_group:'Current Assets',opening_balance:0,balance_type:'debit',credit_limit:0,credit_days:0,gst_applicable:false,status:'active'});setLedgers(c=>[...c,added])}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(splitInvalid){setError('Government fee cannot be more than total amount.');return}if((outsourced||govtPaidBy==='agent')&&!agentLedgerId){setError('Select Fitness Agent ledger.');return}setSaving(true);setError('');const fd=new FormData(e.currentTarget);let createdId='';try{
   await ensureClearing();
   const center=String(fd.get('inspection_name')||'');
   const created=await vehicleOperationsApi.create(vehicleId,'fitness',{period,issue_date:issueDate,expiry_date:expiry,reference_number:fd.get('reference_number'),receipt_date:fd.get('receipt_date'),party_amount:customerReceivable,amount:total,vendor:selectedAgent?.ledger_name||undefined,notes:`Fitness Center: ${center} | Total ${money(total)} | Govt Fee ${money(govt)} | Service ${money(service)} | Govt paid by ${govtPaidBy}${outsourced?` | Agent cost ${money(agent)}`:''}`});createdId=created.id;
   if(customerReceivable>0)await vehicleOperationsApi.create(vehicleId,'payment',{payment_type:'Fitness Bill',account:'FITNESS SERVICE',issue_date:issueDate,billed_amount:customerReceivable,reference_number:`FIT-${created.id}`,notes:`Fitness customer bill | record ${created.id}`});
   if(outsourced&&agent>0)await vehicleOperationsApi.create(vehicleId,'agent_payment',{party_name:selectedAgent?.ledger_name,account:'FITNESS AGENT PAYABLE',issue_date:issueDate,billed_amount:agent,paid_amount:0,reference_number:`FIT-${created.id}`,notes:`Fitness outsourced cost accrued | record ${created.id}`});
   if(govt>0&&govtPaidBy==='agent')await vehicleOperationsApi.create(vehicleId,'agent_payment',{party_name:selectedAgent?.ledger_name,account:'GOVERNMENT FEE CLEARING',issue_date:issueDate,billed_amount:govt,paid_amount:0,reference_number:`FIT-GOVT-${created.id}`,notes:`Fitness government fee paid by agent | record ${created.id}`});
   if(govt>0&&govtPaidBy==='us')await vehicleOperationsApi.create(vehicleId,'payment',{payment_type:'Fitness Government Fee',account:String(fd.get('government_fee_bank_ledger_id')||''),issue_date:issueDate,billed_amount:0,paid_amount:govt,reference_number:`FIT-GOVT-${created.id}`,notes:`Government fee via GOVERNMENT FEE CLEARING | record ${created.id}`});
   e.currentTarget.reset();setPeriod('');setIssueDate('');setTotalAmount('');setGovtFee('');setGovtPaidBy('owner');setOutsourced(false);setAgentLedgerId('');setAgentCost('');await load();
 }catch(err){if(createdId){try{await vehicleOperationsApi.remove(vehicleId,'fitness',createdId)}catch{}}setError(err instanceof Error?err.message:'Fitness record could not be saved.')}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#f4f7fc] p-3 text-[#081a3a] sm:p-5 md:p-7"><div className="mx-auto max-w-7xl space-y-4">
  <section className="relative overflow-hidden rounded-[28px] border border-[#173d78] bg-[#071a3c] p-6 text-white shadow-[0_24px_70px_rgba(7,26,60,.20)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_88%_12%,rgba(48,143,255,.48),transparent_35%),linear-gradient(135deg,#06152f,#0a2555_60%,#0c3478)]"/><div className="relative flex items-center justify-between"><div><a href={`/vehicles/${vehicleId}`} className="text-xs font-bold text-blue-200">← Vehicle Profile</a><p className="mt-5 text-[9px] font-black uppercase tracking-[.24em] text-[#63d4ff]">Commercial compliance</p><h1 className="mt-1 text-3xl font-black">Fitness</h1><p className="mt-2 text-xs text-blue-100/70">Validity, statutory fee and outsourced agent accounting in one entry.</p></div><div className="grid h-20 w-20 place-items-center rounded-[24px] border border-white/10 bg-white/10 text-4xl">✓</div></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
  <form onSubmit={submit} className="overflow-hidden rounded-[26px] border border-[#d9e5f7] bg-white shadow-[0_14px_40px_rgba(26,64,120,.08)]">
   <div className="border-b border-slate-100 bg-gradient-to-r from-white to-blue-50/70 px-6 py-4"><p className="text-[9px] font-black uppercase tracking-[.22em] text-blue-500">New Fitness</p><h2 className="mt-1 text-xl font-black">Fitness Entry</h2></div>
   <div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6">
    <label className={label}>Period *<select required value={period} onChange={e=>setPeriod(e.target.value)} className={input}><option value="">Select Period</option><option value="12">12 Month</option><option value="24">2 Year</option><option value="60">5 Year</option><option value="180">15 Year</option></select></label>
    <label className={label}>Issue Date *<input type="date" required value={issueDate} onChange={e=>setIssueDate(e.target.value)} className={input}/></label>
    <label className={label}>Expire Date<input type="date" readOnly value={expiry} className={`${input} bg-blue-50/60`}/></label>
    <label className={label}>Receipt No *<input name="reference_number" required className={input}/></label>
    <label className={label}>Receipt Date *<input name="receipt_date" type="date" required className={input}/></label>
    <label className={label}>Fitness / Inspection Center *<div className="flex gap-2"><select name="inspection_name" required className={input}><option value="">Select center</option>{centers.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select><button type="button" onClick={()=>void addCenter()} className="h-12 min-w-12 rounded-xl border border-blue-200 bg-blue-50 font-black text-blue-700">+</button></div></label>
   </div>
   <section className="mx-5 mb-5 rounded-[22px] border border-slate-200 bg-[#fbfdff] p-5 sm:mx-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-600">Billing</p><h3 className="mt-1 text-lg font-black">Customer & Government Fee</h3></div><div className="rounded-xl bg-[#081f49] px-4 py-2.5 text-right text-white"><p className="text-[8px] font-black uppercase text-blue-200">Receivable</p><p className="text-xl font-black">{money(customerReceivable)}</p></div></div>
    <div className="grid gap-4 lg:grid-cols-3"><label className={label}>Total Amount Charged *<input type="number" min="0" step="0.01" required value={totalAmount} onChange={e=>setTotalAmount(e.target.value)} className={input}/></label><label className={label}>Government Fee<input type="number" min="0" step="0.01" value={govtFee} onChange={e=>{setGovtFee(e.target.value);if(Number(e.target.value||0)<=0)setGovtPaidBy('owner')}} className={input}/></label><div className="rounded-xl border border-emerald-200 bg-emerald-50/50 px-4 py-3"><p className="text-[9px] font-black uppercase text-emerald-700">Service + Other</p><p className="mt-1 text-2xl font-black">{money(service)}</p><p className="text-[10px] font-semibold text-slate-500">Auto: Total − Govt Fee</p></div></div>
    {govt>0&&<div className="mt-4 grid gap-4 border-t border-slate-200 pt-4 lg:grid-cols-3"><label className={label}>Government Fee Paid By<select value={govtPaidBy} onChange={e=>setGovtPaidBy(e.target.value as GovtPayer)} className={input}><option value="owner">Customer / Owner</option><option value="us">Office / Us</option><option value="agent">Fitness Agent</option></select></label>{govtPaidBy==='us'&&<label className={label}>Paid From Bank / Cash *<select name="government_fee_bank_ledger_id" required className={input}><option value="">Select account</option>{bankLedgers.map(l=><option key={l.id} value={l.id}>{l.ledger_name}</option>)}</select></label>}</div>}
   </section>
   <section className="mx-5 mb-5 rounded-[22px] border border-amber-200 bg-amber-50/30 p-5 sm:mx-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-amber-700">Outsource</p><h3 className="mt-1 text-lg font-black">Fitness Agent</h3></div><button type="button" onClick={()=>setOutsourced(v=>!v)} className={`rounded-full px-4 py-2 text-xs font-black ${outsourced?'bg-amber-600 text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{outsourced?'YES':'NO'}</button></div>{(outsourced||govtPaidBy==='agent')&&<div className="grid gap-4 lg:grid-cols-2"><label className={label}>Agent Ledger *<div className="flex gap-2"><select required value={agentLedgerId} onChange={e=>setAgentLedgerId(e.target.value)} className={input}><option value="">Select agent</option>{creditorLedgers.map(l=><option key={l.id} value={l.id}>{l.ledger_name}</option>)}</select><button type="button" onClick={()=>void addAgentLedger()} className="h-12 min-w-12 rounded-xl border border-amber-200 bg-white font-black text-amber-700">+</button></div></label>{outsourced&&<label className={label}>Agent Cost *<input type="number" min="0" step="0.01" required value={agentCost} onChange={e=>setAgentCost(e.target.value)} className={input}/><span className="normal-case font-semibold tracking-normal text-slate-400">Monthly payable to agent.</span></label>}</div>}</section>
   <div className="flex flex-col gap-3 border-t border-slate-100 bg-[#f8fbff] p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="grid gap-1 text-[10px] font-semibold text-slate-500"><span>Fitness income: {money(service)}</span><span>Agent payable: {money(agent+(govtPaidBy==='agent'?govt:0))}</span></div><button disabled={saving||!expiry||splitInvalid} className="min-w-[210px] rounded-2xl bg-gradient-to-r from-[#0b2b62] to-[#2563eb] px-6 py-3.5 text-sm font-black text-white disabled:opacity-50">{saving?'Saving…':'+ Add Fitness'}</button></div>
  </form>
  <section className="overflow-hidden rounded-[26px] border border-[#d9e5f7] bg-white"><div className="border-b border-slate-100 px-6 py-4"><p className="text-[9px] font-black uppercase tracking-[.22em] text-blue-500">History</p><h2 className="mt-1 text-xl font-black">Fitness Records</h2></div><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-sm"><thead className="bg-[#f8fbff] text-[9px] font-black uppercase text-slate-400"><tr><th className="p-4 text-left">Period</th><th className="p-4 text-left">Issue</th><th className="p-4 text-left">Expiry</th><th className="p-4 text-left">Receipt</th><th className="p-4 text-left">Details</th><th className="p-4 text-left">Customer Due</th><th className="p-4 text-left">Total</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="p-4 font-black">{String(r.period??'—')} Mo</td><td className="p-4">{String(r.issue_date??'—')}</td><td className="p-4">{String(r.expiry_date??'—')}</td><td className="p-4">{String(r.reference_number??'—')}</td><td className="p-4 max-w-[360px] text-xs text-slate-500">{String(r.notes??'—')}</td><td className="p-4 font-black text-blue-700">{money(Number(r.party_amount??0))}</td><td className="p-4 font-black">{money(Number(r.amount??0))}</td><td className="p-4 text-center"><button onClick={()=>confirm('Delete this fitness record?')&&vehicleOperationsApi.remove(vehicleId,'fitness',r.id).then(load)} className="font-black text-red-600">Delete</button></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-10 text-center text-sm font-semibold text-slate-400">No fitness records added yet.</p>}</div></section>
 </div></main>
}
