'use client';

import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { financeControlApi,OutstandingPayload } from '@/lib/finance-control';

const money=(n:number|string|undefined)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export default function OutstandingPage(){
 const[data,setData]=useState<OutstandingPayload|null>(null);const[search,setSearch]=useState('');const[error,setError]=useState('');const[downloading,setDownloading]=useState<'receivable'|'payable'|''>('');
 async function load(){setError('');try{setData(await financeControlApi.outstanding())}catch(e){setError(e instanceof Error?e.message:'Outstanding could not load.')}}
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>data?.rows.filter(r=>!search||r.name.toLowerCase().includes(search.toLowerCase())||r.group.toLowerCase().includes(search.toLowerCase()))??[],[data,search]);
 async function pdf(type:'receivable'|'payable'){setDownloading(type);setError('');try{await financeControlApi.downloadOutstanding(type)}catch(e){setError(e instanceof Error?e.message:'PDF report could not be generated.')}finally{setDownloading('')}}
 const customerReceivable=Number(data?.summary.customer_receivable||0);const otherReceivable=Number(data?.summary.ledger_receivable||0);const totalReceivable=Number(data?.summary.total_receivable||0);const payable=Number(data?.summary.party_payable||0);const commission=Number(data?.summary.insurance_commission_due||0);
 return <main className="min-h-screen bg-[#f3f7fc] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1400px] space-y-5">
  <section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#07172f] via-[#0d3474] to-[#2167df] p-7 text-white shadow-xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-cyan-200">Money Control</p><h1 className="mt-2 text-4xl font-black">Receivable & Payable</h1><p className="mt-2 max-w-2xl text-sm text-blue-100/80">Customer bills tell you what has to come in. Party and insurer liabilities tell you what has to go out. Insurance commission stays separate.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void pdf('receivable')} disabled={!!downloading} className="rounded-xl bg-white px-4 py-3 text-sm font-black text-blue-800 disabled:opacity-60">{downloading==='receivable'?'Generating…':'↓ Receivable PDF'}</button><button onClick={()=>void pdf('payable')} disabled={!!downloading} className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-black text-white disabled:opacity-60">{downloading==='payable'?'Generating…':'↓ Payable PDF'}</button></div></div></section>
  {error&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700"><span>{error}</span><button onClick={()=>void load()} className="rounded-xl bg-red-700 px-4 py-2 text-xs font-black text-white">Retry</button></div>}

  <section className="grid gap-3 lg:grid-cols-[1.15fr_.85fr_.85fr]">
   <Link href="#balances" className="rounded-[24px] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">To Collect · Customers</p><p className="mt-2 text-3xl font-black text-emerald-800">{money(customerReceivable)}</p><p className="mt-1 text-xs font-semibold text-emerald-700/60">Policy + RTO/service bills not yet received</p></Link>
   <Link href="#balances" className="rounded-[24px] border border-rose-200 bg-gradient-to-br from-rose-50 to-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.18em] text-rose-700">To Pay</p><p className="mt-2 text-3xl font-black text-rose-800">{money(payable)}</p><p className="mt-1 text-xs font-semibold text-rose-700/60">Insurer / broker / party liabilities</p></Link>
   <Link href="/reports/insurance-commission" className="rounded-[24px] border border-blue-200 bg-gradient-to-br from-blue-50 to-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.18em] text-blue-700">Commission Receivable · Separate</p><p className="mt-2 text-3xl font-black text-blue-800">{money(commission)}</p><p className="mt-1 text-xs font-semibold text-blue-700/60">Company/source se commission lena hai</p></Link>
  </section>

  {(otherReceivable>0)&&<div className="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm text-slate-600"><b className="text-slate-900">Other ledger receivable: {money(otherReceivable)}</b> · Total customer/party collection position: <b className="text-emerald-700">{money(totalReceivable)}</b>. Commission is not included in this figure.</div>}

  <section id="balances" className="overflow-hidden rounded-[26px] border border-[#dbe6f3] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-xl font-black text-[#0b2d61]">Who owes us / whom do we owe?</h2><p className="mt-1 text-xs text-slate-500">Customer Receivable comes from billed amount minus received amount. Commission is intentionally outside this table.</p></div><div className="flex flex-wrap items-center gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer / party…" className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold outline-none focus:border-blue-400"/><Link href="/fleets" className="rounded-2xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-black text-blue-700">Fleet Balances →</Link></div></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="bg-[#f8fbff] text-left text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="p-4">Customer / Party</th><th className="p-4">Balance Type</th><th className="p-4">To Collect</th><th className="p-4">To Pay</th><th className="p-4">Action</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id} className="border-t hover:bg-slate-50/70"><td className="p-4 font-black text-[#123b78]">{r.name}</td><td className="p-4 text-slate-500">{r.group}</td><td className="p-4 font-black text-emerald-700">{r.receivable?money(r.receivable):'—'}</td><td className="p-4 font-black text-rose-700">{r.payable?money(r.payable):'—'}</td><td className="p-4"><Link href="/accounts/cash-bank" className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-black text-blue-700">Receive / Pay</Link></td></tr>):<tr><td colSpan={5} className="p-10 text-center font-semibold text-slate-400">{data?'No outstanding balance.':'Loading balances…'}</td></tr>}</tbody></table></div>
  </section>
 </div></main>
}
