"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { Customer, CustomerPagination, customerApi } from "@/lib/customers";

type Props={customers:Customer[];meta?:CustomerPagination;onChanged:()=>void};

export function CustomerTable({customers,meta,onChanged}:Props){
 const router=useRouter(),params=useSearchParams();
 const [selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[term,setTerm]=useState(params.get("search")??"");
 const cities=useMemo(()=>Array.from(new Set(customers.map(c=>c.city).filter((x):x is string=>Boolean(x)))).sort(),[customers]);
 const totals=useMemo(()=>({vehicles:customers.reduce((n,c)=>n+c.vehicles_count,0),policies:customers.reduce((n,c)=>n+c.insurance_policies_count,0),rto:customers.reduce((n,c)=>n+c.rto_files_count,0),active:customers.filter(c=>c.status==="active").length,priority:customers.filter(c=>["high","urgent"].includes(c.priority)).length}),[customers]);
 const filtersActive=["search","status","city","priority","sort","direction"].some(k=>params.has(k));
 function update(key:string,value:string){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);next.delete("page");router.push(`/customers?${next}`)}
 function page(value:number){const next=new URLSearchParams(params);next.set("page",String(value));router.push(`/customers?${next}`)}
 async function exportRows(format:"csv"|"pdf"){try{setBusy(format);await customerApi.export(format,params.toString())}catch(e){setMessage(e instanceof Error?e.message:"Export failed.")}finally{setBusy("")}}
 async function bulkDelete(){if(!selected.length||!confirm(`Delete ${selected.length} selected customers?`))return;try{setBusy("delete");await customerApi.bulkDelete(selected);setSelected([]);onChanged()}catch(e){setMessage(e instanceof Error?e.message:"Delete failed.")}finally{setBusy("")}}
 async function assign(){if(!selected.length)return;const id=prompt("Assign to user UUID");if(!id)return;try{setBusy("assign");await customerApi.bulkAssign(selected,id);setSelected([]);onChanged()}catch(e){setMessage(e instanceof Error?e.message:"Assignment failed.")}finally{setBusy("")}}
 async function importCustomers(file:File){if(!file.name.toLowerCase().endsWith(".csv")){setMessage("Please select a CSV file.");return}try{setBusy("import");const lines=(await file.text()).split(/\r?\n/).filter(l=>l.trim());if(lines.length<2)throw new Error("The CSV file has no customer rows.");const headers=parseCsvLine(lines[0]).map(h=>h.trim().toLowerCase().replaceAll(" ","_"));if(["first_name","last_name","mobile"].some(h=>!headers.includes(h)))throw new Error("CSV requires first_name, last_name and mobile columns.");let imported=0;for(const line of lines.slice(1)){const values=parseCsvLine(line);const row=Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()||null]));await customerApi.create({...row,priority:row.priority||"normal",status:row.status||"active",tags:[]});imported++}setMessage(`${imported} customer${imported===1?"":"s"} imported.`);onChanged()}catch(e){setMessage(e instanceof Error?e.message:"Import failed.")}finally{setBusy("")}}
 const allSelected=customers.length>0&&customers.every(c=>selected.includes(c.id));
 return <div className="mx-auto max-w-[1700px] space-y-5">
  <section className="relative overflow-hidden rounded-[30px] border border-[#153d79] bg-[#071a3c] p-6 text-white shadow-[0_25px_70px_rgba(7,26,60,.22)] sm:p-8">
   <div className="absolute inset-0 bg-[radial-gradient(circle_at_90%_10%,rgba(49,124,255,.5),transparent_32%),linear-gradient(135deg,#06152f,#0a2555_58%,#0d3b87)]"/>
   <div className="relative flex flex-wrap items-end justify-between gap-6"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#63d4ff]">Relationship workspace</p><h1 className="mt-2 text-4xl font-black tracking-tight">Customer CRM</h1><p className="mt-2 max-w-2xl text-sm text-blue-100/75">Customers, vehicles, policies and RTO work — one clean relationship view.</p></div><div className="flex flex-wrap gap-2"><Link href="/accounts/ledgers" className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-black backdrop-blur">Ledger Master</Link><label className="cursor-pointer rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-black backdrop-blur">{busy==="import"?"Importing…":"Import CSV"}<input type="file" accept=".csv,text/csv" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void importCustomers(f);e.target.value=""}}/></label><Link href="/customers/new" className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-[#0b3475] shadow-lg">＋ Add Customer</Link></div></div>
  </section>

  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{[["Customers",meta?.total??customers.length,"👥"],["Active",totals.active,"✓"],["Vehicles",totals.vehicles,"🚘"],["Policies",totals.policies,"🛡"],["RTO Files",totals.rto,"🏛"],["Priority",totals.priority,"★"]].map(([l,v,i])=><article key={String(l)} className="rounded-[22px] border border-[#dbe5f2] bg-white p-4 shadow-[0_10px_30px_rgba(15,40,86,.06)]"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#eff5ff] text-lg">{i}</span><span className="text-[9px] font-black uppercase tracking-[.14em] text-slate-400">Live</span></div><p className="mt-4 text-[10px] font-black uppercase tracking-wide text-slate-400">{l}</p><p className="mt-1 text-2xl font-black text-[#081a3a]">{Number(v).toLocaleString("en-IN")}</p></article>)}</section>

  {message&&<div className="flex items-center justify-between rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-800"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}

  <section className="overflow-hidden rounded-[28px] border border-[#dbe5f2] bg-white shadow-[0_18px_55px_rgba(15,40,86,.08)]">
   <div className="border-b border-slate-100 bg-gradient-to-b from-white to-[#f7faff] p-4 sm:p-5"><div className="grid gap-3 xl:grid-cols-[minmax(320px,1fr)_repeat(4,150px)]"><label className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input value={term} onChange={e=>setTerm(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")update("search",term)}} placeholder="Search customer, mobile or code…" className="h-12 w-full rounded-2xl border border-[#dbe5f2] bg-white pl-11 pr-4 text-sm font-semibold outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50"/></label><Filter label="Status" value={params.get("status")??""} set={v=>update("status",v)} options={["active","inactive"]}/><Filter label="City" value={params.get("city")??""} set={v=>update("city",v)} options={cities}/><Filter label="Priority" value={params.get("priority")??""} set={v=>update("priority",v)} options={["low","normal","high","urgent"]}/><Filter label="Sort" value={params.get("sort")??""} set={v=>update("sort",v)} options={["created_at","first_name","customer_code","city","priority"]}/></div>
   <div className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-blue-100 bg-blue-50/50 px-4 py-2.5"><p className="text-xs font-black text-slate-600">{selected.length?`${selected.length} selected`:`${meta?.total??customers.length} total customers`}</p><div className="flex flex-wrap gap-2">{filtersActive&&<button onClick={()=>{setTerm("");router.push("/customers")}} className="rounded-xl bg-white px-3 py-2 text-[10px] font-black text-slate-600">Clear</button>}<button onClick={()=>void exportRows("csv")} className="rounded-xl bg-white px-3 py-2 text-[10px] font-black text-blue-700">CSV</button><button onClick={()=>void exportRows("pdf")} className="rounded-xl bg-white px-3 py-2 text-[10px] font-black text-blue-700">PDF</button><button onClick={()=>window.print()} className="rounded-xl bg-white px-3 py-2 text-[10px] font-black text-blue-700">Print</button><button disabled={!selected.length||Boolean(busy)} onClick={()=>void assign()} className="rounded-xl bg-white px-3 py-2 text-[10px] font-black text-blue-700 disabled:opacity-30">Assign</button><button disabled={!selected.length||Boolean(busy)} onClick={()=>void bulkDelete()} className="rounded-xl bg-rose-50 px-3 py-2 text-[10px] font-black text-rose-600 disabled:opacity-30">Delete</button></div></div></div>

   {customers.length?<div className="grid gap-3 p-3 sm:p-4">{customers.map(customer=><CustomerWorkspaceCard key={customer.id} customer={customer} checked={selected.includes(customer.id)} select={checked=>setSelected(cur=>checked?[...new Set([...cur,customer.id])]:cur.filter(id=>id!==customer.id))}/>)}</div>:<div className="p-16 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-[26px] bg-blue-50 text-3xl">👥</div><h2 className="mt-4 text-xl font-black">{filtersActive?"No matching customers":"Customer workspace is ready"}</h2><p className="mt-2 text-sm text-slate-500">{filtersActive?"Try a broader search or clear filters.":"Add your first customer to get started."}</p></div>}
   <Pagination meta={meta} fallback={customers.length} go={page}/>
  </section>
 </div>
}

function CustomerWorkspaceCard({customer,checked,select}:{customer:Customer;checked:boolean;select:(v:boolean)=>void}){const name=[customer.first_name,customer.middle_name,customer.last_name].filter(Boolean).join(" "),initials=`${customer.first_name?.[0]??""}${customer.last_name?.[0]??""}`.toUpperCase();return <article className="group overflow-hidden rounded-[24px] border border-[#dce6f2] bg-white transition hover:-translate-y-0.5 hover:shadow-[0_18px_40px_rgba(18,59,120,.10)]"><div className="grid lg:grid-cols-[300px_1fr_360px]">
 <div className="relative overflow-hidden bg-[#081a3a] p-5 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_100%_0%,rgba(45,112,255,.5),transparent_45%)]"/><div className="relative"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/10 text-sm font-black">{initials||"CU"}</span><input aria-label={`Select ${name}`} type="checkbox" checked={checked} onChange={e=>select(e.target.checked)} className="h-4 w-4"/></div><Link href={`/customers/${customer.id}`} className="mt-5 block truncate text-xl font-black hover:text-blue-200">{name}</Link><p className="mt-1 text-[10px] font-black uppercase tracking-[.14em] text-blue-200/65">{customer.customer_code}</p><p className="mt-5 text-sm font-bold text-blue-100">☎ {customer.mobile}</p><p className="mt-2 text-xs text-blue-100/60">⌖ {customer.city||"City not added"}</p></div></div>
 <div className="grid gap-3 p-5 sm:grid-cols-2"><Detail label="Vehicles" value={String(customer.vehicles_count)}/><Detail label="Insurance Policies" value={String(customer.insurance_policies_count)}/><Detail label="RTO Files" value={String(customer.rto_files_count)}/><Detail label="GST" value={customer.gst_number||"Not added"}/><Detail label="Priority" value={human(customer.priority)}/><Detail label="Status" value={human(customer.status)}/></div>
 <div className="flex flex-col justify-between border-t border-slate-100 bg-[#fbfdff] p-5 lg:border-l lg:border-t-0"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-500">Customer actions</p><p className="mt-2 text-xs leading-5 text-slate-500">Open profile for complete relationship history or start a connected workflow.</p></div><div className="mt-5 grid grid-cols-2 gap-2"><Link href={`/customers/${customer.id}`} className="col-span-2 rounded-2xl bg-[#0b2f6b] px-4 py-3 text-center text-xs font-black text-white shadow-sm">Open Customer</Link><Link href={`/customers/${customer.id}/edit`} className="rounded-xl border border-slate-200 px-3 py-2.5 text-center text-[10px] font-black text-slate-700">Edit</Link><Link href={`/customers/${customer.id}/timeline`} className="rounded-xl border border-slate-200 px-3 py-2.5 text-center text-[10px] font-black text-slate-700">Timeline</Link><Link href={`/vehicles/new?customer_id=${customer.id}`} className="col-span-2 rounded-xl border border-blue-100 bg-blue-50 px-3 py-2.5 text-center text-[10px] font-black text-blue-700">＋ Add Vehicle</Link></div></div>
 </div></article>}
function Detail({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-100 bg-slate-50/70 p-3"><p className="text-[9px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-black text-[#10213f]">{value}</p></div>}
function human(v?:string){return v?v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"Not added"}
function Filter({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <select aria-label={label} value={value} onChange={e=>set(e.target.value)} className="h-12 rounded-2xl border border-[#dbe5f2] bg-white px-3 text-xs font-black text-slate-700 outline-none focus:border-blue-400"><option value="">All {label}</option>{options.map(x=><option key={x} value={x}>{human(x)}</option>)}</select>}
function Pagination({meta,fallback,go}:{meta?:CustomerPagination;fallback:number;go:(p:number)=>void}){const current=meta?.current_page??1,last=meta?.last_page??1,total=meta?.total??fallback;return <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 bg-[#fbfdff] p-4 text-sm"><span className="font-semibold text-slate-500">{total} customers · Page {current} of {last}</span><div className="flex gap-2"><button disabled={current<=1} onClick={()=>go(current-1)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-black disabled:opacity-40">Previous</button><button disabled={current>=last} onClick={()=>go(current+1)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-black disabled:opacity-40">Next</button></div></div>}
function parseCsvLine(line:string){const values:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&quoted){value+='"';i++}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){values.push(value);value=""}else value+=c}values.push(value);return values}
