import Link from "next/link";

const lines=[
 {title:"Motor Insurance",desc:"Retail and wholesale motor policy entry with vehicle linkage, premium calculation, company/purchase-source flow and commission.",href:"/insurance/motor",tag:"Motor"},
 {title:"Non-Motor Insurance",desc:"Fire, shop, property, marine, engineering, liability and other business covers.",href:"/insurance/non_motor",tag:"Property & Business"},
 {title:"Health Insurance",desc:"Individual, family floater, group health, top-up and critical illness policies.",href:"/insurance/health",tag:"Health"},
 {title:"Life Insurance",desc:"Term, endowment, pension, child and savings policies.",href:"/insurance/life",tag:"Life"},
] as const;

const flow=[
 ["1","Select customer + Retail / Wholesale","Policy kis customer aur kis business channel se aayi, pehle clear karo."],
 ["2","Enter policy + premium","Company, purchase source, dates, cover and premium save karo."],
 ["3","Collect customer payment","Customer due ko follow karo; company payment se mix mat karo."],
 ["4","Pay company / purchase source","Provider payable Company Payments queue se clear karo."],
 ["5","Receive commission","Expected, TDS, received aur outstanding Commission queue me match karo."],
 ["6","Renewal / Claim","Expiry follow-up ya claim intimation ko dedicated desk me continue karo."],
] as const;

export default function InsuranceHub(){return <main className="min-h-screen bg-[#f4f7fb] p-4 md:p-6 dark:bg-[#050914]"><div className="mx-auto max-w-[1480px] space-y-5">
<section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#06172f] via-[#0c3477] to-[#2674ef] p-7 text-white shadow-xl"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-200">Insurance Operations</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em] md:text-5xl">Policy se payment, commission aur claim tak.</h1><p className="mt-3 max-w-3xl text-sm font-semibold leading-6 text-blue-100/80">Retail + wholesale ke liye ek guided operating system. Naya employee bhi screen ke sequence se samajh sake ki ab next kaam kya hai.</p></div><div className="flex flex-wrap gap-2"><Link href="/insurance/company-payments" className="rounded-2xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-black">Company Payments</Link><Link href="/insurance/commissions" className="rounded-2xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-black">Commission</Link><Link href="/claims" className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-[#12376d]">Claims Desk</Link></div></div></section>

<section className="grid gap-4 xl:grid-cols-[1fr_390px]"><div className="grid gap-4 md:grid-cols-2">{lines.map(card=><Link key={card.title} href={card.href} className="group rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg dark:border-slate-800 dark:bg-slate-900"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{card.tag}</span><h2 className="mt-4 text-2xl font-black text-slate-950 dark:text-white">{card.title}</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-500">{card.desc}</p><p className="mt-5 text-sm font-black text-blue-700">Open guided entry →</p></Link>)}</div><aside className="rounded-[26px] bg-[#0d2b55] p-5 text-white"><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-300">Employee operating flow</p><h2 className="mt-2 text-2xl font-black">Bas is order me kaam karo.</h2><div className="mt-5 space-y-2">{flow.map(([n,title,desc])=><div key={n} className="flex gap-3 rounded-xl bg-white/[.07] p-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-cyan-300/15 text-[10px] font-black text-cyan-200">{n}</span><span><strong className="block text-xs">{title}</strong><small className="mt-1 block text-[9px] leading-4 text-blue-100/55">{desc}</small></span></div>)}</div></aside></section>

<section className="grid gap-4 md:grid-cols-3"><Link href="/insurance/company-payments" className="rounded-[22px] border border-slate-200 bg-white p-5 transition hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-emerald-600">Step 4 · Settlement</p><h3 className="mt-2 text-xl font-black">Company / Source Payments</h3><p className="mt-2 text-xs leading-5 text-slate-500">Motor, Non-Motor, Health aur Life ke provider payments ek queue me.</p></Link><Link href="/insurance/commissions" className="rounded-[22px] border border-slate-200 bg-white p-5 transition hover:border-violet-300 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-violet-600">Step 5 · Income</p><h3 className="mt-2 text-xl font-black">Commission Receivable</h3><p className="mt-2 text-xs leading-5 text-slate-500">Gross commission, TDS, receipt, UTR aur outstanding balance.</p></Link><Link href="/claims" className="rounded-[22px] border border-slate-200 bg-white p-5 transition hover:border-blue-300 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-blue-600">Step 6 · Service</p><h3 className="mt-2 text-xl font-black">Claim Operating System</h3><p className="mt-2 text-xs leading-5 text-slate-500">Fillable intimation, documents, surveyor, follow-up, approval, repair and settlement.</p></Link></section>
</div></main>}
