import Link from "next/link";

const cards=[
 {title:"Motor Insurance",desc:"CRM-first motor policy entry: select customer, vehicle type and vehicle, then open policy form with existing GST, premium and commission logic.",href:"/insurance/motor",tag:"Motor"},
 {title:"Non-Motor Insurance",desc:"Fire, property, home, shop, burglary, marine, engineering, liability and business covers.",href:"/insurance/non_motor",tag:"Property & Business"},
 {title:"Health Insurance",desc:"Individual, family floater, group health, top-up and critical illness policies.",href:"/insurance/health",tag:"Health"},
 {title:"Life Insurance",desc:"Term, endowment, whole-life, pension, child and savings policies.",href:"/insurance/life",tag:"Life"},
] as const;

export default function InsuranceHub(){return <main className="min-h-screen bg-[#f4f7fb] p-4 md:p-6 dark:bg-[#050914]"><div className="mx-auto max-w-[1450px] space-y-6"><section className="rounded-[30px] bg-gradient-to-br from-[#07162f] via-[#0d3478] to-[#2872ef] p-7 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-200">Insurance Workspace</p><h1 className="mt-2 text-4xl font-black">All Insurance</h1><p className="mt-2 max-w-3xl text-sm font-semibold text-blue-100/80">Every insurance line starts from CRM customer selection. Motor remains vehicle-linked; non-motor, health and life stay directly customer-linked. Premium is not treated as profit; commission remains the insurance earning.</p></section><section className="grid gap-4 md:grid-cols-2">{cards.map(card=><Link key={card.title} href={card.href} className="group rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg dark:border-slate-800 dark:bg-slate-900"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{card.tag}</span><h2 className="mt-4 text-2xl font-black text-slate-950 dark:text-white">{card.title}</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-500">{card.desc}</p><p className="mt-5 text-sm font-black text-blue-700">Open workspace →</p></Link>)}</section></div></main>}
