import Link from "next/link";

const lines=[
 {title:"Motor Insurance",desc:"Retail and wholesale motor policy entry with vehicle linkage, premium calculation, company/purchase-source flow and commission.",href:"/insurance/motor",tag:"Motor"},
 {title:"Non-Motor Insurance",desc:"Fire, shop, property, marine, engineering, liability and other business covers.",href:"/insurance/non_motor",tag:"Property & Business"},
 {title:"Health Insurance",desc:"Individual, family floater, group health, top-up and critical illness policies.",href:"/insurance/health",tag:"Health"},
 {title:"Life Insurance",desc:"Term, endowment, pension, child and savings policies.",href:"/insurance/life",tag:"Life"},
] as const;

const flow=["Select customer / channel","Enter policy & premium","Company / purchase source","Customer payment","Company settlement","Commission receivable","Renewal follow-up","Claim support"];

export default function InsuranceHub(){return <main className="min-h-screen bg-[#f4f7fb] p-4 md:p-6 dark:bg-[#050914]"><div className="mx-auto max-w-[1480px] space-y-5">
<section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#06172f] via-[#0c3477] to-[#2674ef] p-7 text-white shadow-xl"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-200">Insurance Operations</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em] md:text-5xl">Retail + Wholesale. Policy se commission tak.</h1><p className="mt-3 max-w-3xl text-sm font-semibold leading-6 text-blue-100/80">Employee ko accounting logic ya process yaad rakhne ki zarurat nahi honi chahiye. Same guided operating flow har insurance line me follow hoga.</p></div><div className="flex gap-2"><Link href="/claims" className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-[#12376d]">Claims desk</Link><Link href="/reports/insurance-commission" className="rounded-2xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-black text-white">Commission report</Link></div></div></section>

<section className="grid gap-4 xl:grid-cols-[1fr_360px]"><div className="grid gap-4 md:grid-cols-2">{lines.map(card=><Link key={card.title} href={card.href} className="group rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg dark:border-slate-800 dark:bg-slate-900"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{card.tag}</span><h2 className="mt-4 text-2xl font-black text-slate-950 dark:text-white">{card.title}</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-500">{card.desc}</p><p className="mt-5 text-sm font-black text-blue-700">Open workspace →</p></Link>)}</div><aside className="rounded-[26px] bg-[#0d2b55] p-5 text-white"><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-300">Standard employee flow</p><h2 className="mt-2 text-2xl font-black">Har policy ka same logic.</h2><div className="mt-5 space-y-2">{flow.map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-white/[.07] px-3 py-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/10 text-[10px] font-black text-cyan-200">{i+1}</span><span className="text-xs font-bold">{x}</span></div>)}</div></aside></section>

<section className="grid gap-4 md:grid-cols-3"><Link href="/insurance/company-payments" className="rounded-[22px] border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-emerald-600">Company settlement</p><h3 className="mt-2 text-xl font-black">Pending company payments</h3><p className="mt-2 text-xs leading-5 text-slate-500">Policy issue hone ke baad company ko payable / settlement control.</p></Link><Link href="/reports/insurance-commission" className="rounded-[22px] border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-violet-600">Income control</p><h3 className="mt-2 text-xl font-black">Commission receivable</h3><p className="mt-2 text-xs leading-5 text-slate-500">Company ya purchase source se aane wali commission track karo.</p></Link><Link href="/claims" className="rounded-[22px] border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-black uppercase tracking-wider text-blue-600">Claims desk</p><h3 className="mt-2 text-xl font-black">Intimation to closure</h3><p className="mt-2 text-xs leading-5 text-slate-500">Fillable claim form, surveyor, follow-up, approval and settlement.</p></Link></section>
</div></main>}
