'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {moduleLabels,OperationalRecord,VehicleModule,vehicleOperationsApi} from '@/lib/vehicle-operations';

type FieldSpec={name:string;label:string;type?:string;required?:boolean};
const common:FieldSpec[]=[{name:'reference_number',label:'Receipt / Reference'},{name:'period',label:'Period'},{name:'receipt_date',label:'Receipt Date',type:'date'},{name:'issue_date',label:'Issue Date',type:'date'},{name:'expiry_date',label:'Expiry Date',type:'date'},{name:'amount',label:'Amount',type:'number'},{name:'party_amount',label:'Party Amount',type:'number'},{name:'status',label:'Status'},{name:'notes',label:'Notes'}];
const fields:Partial<Record<VehicleModule,FieldSpec[]>>={
 permit:[{name:'permit_type',label:'Permit Type',required:true},{name:'state',label:'State'},...common],
 counter_tax:[...common,{name:'dealer_name',label:'Dealer Name'},{name:'dealer_amount',label:'Dealer Amount',type:'number'}],
 hsrp:[{name:'party_name',label:'Customer / Party'},{name:'order_date',label:'Order Date',type:'date'},{name:'received_date',label:'Received Date',type:'date'},{name:'delivery_date',label:'Delivery Date',type:'date'},{name:'vendor',label:'Vendor'},...common],
 sld:[{name:'vendor',label:'Vendor'},{name:'fitment_date',label:'Fitment Date',type:'date'},...common],
 rto_process:[{name:'work_type',label:'Work Type',required:true},{name:'process_date',label:'Open / Process Date',type:'date'},{name:'rto_office',label:'RTO Office'},{name:'broker',label:'Broker'},{name:'assigned_agent',label:'Assigned Agent'},{name:'external_agent',label:'External RTO Agent'},{name:'agent_amount',label:'Agent Amount',type:'number'},{name:'invoice_number',label:'Invoice Number'},...common],
 transfer:[{name:'new_owner_name',label:'Intended New Owner',required:true},{name:'application_date',label:'Application Date',type:'date'},{name:'completion_date',label:'Completion Date',type:'date'},{name:'reference_number',label:'Application / Reference'},{name:'status',label:'Status'},{name:'amount',label:'Fees',type:'number'},{name:'notes',label:'Notes'}],
 payment:[{name:'payment_type',label:'Payment Type'},{name:'account',label:'Cash / Bank / Account'},{name:'invoice_number',label:'Invoice Number'},{name:'issue_date',label:'Date',type:'date'},{name:'billed_amount',label:'Billed / Debit',type:'number'},{name:'paid_amount',label:'Received / Credit',type:'number'},{name:'reference_number',label:'Reference'},{name:'notes',label:'Remarks'}],
 agent_payment:[{name:'party_name',label:'Agent / Vendor'},{name:'account',label:'Method / Account'},{name:'issue_date',label:'Date',type:'date'},{name:'billed_amount',label:'Amount Payable',type:'number'},{name:'paid_amount',label:'Amount Paid',type:'number'},{name:'reference_number',label:'Reference'},{name:'notes',label:'Remarks'}],
 other_payment:[{name:'purpose',label:'Purpose / Category',required:true},{name:'party_name',label:'Party'},{name:'issue_date',label:'Date',type:'date'},{name:'party_amount',label:'Party Amount',type:'number'},{name:'amount',label:'Cost Amount',type:'number'},{name:'account',label:'Account'},{name:'reference_number',label:'Reference'},{name:'notes',label:'Remarks'}],
};

export default function VehicleOperationPage(){
 const {vehicleId,module:raw}=useParams<{vehicleId:string;module:string}>(); const module=raw as VehicleModule; const [rows,setRows]=useState<OperationalRecord[]>([]); const [masterOptions,setMasterOptions]=useState<{id:string;name:string}[]>([]); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [search,setSearch]=useState('');
 const masterType=module==='permit'?'permit_type':module==='rto_process'?'rto_work_type':module==='payment'?'payment_type':module==='other_payment'?'other_payment_category':'';
 const load=()=>vehicleOperationsApi.list(vehicleId,module).then(setRows).catch(e=>setError(e instanceof Error?e.message:'History could not be loaded.'));
 useEffect(()=>{void load()},[vehicleId,module]);
 useEffect(()=>{if(masterType)void vehicleOperationsApi.masters(masterType).then(setMasterOptions)},[masterType]);
 async function addMaster(){const name=prompt('Enter the new master value');if(!name?.trim())return;const added=await vehicleOperationsApi.addMaster(masterType,name.trim());setMasterOptions(current=>current.some(item=>item.id===added.id)?current:[...current,added].sort((a,b)=>a.name.localeCompare(b.name)))}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');const element=event.currentTarget;const form=new FormData(element);const document=form.get('document');form.delete('document');const body=Object.fromEntries([...form.entries()].filter(([,v])=>v!==''));try{const created=await vehicleOperationsApi.create(vehicleId,module,body);if(document instanceof File&&document.size)await vehicleOperationsApi.upload(vehicleId,module,created.id,document);element.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Record could not be saved.')}finally{setSaving(false)}}
 async function edit(row:OperationalRecord){const current=String(row.reference_number??row.status??'');const value=prompt('Update reference/status value',current);if(value===null)return;const key=row.reference_number!==undefined?'reference_number':'status';await vehicleOperationsApi.update(vehicleId,module,row.id,{[key]:value});await load()}
 const visible=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 return <main className="space-y-6 p-4 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><a href={`/vehicles/${vehicleId}`} className="text-sm font-semibold text-blue-700">← Vehicle Profile</a><h1 className="mt-2 text-3xl font-black">{moduleLabels[module]??'Vehicle Operation'}</h1></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{rows.length} history records</span></div>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
 <form onSubmit={submit} className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-4">{(fields[module]??common).map(field=>masterType&&['permit_type','work_type','payment_type','purpose'].includes(field.name)?<label key={field.name} className="grid gap-1 text-sm font-semibold">{field.label}<div className="flex gap-2"><input name={field.name} required={field.required} list={`${masterType}-options`} className="min-w-0 flex-1 rounded-xl border px-3 py-2.5 font-normal"/><button type="button" onClick={()=>void addMaster()} className="rounded-xl border px-3 text-blue-700">+ Add</button></div><datalist id={`${masterType}-options`}>{masterOptions.map(item=><option key={item.id} value={item.name}/>)}</datalist></label>:<Field key={field.name} {...field}/>)}<Field name="document" label="Supporting Document" type="file"/><div className="flex items-end"><button disabled={saving} className="w-full rounded-xl bg-blue-700 px-4 py-3 font-bold text-white disabled:opacity-50">{saving?'Saving...':'Add New'}</button></div></form>
 {rows[0]&&<section className="grid gap-3 sm:grid-cols-3"><Summary label="Current Status" value={String(rows[0].derived_status??rows[0].status??'ACTIVE').replaceAll('_',' ')}/><Summary label="Current Reference" value={String(rows[0].reference_number??rows[0].work_type??'—')}/><Summary label="Current Expiry" value={String(rows[0].expiry_date??'Not applicable')}/></section>}
 <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-xl font-bold">History</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search history" className="rounded-xl border px-3 py-2"/></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Reference</th><th className="p-3">Issue</th><th className="p-3">Expiry</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Documents</th><th className="p-3">Action</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3 font-semibold">{String(row.reference_number??row.work_type??row.permit_type??'—')}</td><td className="p-3">{String(row.issue_date??row.process_date??'—')}</td><td className="p-3">{String(row.expiry_date??'—')}</td><td className="p-3">₹{Number(row.amount??0).toFixed(2)}</td><td className="p-3">{String(row.derived_status??row.status??'ACTIVE').replaceAll('_',' ')}</td><td className="p-3">{row.documents?.map(doc=><button key={doc.id} onClick={()=>void vehicleOperationsApi.downloadDocument(vehicleId,doc)} className="block text-blue-700 hover:underline">{doc.original_name}</button>)??'—'}</td><td className="p-3"><div className="flex gap-3"><button onClick={()=>void edit(row)} className="font-semibold text-blue-700">Edit</button><button onClick={()=>confirm('Delete this history record?')&&vehicleOperationsApi.remove(vehicleId,module,row.id).then(load)} className="font-semibold text-red-600">Delete</button></div></td></tr>)}</tbody></table>{visible.length===0&&<p className="p-8 text-center text-slate-500">No records added yet.</p>}</div></section></main>;
}
function Field({name,label,type='text',required=false}:FieldSpec){return <label className="grid gap-1 text-sm font-semibold">{label}<input name={name} type={type} required={required} accept={type==='file'?'.pdf,.jpg,.jpeg,.png':undefined} step={type==='number'?'0.01':undefined} className="rounded-xl border px-3 py-2.5 font-normal"/></label>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-lg font-black">{value}</p></div>}
