'use client';

import { useEffect,useMemo,useState } from 'react';
import { financeControlApi,FinancialYearStatus,OpeningBalanceRow } from '@/lib/finance-control';

const money=(n:number|string|undefined)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export default function AccountsSetupPage(){
 const[rows,setRows]=useState<OpeningBalanceRow[]>([]);const[year,setYear]=useState<FinancialYearStatus|null>(null);const[fyStart,setFyStart]=useState(()=>{const d=new Date();const y=d.getMonth()+1>=4?d.getFullYear():d.getFullYear()-1;return `${y}-04-01`});const[search,setSearch]=useState('');const[msg,setMsg]=useState('');const[error,setError]=useState('');
 async function load(){setError('');try{const[r,y]=await Promise.all([financeControlApi.openingBalances(),financeControlApi.yearStatus(fyStart)]);setRows(r);setYear(y)}catch(e){setError(e instanceof Error?e.message:'Account setup could not load.')}}
 useEffect(()=>{void load()},[fyStart]);
 const filtered=useMemo(()=>rows.filter(r=>!search||r.ledger_name.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 async function save(r:OpeningBalanceRow,value:string,type:'debit'|'credit'){setError('');setMsg('');try{await financeControlApi.updateOpening(r.id,{opening_balance:Number(value||0),balance_type:type,fy_start:fyStart});setMsg(`${r.ledger_name} opening balance updated.`);await load()}catch(e){setError(e instanceof Error?e.message:'Opening balance could not save.')}}
 async function toggleLock(){if(!year)return;const text=year.locked?'UNLOCK':'LOCK';if(!confirm(`${text} financial year ${year.fy_start} to ${year.fy_end}?`))return;try{year.locked?await financeControlApi.unlockYear(fyStart):await financeControlApi.lockYear(fyStart);await load();setMsg(year.locked?'Financial year unlocked.':'Financial year locked.')}catch(e){setError(e instanceof Error?e.message:'Year status could not change.')}}
 return <main className="min-h-screen bg-[#f3f7fc] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1400px] space-y-5">
  <section className="rounded-[30px] bg-gradient-to-br from-[#07172f] via-[#0d3474] to-[#2167df] p-7 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.22em] text-cyan-200">Year Setup</p><h1 className="mt-2 text-4xl font-black">Opening Balance & Year Lock</h1><p className="mt-2 max-w-3xl text-sm text-blue-100/80">Set the correct starting balances once, then lock a completed financial year so old figures cannot change accidentally.</p></section>
  {(msg||error)&&<div className={`rounded-2xl border p-4 font-bold ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||msg}</div>}
  <section className="grid gap-4 lg:grid-cols-[1fr_1.4fr]">
   <div className="rounded-[24px] border border-[#dbe6f3] bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wider text-blue-500">Financial Year</p><label className="mt-3 block text-sm font-black text-slate-600">Year starting<input type="date" value={fyStart} onChange={e=>setFyStart(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 p-3 font-bold"/></label>{year&&<div className="mt-4 rounded-2xl bg-[#f8fbff] p-4"><p className="text-sm font-black text-[#0b2d61]">{year.fy_start} → {year.fy_end}</p><p className={`mt-2 inline-flex rounded-full px-3 py-1 text-xs font-black ${year.locked?'bg-rose-100 text-rose-700':'bg-emerald-100 text-emerald-700'}`}>{year.locked?'LOCKED':'OPEN'}</p><p className="mt-3 text-xs leading-relaxed text-slate-500">When locked, new cash/bank entries and opening-balance changes for this year are blocked.</p><button onClick={toggleLock} className={`mt-4 w-full rounded-2xl px-4 py-3 font-black text-white ${year.locked?'bg-amber-500':'bg-[#0b2f6b]'}`}>{year.locked?'Unlock Year':'Close & Lock Year'}</button></div>}</div>
   <div className="rounded-[24px] border border-[#dbe6f3] bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wider text-blue-500">Year-end checklist</p><h2 className="mt-1 text-xl font-black text-[#0b2d61]">Before you lock the year</h2><div className="mt-4 space-y-2 text-sm font-semibold text-slate-600">{['Cash and bank balances checked','Customer/party receivables checked','Agent/vendor payables checked','Insurance commission due checked','Profit & Loss reviewed','Balance Sheet difference reviewed','PDF/Excel copies saved'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-100 text-xs font-black text-blue-700">{i+1}</span>{x}</div>)}</div></div>
  </section>
  <section className="overflow-hidden rounded-[26px] border border-[#dbe6f3] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-xl font-black text-[#0b2d61]">Opening Balances</h2><p className="mt-1 text-xs text-slate-500">Use only actual closing balances brought forward from the previous year.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search account…" className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold"/></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-[#f8fbff] text-left text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="p-4">Account</th><th className="p-4">Group</th><th className="p-4">Opening</th><th className="p-4">Type</th><th className="p-4">Save</th></tr></thead><tbody>{filtered.map(r=><OpeningRow key={`${r.id}-${r.opening_balance}-${r.balance_type}`} row={r} disabled={!!year?.locked} onSave={save}/>)}</tbody></table></div></section>
 </div></main>
}
function OpeningRow({row,disabled,onSave}:{row:OpeningBalanceRow;disabled:boolean;onSave:(r:OpeningBalanceRow,v:string,t:'debit'|'credit')=>void}){const[v,setV]=useState(String(row.opening_balance||0));const[t,setT]=useState<'debit'|'credit'>(row.balance_type);return <tr className="border-t"><td className="p-4 font-black text-[#123b78]">{row.ledger_name}</td><td className="p-4 text-slate-500">{row.ledger_group}</td><td className="p-4"><input disabled={disabled} value={v} onChange={e=>setV(e.target.value)} type="number" min="0" step="0.01" className="w-36 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 font-bold disabled:opacity-50"/></td><td className="p-4"><select disabled={disabled} value={t} onChange={e=>setT(e.target.value as 'debit'|'credit')} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 font-bold disabled:opacity-50"><option value="debit">To Receive / Asset (Dr)</option><option value="credit">To Pay / Liability (Cr)</option></select></td><td className="p-4"><button disabled={disabled} onClick={()=>onSave(row,v,t)} className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Save</button></td></tr>}
