"use client";

import Link from "next/link";
import { Suspense, useCallback, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { VehicleTable } from "@/components/vehicles/VehicleTable";
import { Vehicle, VehiclePagination, vehicleApi } from "@/lib/vehicles";

export default function VehiclesPage(){return <Suspense fallback={<VehicleSkeleton/>}><VehiclesContent/></Suspense>}

function VehiclesContent(){
 const searchParams=useSearchParams(); const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [meta,setMeta]=useState<VehiclePagination>(); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [reload,setReload]=useState(0);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const query=searchParams.toString();const result=await vehicleApi.list(query?`?${query}`:"");setVehicles(result.data??[]);setMeta(result.meta??(result.current_page!==undefined?{current_page:result.current_page,last_page:result.last_page??1,per_page:result.per_page??result.data.length,total:result.total??result.data.length}:undefined));}catch(caught){setError(caught instanceof Error?caught.message:"Vehicles could not be loaded.");}finally{setLoading(false)}},[searchParams]);
 useEffect(()=>{void load()},[load,reload]);
 const filtered=Boolean(searchParams.get("search")||searchParams.get("fuel_type"));
 return <main className="min-h-screen bg-[#f4f7fc] p-3 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1680px] space-y-5"><header className="relative overflow-hidden rounded-[30px] border border-[#183e7a] bg-[#071a3d] p-5 text-white shadow-[0_26px_80px_rgba(7,26,61,.20)] sm:p-7 lg:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_88%_18%,rgba(65,135,255,.42),transparent_28%),radial-gradient(circle_at_78%_120%,rgba(20,105,255,.55),transparent_34%),linear-gradient(125deg,#06142d,#0a2557_56%,#0e3d8f)]"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/15 bg-cyan-300/8 px-3 py-1.5 text-[9px] font-black uppercase tracking-[.22em] text-cyan-300"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300"/>Vehicle operations</div><h1 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">Vehicle Master</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-100/70">A clean control room for vehicles, owners, insurance, compliance and RTO work.</p><div className="mt-5 flex flex-wrap gap-2 text-[10px] font-bold text-blue-100/80"><span className="rounded-full border border-white/10 bg-white/8 px-3 py-1.5">{meta?.total ?? vehicles.length} vehicles</span><span className="rounded-full border border-white/10 bg-white/8 px-3 py-1.5">Live records</span><span className="rounded-full border border-white/10 bg-white/8 px-3 py-1.5">Search • Filter • Export</span></div></div><Link href="/vehicles/new" className="group inline-flex h-14 items-center justify-center gap-2 rounded-2xl bg-white px-6 font-black text-[#0b2c65] shadow-[0_14px_34px_rgba(0,0,0,.16)] transition hover:-translate-y-0.5 hover:shadow-[0_18px_40px_rgba(0,0,0,.20)] focus:outline-none focus:ring-4 focus:ring-cyan-300/30"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-50 text-lg text-blue-700 transition group-hover:bg-blue-100">+</span>Add Vehicle</Link></div></header>
 {error?<section className="rounded-[24px] border border-rose-200 bg-rose-50 p-6 text-rose-700"><h2 className="font-black">Vehicles could not be loaded</h2><p className="mt-1 text-sm">{error}</p><button onClick={()=>setReload(value=>value+1)} className="mt-4 rounded-xl bg-rose-700 px-4 py-2.5 text-sm font-bold text-white">Retry</button></section>:loading&&!vehicles.length?<VehicleSkeleton/>:!vehicles.length?<section className="rounded-[28px] border border-dashed border-slate-300 bg-white p-12 text-center shadow-sm"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-2xl">🚘</div><h2 className="mt-4 text-xl font-black">{filtered?"No matching vehicles":"No vehicles yet"}</h2><p className="mt-2 text-sm text-slate-500">{filtered?"Clear or change the current filters.":"Add the first vehicle to begin managing compliance and insurance."}</p>{!filtered&&<Link href="/vehicles/new" className="mt-5 inline-flex rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">Add Vehicle</Link>}</section>:<VehicleTable vehicles={vehicles} meta={meta} loading={loading} onChanged={()=>setReload(value=>value+1)}/>} </div></main>
}
function VehicleSkeleton(){return <main className="mx-auto max-w-[1680px] space-y-4 p-4 sm:p-6 lg:p-8"><div className="h-52 animate-pulse rounded-[30px] bg-slate-200"/><div className="rounded-[28px] border bg-white p-5">{Array.from({length:6}).map((_,index)=><div key={index} className="mb-3 h-20 animate-pulse rounded-2xl bg-slate-100"/>)}</div></main>}
