"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { PolicyRow, policyApi } from "@/lib/policies";
import { vehicleInsuranceApi } from "@/lib/vehicle-insurance";

const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(value||0));
export default function PolicyDetail(){const {policyId}=useParams<{policyId:string}>(),router=useRouter();const [policy,setPolicy]=useState<PolicyRow|null>(null),[error,setError]=useState(""),[cancel,setCancel]=useState(false),[saving,setSaving]=useState(false);useEffect(()=>{policyApi.get(policyId).then(setPolicy).catch(e=>setError(e instanceof Error?e.message:"Policy could not load."))},[policyId]);if(error)return <main className="p-6 text-rose-700">{error}</main>;if(!policy)return <main className="p-6">Loading policy...</main>;
async function remove(){if(!confirm("Delete this policy permanently? This is only allowed when no financial, claim, payment or document records are linked."))return;setSaving(true);try{await vehicleInsuranceApi.remove(policy!.vehicle_id,policy!.id);router.push("/policies");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}finally{setSaving(false)}}
async function archive(){setSaving(true);try{await vehicleInsuranceApi.archive(policy!.vehicle_id,policy!.id);router.push("/policies");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Archive failed.")}finally{setSaving(false)}}
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);try{const updated=await vehicleInsuranceApi.cancel(policy!.vehicle_id,policy!.id,{cancellation_date:String(form.get("date")),cancellation_reason:String(form.get("reason")),refund_amount:Number(form.get("refund")||0),cancellation_charges:Number(form.get("charges")||0),confirmed:form.get("confirmed")==="on"});setPolicy({...policy!,...updated});setCancel(false)}catch(e){setError(e instanceof Error?e.message:"Cancellation failed.")}finally{setSaving(false)}}
return <main className="space-y-6 p-6"><header className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-black tracking-[.2em] text-blue-300">POLICY DETAIL</p><h1 className="mt-2 text-3xl font-black">{policy.policy_number}</h1><p className="mt-2 text-slate-300">{policy.company_name} · {policy.vehicle_number}</p><div className="mt-5 flex flex-wrap gap-2"><Link href={`/vehicles/${policy.vehicle_id}/insurance`} className="rounded-xl bg-white px-4 py-2 font-bold text-slate-900">Edit</Link>{policy.status!=="cancelled"&&<button onClick={()=>setCancel(true)} className="rounded-xl bg-amber-500 px-4 py-2 font-bold text-slate-950">Cancel Policy</button>}<button disabled={saving} onClick={()=>void archive()} className="rounded-xl border border-white/30 px-4 py-2">Archive</button><button disabled={saving} onClick={()=>void remove()} className="rounded-xl bg-rose-700 px-4 py-2 font-bold">Delete Policy</button></div></header><section className="grid gap-4 md:grid-cols-3">{[["Status",policy.status],["Issue Date",String(policy.issue_date).slice(0,10)],["Expiry Date",String(policy.expiry_date).slice(0,10)],["Premium",money(policy.gross_premium)],["Gross Commission",money(policy.gross_commission)],["TDS",money(policy.tds_amount??0)]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>)}</section>{cancel&&<div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6"><h2 className="text-xl font-black">Cancel Policy</h2><input required name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="w-full rounded-xl border p-3"/><textarea required name="reason" placeholder="Cancellation reason" className="min-h-24 w-full rounded-xl border p-3"/><div className="grid grid-cols-2 gap-3"><input name="refund" type="number" min="0" step=".01" placeholder="Refund amount" className="rounded-xl border p-3"/><input name="charges" type="number" min="0" step=".01" placeholder="Cancellation charges" className="rounded-xl border p-3"/></div><label className="flex gap-2"><input required name="confirmed" type="checkbox"/>Confirm cancellation and reversal</label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setCancel(false)} className="rounded-xl border px-4 py-2">Close</button><button disabled={saving} className="rounded-xl bg-rose-700 px-4 py-2 font-bold text-white">Confirm</button></div></form></div>}</main>}
