"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { PolicyRow, policyApi } from "@/lib/policies";
import { vehicleInsuranceApi } from "@/lib/vehicle-insurance";

const money = (value:number) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR" }).format(Number(value || 0));
const humanize = (value:string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function PoliciesPage() {
  const [rows,setRows]=useState<PolicyRow[]>([]), [search,setSearch]=useState(""), [status,setStatus]=useState(""), [page,setPage]=useState(1), [pages,setPages]=useState(1), [total,setTotal]=useState(0);
  const [loading,setLoading]=useState(true), [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const query=new URLSearchParams({page:String(page),per_page:"20"});if(search)query.set("search",search);if(status)query.set("status",status);const result=await policyApi.list(query);setRows(result.data);setPages(Math.max(1,result.last_page));setTotal(result.total)}catch(caught){setError(caught instanceof Error?caught.message:"Policies could not load.")}finally{setLoading(false)}},[page,search,status]);
  useEffect(()=>{void load()},[load]); useEffect(()=>setPage(1),[search,status]);
  async function remove(row:PolicyRow){if(!confirm(`Delete policy ${row.policy_number}?`))return;setError("");try{await vehicleInsuranceApi.remove(row.vehicle_id,row.id);await load()}catch(caught){setError(caught instanceof Error?caught.message:"Policy could not be deleted.")}}
  return <main className="space-y-5 p-4 md:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Policies</h1><p className="text-slate-500">{total} tenant policies with live premium and commission values.</p></div><Link href="/vehicles" className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">Select Vehicle to Add Policy</Link></header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
  <section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_240px]"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search policy, company, vehicle or customer" className="rounded-xl border px-4 py-3"/><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="">All statuses</option><option value="running">Running</option><option value="pending">Pending</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></section>
  <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Policy","Vehicle / Customer","Company","Type","Dates","Premium","Gross Commission","TDS","Status","Actions"].map(title=><th key={title} className="p-4">{title}</th>)}</tr></thead><tbody>{loading&&<tr><td colSpan={10} className="p-10 text-center text-slate-500">Loading policies...</td></tr>}{!loading&&!rows.length&&<tr><td colSpan={10} className="p-10 text-center text-slate-500">No policies found.</td></tr>}{rows.map(row=><tr key={row.id} className="border-t"><td className="p-4 font-bold">{row.policy_number}</td><td><Link className="font-semibold text-blue-700" href={`/vehicles/${row.vehicle_id}`}>{row.vehicle_number}</Link><p className="text-xs text-slate-500">{`${row.first_name??""} ${row.last_name??""}`.trim()||"—"}</p></td><td>{row.company_name}</td><td>{humanize(row.insurance_type)}</td><td>{String(row.issue_date).slice(0,10)}<br/><span className="text-xs text-slate-500">to {String(row.expiry_date).slice(0,10)}</span></td><td>{money(row.gross_premium)}</td><td>{money(row.gross_commission)}</td><td>{money(row.tds_amount??0)}</td><td>{humanize(row.status)}</td><td><div className="flex gap-2"><Link href={`/vehicles/${row.vehicle_id}/insurance`} className="rounded-lg border px-3 py-2">Edit</Link><button onClick={()=>void remove(row)} className="rounded-lg border border-red-200 px-3 py-2 text-red-700">Delete</button></div></td></tr>)}</tbody></table></section>
  <div className="flex items-center justify-between"><button disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Previous</button><span className="text-sm text-slate-500">Page {page} of {pages}</span><button disabled={page>=pages||loading} onClick={()=>setPage(value=>value+1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Next</button></div></main>;
}
