"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { PolicyRow, policyApi } from "@/lib/policies";
import { vehicleInsuranceApi } from "@/lib/vehicle-insurance";

const money = (value:number) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR" }).format(Number(value || 0));
const humanize = (value:string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export default function PoliciesPage() {
  const [rows,setRows]=useState<PolicyRow[]>([]), [search,setSearch]=useState(""), [status,setStatus]=useState(""), [page,setPage]=useState(1), [pages,setPages]=useState(1), [total,setTotal]=useState(0);
  const [loading,setLoading]=useState(true), [error,setError]=useState(""), [success,setSuccess]=useState(""), [mutating,setMutating]=useState(false), [cancelRow,setCancelRow]=useState<PolicyRow|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const query=new URLSearchParams({page:String(page),per_page:"20"});if(search)query.set("search",search);if(status)query.set("status",status);const result=await policyApi.list(query);setRows(result.data);setPages(Math.max(1,result.last_page));setTotal(result.total)}catch(caught){setError(caught instanceof Error?caught.message:"Policies could not load.")}finally{setLoading(false)}},[page,search,status]);
  useEffect(()=>{void load()},[load]); useEffect(()=>setPage(1),[search,status]);
  async function remove(row:PolicyRow){if(!confirm("Delete this policy permanently? This is only allowed when no financial, claim, payment or document records are linked."))return;setError("");setSuccess("");setMutating(true);try{await vehicleInsuranceApi.remove(row.vehicle_id,row.id);setSuccess("Policy deleted successfully.");await load()}catch(caught){setError(caught instanceof Error?caught.message:"Policy could not be deleted.")}finally{setMutating(false)}}
  async function archive(row:PolicyRow){if(!confirm(`Archive policy ${row.policy_number}?`))return;setError("");setMutating(true);try{await vehicleInsuranceApi.archive(row.vehicle_id,row.id);setSuccess("Policy archived successfully.");await load()}catch(caught){setError(caught instanceof Error?caught.message:"Policy could not be archived.")}finally{setMutating(false)}}
  async function cancel(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!cancelRow||mutating)return;setMutating(true);setError("");const data=new FormData(event.currentTarget);try{await vehicleInsuranceApi.cancel(cancelRow.vehicle_id,cancelRow.id,{cancellation_date:String(data.get("cancellation_date")),cancellation_reason:String(data.get("cancellation_reason")),refund_amount:Number(data.get("refund_amount")||0),cancellation_charges:Number(data.get("cancellation_charges")||0),confirmed:data.get("confirmed")==="on"});setCancelRow(null);setSuccess("Policy cancelled successfully and reversal recorded.");await load()}catch(caught){setError(caught instanceof Error?caught.message:"Policy could not be cancelled.")}finally{setMutating(false)}}
  return <main className="space-y-5 p-4 md:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Policies</h1><p className="text-slate-500">{total} tenant policies with live premium and commission values.</p></div><Link href="/vehicles" className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">Select Vehicle to Add Policy</Link></header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{success}</div>}
  <section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_240px]"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search policy, company, vehicle or customer" className="rounded-xl border px-4 py-3"/><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="">Active policies</option>{["draft","running","pending","expired","cancelled","archived"].map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></section>
  <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Policy","Vehicle / Customer","Company","Type","Dates","Premium","Gross Commission","TDS","Status","Actions"].map(title=><th key={title} className="p-4">{title}</th>)}</tr></thead><tbody>{loading&&<tr><td colSpan={10} className="p-10 text-center text-slate-500">Loading policies...</td></tr>}{!loading&&!rows.length&&<tr><td colSpan={10} className="p-10 text-center text-slate-500">No policies found.</td></tr>}{rows.map(row=><tr key={row.id} className="border-t"><td className="p-4 font-bold">{row.policy_number}</td><td><Link className="font-semibold text-blue-700" href={`/vehicles/${row.vehicle_id}`}>{row.vehicle_number}</Link><p className="text-xs text-slate-500">{`${row.first_name??""} ${row.last_name??""}`.trim()||"—"}</p></td><td>{row.company_name}</td><td>{humanize(row.insurance_type)}</td><td>{String(row.issue_date).slice(0,10)}<br/><span className="text-xs text-slate-500">to {String(row.expiry_date).slice(0,10)}</span></td><td>{money(row.gross_premium)}</td><td>{money(row.gross_commission)}</td><td>{money(row.tds_amount??0)}</td><td>{humanize(row.archived_at?"archived":row.status)}</td><td><div className="flex flex-wrap gap-2"><Link href={`/policies/${row.id}`} className="rounded-lg border px-3 py-2">View</Link><Link href={`/vehicles/${row.vehicle_id}/insurance`} className="rounded-lg border px-3 py-2">Edit</Link>{row.status!=="cancelled"&&!row.archived_at&&<button disabled={mutating} onClick={()=>setCancelRow(row)} className="rounded-lg border border-amber-300 px-3 py-2 text-amber-800">Cancel Policy</button>}{!row.archived_at&&<button disabled={mutating} onClick={()=>void archive(row)} className="rounded-lg border px-3 py-2">Archive</button>}<button disabled={mutating} onClick={()=>void remove(row)} className="rounded-lg border border-red-200 px-3 py-2 text-red-700">Delete Policy</button></div></td></tr>)}</tbody></table></section>
  <div className="flex items-center justify-between"><button disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Previous</button><span className="text-sm text-slate-500">Page {page} of {pages}</span><button disabled={page>=pages||loading} onClick={()=>setPage(value=>value+1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Next</button></div>{cancelRow&&<CancellationModal policy={cancelRow} saving={mutating} close={()=>setCancelRow(null)} submit={cancel}/>}</main>;
}

function CancellationModal({policy,saving,close,submit}:{policy:PolicyRow;saving:boolean;close:()=>void;submit:(event:FormEvent<HTMLFormElement>)=>void}){return <div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">Cancel Policy {policy.policy_number}</h2><label className="block text-sm font-semibold">Cancellation Date<input required name="cancellation_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-semibold">Cancellation Reason<textarea required name="cancellation_reason" className="mt-2 min-h-24 w-full rounded-xl border px-4 py-3"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Refund Amount<input name="refund_amount" type="number" min="0" step="0.01" defaultValue="0" className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-semibold">Cancellation Charges<input name="cancellation_charges" type="number" min="0" step="0.01" defaultValue="0" className="mt-2 w-full rounded-xl border px-4 py-3"/></label></div><label className="flex items-start gap-2 text-sm"><input required name="confirmed" type="checkbox" className="mt-1"/>I confirm cancellation and creation of reversal records.</label><div className="flex justify-end gap-2"><button type="button" disabled={saving} onClick={close} className="rounded-xl border px-5 py-3">Close</button><button disabled={saving} className="rounded-xl bg-rose-700 px-5 py-3 font-bold text-white">{saving?"Cancelling...":"Cancel Policy"}</button></div></form></div>}
