"use client";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
import { Icon } from "@/components/dashboard/Icon";
import { DashboardPeriod,DashboardSummary,getDashboardSummary } from "@/lib/dashboard-api";
import { DASHBOARD_REFRESH_EVENT } from "@/lib/dashboard-refresh";
import { DASHBOARD_PERIODS,dashboardPeriodLabel } from "@/lib/dashboard-periods";

const money=(v=0)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
const num=(v=0)=>v.toLocaleString("en-IN");

const operationActions=[
 {label:"New Vehicle",hint:"Register vehicle",href:"/vehicles/new",icon:"vehicle"},
 {label:"New Customer",hint:"Add customer",href:"/customers/new",icon:"customers"},
 {label:"Insurance",hint:"Policy work",href:"/policies",icon:"shield"},
 {label:"RTO Work",hint:"RTO services",href:"/vehicles",icon:"building"},
 {label:"Driving Licence",hint:"Licence work",href:"/services/driving-licence",icon:"book"},
 {label:"Passport",hint:"Passport work",href:"/services/passport",icon:"book"},
] as const;

const financeActions=[
 {label:"Receive / Pay",hint:"Cash & bank entry",href:"/accounts/cash-bank",icon:"credit"},
 {label:"Party Balance",hint:"To receive / pay",href:"/accounts/outstanding",icon:"wallet"},
 {label:"Accounts",hint:"Daily accounts",href:"/accounts",icon:"book"},
 {label:"Profit & Loss",hint:"Yearly profit",href:"/reports/profit-loss",icon:"reports"},
 {label:"Balance Sheet",hint:"Financial position",href:"/reports/balance-sheet",icon:"book"},
 {label:"Reports",hint:"Insurance & RTO",href:"/reports",icon:"reports"},
] as const;

export default function DashboardPage(){
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date());
 const[data,setData]=useState<DashboardSummary>(); const[error,setError]=useState(""); const[refreshing,setRefreshing]=useState(false); const[period,setPeriod]=useState<DashboardPeriod>("today"); const[dateFrom,setDateFrom]=useState(today); const[dateTo,setDateTo]=useState(today); const req=useRef<AbortController|null>(null);
 const refresh=useCallback(()=>{if(period==="custom"&&(!dateFrom||!dateTo||dateFrom>dateTo)){setError("Select a valid date range.");return Promise.resolve();} req.current?.abort();const c=new AbortController();req.current=c;setRefreshing(true);setError("");return getDashboardSummary({period,dateFrom,dateTo},c.signal).then(setData).catch(e=>{if(e instanceof DOMException&&e.name==="AbortError")return;if(e instanceof Error&&e.message==="AUTH_REQUIRED"){sessionStorage.removeItem("raj_erp_token");location.replace("/login?next=/dashboard");return;}setError(e instanceof Error?e.message:"Dashboard could not refresh.");}).finally(()=>{if(req.current===c){setRefreshing(false);req.current=null;}})},[period,dateFrom,dateTo]);
 useEffect(()=>{void refresh();const r=()=>void refresh();window.addEventListener("focus",r);window.addEventListener(DASHBOARD_REFRESH_EVENT,r);return()=>{req.current?.abort();window.removeEventListener("focus",r);window.removeEventListener(DASHBOARD_REFRESH_EVENT,r)}},[refresh]);
 const work=Object.entries(data?.work??{}).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]); const vehicles=data?.kpis.vehicles?.value??0; const policies=data?.kpis.active_policies?.value??0; const due=data?.kpis.expiring_policies?.value??0; const outstanding=data?.kpis.outstanding_amount?.value??0; const totalWork=work.reduce((s,[,v])=>s+v,0);
 return <main className="min-h-screen bg-[#f4f7fb] pb-10 dark:bg-[#050914]"><div className="mx-auto max-w-[1560px] space-y-5 p-4 sm:p-6 lg:p-7">
  <section className="relative overflow-hidden rounded-[28px] bg-[#071a3c] text-white shadow-[0_28px_70px_-32px_rgba(7,26,60,.8)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_88%_4%,rgba(46,116,255,.5),transparent_29%),linear-gradient(120deg,#06142e_0%,#082255_60%,#144fc8_100%)]"/><div className="absolute right-[-90px] top-[-145px] h-80 w-80 rounded-full border border-white/10"/><div className="relative p-6 sm:p-7">
   <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_14px_rgba(103,232,249,.8)]"/><p className="text-[9px] font-black uppercase tracking-[.24em] text-cyan-200">Raj Insurance ERP · Command Center</p></div><h1 className="mt-2 text-3xl font-black tracking-[-.045em] sm:text-[42px]">Business at a glance</h1><p className="mt-2 max-w-2xl text-sm font-medium text-blue-100/65">Insurance, RTO, licence, passport and accounts — only the numbers that need your attention.</p></div><div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/[.07] p-1.5"><span className="px-3 text-[10px] font-black uppercase tracking-[.14em] text-blue-100/60">Period</span><select value={period} onChange={e=>setPeriod(e.target.value as DashboardPeriod)} className="rounded-xl border-0 bg-white px-3 py-2 text-xs font-black text-[#0b2b62] outline-none">{DASHBOARD_PERIODS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><button onClick={()=>void refresh()} disabled={refreshing} className="rounded-xl bg-blue-500 px-3 py-2 text-xs font-black text-white transition hover:bg-blue-400 disabled:opacity-50">{refreshing?"…":"Refresh"}</button></div></div>
   {period==="custom"&&<div className="mt-4 flex max-w-md gap-2"><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.09] px-3 py-2.5 text-xs font-bold text-white outline-none"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.09] px-3 py-2.5 text-xs font-bold text-white outline-none"/></div>}
   <div className="mt-6 grid overflow-hidden rounded-2xl border border-white/10 bg-black/[.12] sm:grid-cols-2 lg:grid-cols-4"><Metric label="Vehicles" value={num(vehicles)} icon="vehicle"/><Metric label="Active Policies" value={num(policies)} icon="shield"/><Metric label="Renewal Due" value={num(due)} icon="clock" alert={due>0}/><Metric label="Outstanding" value={money(outstanding)} icon="wallet" alert={outstanding>0} last/></div>
  </div></section>

  {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}

  <section className="grid gap-4 xl:grid-cols-2">
   <ActionPanel eyebrow="Daily work" title="Quick actions" subtitle="Most-used Insurance & RTO actions" items={operationActions}/>
   <ActionPanel eyebrow="Money & control" title="Accounts shortcuts" subtitle="Simple entries and yearly control" items={financeActions}/>
  </section>

  <section className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
   <article className="overflow-hidden rounded-[26px] border border-[#dce6f4] bg-white shadow-[0_16px_45px_rgba(24,59,110,.07)] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-6 dark:border-slate-800"><div><div className="flex items-center gap-2"><span className="rounded-lg bg-blue-50 px-2 py-1 text-[9px] font-black uppercase tracking-[.18em] text-blue-700">Priority queue</span><span className="text-[10px] font-bold text-slate-400">Pending compliance work</span></div><h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950 dark:text-white">Today&apos;s work</h2></div><div className="text-right"><p className="text-3xl font-black tracking-tight text-[#0a2b64] dark:text-blue-300">{totalWork}</p><p className="text-[9px] font-black uppercase tracking-wider text-slate-400">Open items</p></div></div>
   <div className="p-3 sm:p-4">{work.length?<div className="grid gap-2 md:grid-cols-2">{work.slice(0,8).map(([label,value],index)=><Link href="/vehicles" key={label} className="group grid grid-cols-[42px_1fr_auto] items-center gap-3 rounded-2xl border border-slate-100 bg-[#f8fafc] px-3 py-3 transition hover:border-blue-200 hover:bg-blue-50/70 dark:border-slate-800 dark:bg-slate-950/40"><span className={`grid h-10 w-10 place-items-center rounded-xl ${index===0?"bg-[#0b2b62] text-white":"bg-white text-blue-700 ring-1 ring-slate-100 dark:bg-slate-900 dark:ring-slate-800"}`}><Icon name={index%2===0?"clock":"building"} className="h-4 w-4"/></span><span className="min-w-0"><span className="block truncate text-sm font-black capitalize text-slate-900 dark:text-white">{label.replaceAll("_"," ")}</span><span className="block text-[10px] font-semibold text-slate-400">Review pending work</span></span><b className="text-lg font-black text-[#0b2b62] dark:text-blue-300">{value}</b></Link>)}</div>:<div className="grid min-h-52 place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><Icon name="shield" className="h-6 w-6"/></div><p className="mt-4 text-base font-black text-slate-900 dark:text-white">Work queue clear</p><p className="mt-1 text-xs text-slate-400">Nothing needs attention in this period.</p></div></div>}</div></article>

   <aside className="space-y-4"><div className="rounded-[26px] border border-[#dce6f4] bg-white p-5 shadow-[0_16px_45px_rgba(24,59,110,.06)] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Business snapshot</p><h2 className="mt-1 text-2xl font-black text-slate-950 dark:text-white">{dashboardPeriodLabel(period)}</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300"><Icon name="reports" className="h-4 w-4"/></span></div><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Pending Work" value={num(totalWork)}/><Mini label="Renewal Due" value={num(due)}/><Mini label="Policies" value={num(policies)}/><Mini label="Receivable" value={money(outstanding)}/></div><div className="mt-4 grid grid-cols-2 gap-2"><Link href="/accounts" className="rounded-xl bg-[#0b2b62] px-3 py-3 text-center text-xs font-black text-white">Open Accounts</Link><Link href="/reports" className="rounded-xl border border-slate-200 px-3 py-3 text-center text-xs font-black text-slate-700 hover:border-blue-300 hover:text-blue-700 dark:border-slate-700 dark:text-slate-200">Open Reports</Link></div></div>
   <div className="rounded-[26px] bg-[#081b3f] p-5 text-white shadow-[0_18px_45px_rgba(8,27,63,.16)]"><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-300">Year-end control</p><h3 className="mt-2 text-xl font-black">Keep accounts simple</h3><p className="mt-2 text-xs font-medium leading-5 text-blue-100/65">Daily team only records money received, paid and expenses. Profit & Loss and Balance Sheet stay ready in the background.</p><Link href="/accounts/cash-bank" className="mt-4 flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-xs font-black hover:bg-white/15"><span>Record cash / bank entry</span><span>→</span></Link></div>
   </aside>
  </section>
 </div></main>
}

function ActionPanel({eyebrow,title,subtitle,items}:{eyebrow:string;title:string;subtitle:string;items:readonly {label:string;hint:string;href:string;icon:string}[]}){return <article className="rounded-[26px] border border-[#dce6f4] bg-white p-5 shadow-[0_16px_45px_rgba(24,59,110,.06)] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-end justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">{eyebrow}</p><h2 className="mt-1 text-xl font-black text-slate-950 dark:text-white">{title}</h2><p className="mt-1 text-xs font-semibold text-slate-400">{subtitle}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><Link href={item.href} key={item.label} className="group flex min-h-[76px] items-center gap-3 rounded-2xl border border-slate-100 bg-[#f8fafc] p-3 transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50/70 dark:border-slate-800 dark:bg-slate-950/40"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-[#0b2b62] shadow-sm ring-1 ring-slate-100 transition group-hover:bg-[#0b2b62] group-hover:text-white dark:bg-slate-900 dark:ring-slate-800 dark:text-blue-300"><Icon name={item.icon} className="h-4 w-4"/></span><span className="min-w-0"><b className="block truncate text-sm font-black text-slate-900 dark:text-white">{item.label}</b><span className="mt-0.5 block truncate text-[10px] font-semibold text-slate-400">{item.hint}</span></span><span className="ml-auto text-blue-500 opacity-0 transition group-hover:opacity-100">→</span></Link>)}</div></article>}
function Metric({label,value,icon,alert=false,last=false}:{label:string;value:string;icon:string;alert?:boolean;last?:boolean}){return <div className={`flex items-center gap-3 p-4 sm:p-5 ${last?"":"border-b border-white/10 sm:border-b-0 sm:border-r"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${alert?"bg-amber-300/15 text-amber-200":"bg-white/10 text-blue-100"}`}><Icon name={icon} className="h-4 w-4"/></span><div className="min-w-0"><p className="text-[9px] font-black uppercase tracking-[.13em] text-blue-100/50">{label}</p><p className="mt-0.5 truncate text-xl font-black tracking-tight text-white sm:text-2xl">{value}</p></div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-100 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-950/40"><p className="text-[8px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 truncate text-lg font-black text-[#0b2b62] dark:text-blue-300">{value}</p></div>}
