'use client';

import type { ReactNode } from 'react';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import PolicyFundingPanel from '@/components/insurance/PolicyFundingPanel';
import {vehicleInsuranceApi,type VehicleInsurancePolicy} from '@/lib/vehicle-insurance';
import {authenticatedRequest} from '@/lib/api-client';

type SettlementInfo={settlement:null|{settlement_type:string;amount:number;payment_date:string}};
const money=(n:number|string|undefined)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=(v?:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
const label=(v?:string)=>String(v||'—').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

export default function InsuranceLayout({children}:{children:ReactNode}){
 const {vehicleId}=useParams<{vehicleId:string}>();
 const[policies,setPolicies]=useState<VehicleInsurancePolicy[]>([]),[loading,setLoading]=useState(true),[showEntry,setShowEntry]=useState(false),[payOpen,setPayOpen]=useState(false),[payPolicy,setPayPolicy]=useState<string>(),[settled,setSettled]=useState<Record<string,boolean>>({});
 const hydrate=useCallback(async(rows:VehicleInsurancePolicy[])=>{setPolicies(rows);const map:Record<string,boolean>={};await Promise.all(rows.filter(p=>p.status!=='cancelled'&&!p.archived_at).map(async p=>{try{const d=await authenticatedRequest<SettlementInfo>(`/vehicles/${vehicleId}/insurances/${p.id}/settlement`);map[p.id]=!!d.settlement}catch{map[p.id]=false}}));setSettled(map)},[vehicleId]);
 const reload=useCallback(async()=>{try{await hydrate(await vehicleInsuranceApi.list(vehicleId))}finally{setLoading(false)}},[vehicleId,hydrate]);
 useEffect(()=>{void reload()},[reload]);
 useEffect(()=>{const saved=(e:Event)=>{const d=(e as CustomEvent<{vehicleId:string;policyId:string}>).detail;if(d?.vehicleId!==vehicleId)return;setPayPolicy(d.policyId);setShowEntry(false);void reload().then(()=>setPayOpen(true))};const paid=(e:Event)=>{const d=(e as CustomEvent<{vehicleId:string}>).detail;if(d?.vehicleId===vehicleId)void reload()};window.addEventListener('raj:policy-saved',saved);window.addEventListener('raj:insurance-payment-saved',paid);return()=>{window.removeEventListener('raj:policy-saved',saved);window.removeEventListener('raj:insurance-payment-saved',paid)}},[vehicleId,reload]);
 const live=useMemo(()=>policies.filter(p=>!p.archived_at&&p.status!=='cancelled'&&p.status!=='expired').sort((a,b)=>String(b.expiry_date).localeCompare(String(a.expiry_date))),[policies]);
 const current=live[0];
 useEffect(()=>{if(loading||(!showEntry&&current))return;const before=new Set(policies.map(p=>p.id));const timer=window.setInterval(async()=>{try{const rows=await vehicleInsuranceApi.list(vehicleId);const created=rows.find(p=>!before.has(p.id));if(!created)return;window.clearInterval(timer);await hydrate(rows);setPayPolicy(created.id);setShowEntry(false);setPayOpen(true)}catch{}},850);return()=>window.clearInterval(timer)},[loading,showEntry,current,policies,vehicleId,hydrate]);
 if(loading)return <main className="p-6 text-sm font-semibold text-slate-500">Loading insurance...</main>;
 if(!current||showEntry)return <><div className="sticky top-0 z-40 flex justify-end bg-white/90 px-4 py-2 backdrop-blur">{current&&<button onClick={()=>setShowEntry(false)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-black text-slate-700 shadow-sm">← Current Policy</button>}</div>{children}<PolicyFundingPanel vehicleId={vehicleId} open={payOpen} defaultPolicyId={payPolicy} onClose={()=>setPayOpen(false)}/></>;
 return <main className="min-h-screen bg-[#f4f7fc] p-3 text-[#071a3c] sm:p-5 md:p-7"><div className="mx-auto max-w-7xl space-y-4">
  <section className="overflow-hidden rounded-[28px] border border-[#153d7b] bg-[radial-gradient(circle_at_92%_0%,rgba(65,132,255,.55),transparent_36%),linear-gradient(135deg,#06152f,#0b2d67_58%,#1558cb)] text-white shadow-[0_22px_65px_rgba(7,26,60,.20)]"><div className="flex flex-col gap-5 p-5 sm:p-7 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-cyan-200">Insurance</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Current Policy</h1><span className="inline-flex items-center gap-2 rounded-full border border-emerald-300/25 bg-emerald-300/12 px-3 py-1 text-[10px] font-black uppercase text-emerald-200"><span className="h-2 w-2 rounded-full bg-emerald-400"/> {current.status||'Running'}</span></div><p className="mt-2 text-sm font-semibold text-blue-100">Policy details stay visible here. Entry form opens only for renewal or a new cover.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setPayPolicy(current.id);setPayOpen(true)}} className={`rounded-2xl px-5 py-3 text-sm font-black shadow-lg ${settled[current.id]?'border border-emerald-300/30 bg-emerald-400/15 text-emerald-100':'bg-white text-[#0b2f6b]'}`}>{settled[current.id]?'✓ Company Payment Done':'₹ Pay Insurance Company'}</button><button onClick={()=>setShowEntry(true)} className="rounded-2xl border border-white/25 bg-white/10 px-5 py-3 text-sm font-black text-white">＋ Add / Renew Policy</button></div></div></section>

  <section className="overflow-hidden rounded-[24px] border border-[#dbe6f4] bg-white shadow-[0_12px_36px_rgba(20,55,105,.07)]">
   <div className="flex flex-col gap-2 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-600">Policy Details</p><h2 className="mt-1 text-xl font-black text-[#081f47]">Complete current policy information</h2></div><span className="w-fit rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-700">{label(current.insurance_type)}</span></div>
   <div className="grid gap-px bg-slate-100 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Insurance Company" value={current.company_name}/><Fact label="Policy Number" value={current.policy_number}/><Fact label="Policy Type" value={label(current.insurance_type)}/><Fact label="Purchase From" value={current.purchase_from||'Direct Company'}/><Fact label="Policy Start" value={date(current.policy_date||current.issue_date)}/><Fact label="Issue Date" value={date(current.issue_date)}/><Fact label="Expiry Date" value={date(current.expiry_date)}/><Fact label="Status" value={label(current.status)}/></div>
   <div className="border-t border-slate-100 p-4 sm:p-5"><p className="mb-3 text-[9px] font-black uppercase tracking-[.18em] text-slate-400">Premium & Tax Breakup</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Status label="OD Premium" value={money(current.od_premium)} tone="slate"/><Status label="TP Premium" value={money(current.tp_premium)} tone="slate"/><Status label="Add-on Premium" value={money(current.addon_premium)} tone="slate"/><Status label="Net Premium" value={money(current.net_premium)} tone="blue"/><Status label="GST" value={`${money(current.gst_amount)}${current.gst_percent?` · ${Number(current.gst_percent)}%`:''}`} tone="slate"/><Status label="Other Charges" value={money(current.other_charges)} tone="slate"/><Status label="Gross Premium" value={money(current.gross_premium)} tone="blue"/><Status label="Customer Discount" value={money(current.customer_discount)} tone="slate"/></div></div>
   <div className="grid gap-px border-t border-slate-100 bg-slate-100 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Customer Pay" value={money(current.customer_pay)}/><Fact label="Commission Basis" value={label(current.commission_basis)}/><Fact label="Commission Rate" value={`${Number(current.commission_percent||0).toFixed(2)}%`}/><Fact label="Gross Commission" value={money(current.gross_commission)}/><Fact label="Sales Agent / Sub-Agent" value={current.agent||'Own Business'}/><Fact label="Agent Commission" value={money(current.agent_commission)}/><Fact label="Company / Agency Code" value={current.company_code||'—'}/><Fact label="Remark" value={current.remark||'—'}/></div>
  </section>

  <section className="overflow-hidden rounded-[24px] border border-[#dbe6f4] bg-white shadow-[0_12px_36px_rgba(20,55,105,.07)]"><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4"><Status label="Customer Pay" value={money(current.customer_pay)} tone="blue"/><Status label="Commission" value={money(current.gross_commission)} tone="blue"/><Status label="Company Payment" value={settled[current.id]?'PAID':'PENDING'} tone={settled[current.id]?'green':'amber'}/><Status label="Customer Recovery" value="Tracked separately" tone="slate"/></div></section>
  {policies.length>1&&<section className="rounded-[22px] border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-500">Policy history</p><h2 className="text-lg font-black">Previous / additional records</h2></div><button onClick={()=>setShowEntry(true)} className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-black text-blue-700">Manage</button></div><div className="grid gap-2">{policies.filter(p=>p.id!==current.id).map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm"><div><b>{p.policy_number}</b><span className="ml-2 text-slate-500">{p.company_name}</span></div><div className="font-bold text-slate-600">{p.status} · {date(p.expiry_date)}</div></div>)}</div></section>}
 </div><PolicyFundingPanel vehicleId={vehicleId} open={payOpen} defaultPolicyId={payPolicy||current.id} onClose={()=>setPayOpen(false)}/></main>
}
function Fact({label,value}:{label:string;value:string}){return <div className="bg-white p-4"><p className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-black text-[#0a2858]">{value||'—'}</p></div>}
function Status({label,value,tone}:{label:string;value:string;tone:'green'|'amber'|'blue'|'slate'}){const c={green:'border-emerald-200 bg-emerald-50 text-emerald-700',amber:'border-amber-200 bg-amber-50 text-amber-700',blue:'border-blue-100 bg-blue-50 text-blue-800',slate:'border-slate-200 bg-slate-50 text-slate-700'}[tone];return <div className={`rounded-2xl border p-3 ${c}`}><p className="text-[8px] font-black uppercase tracking-[.15em] opacity-70">{label}</p><p className="mt-1 text-base font-black">{value}</p></div>}
