'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {Vehicle,vehicleApi} from '@/lib/vehicles';
import {InsuranceCompany,PurchaseSource,insuranceAccountingApi} from '@/lib/insurance-accounting';
import {InsuranceCalculation,VehicleInsurancePolicy,vehicleInsuranceApi} from '@/lib/vehicle-insurance';
import {scanDocument} from '@/lib/ocr';
import {apiUrl} from '@/lib/api-url';

type Purchase={id:string;name:string;active:boolean};
const empty:Record<string,string>={company_id:'',purchase_id:'',purchase_from_type:'direct_company',purchase_source_id:'',policy_number:'',policy_date:'',issue_date:'',expiry_date:'',status:'running',insurance_type:'comprehensive',od_premium:'0',tp_premium:'0',addon_premium:'0',gst_percent:'18',other_charges:'0',has_od_cover:'1',has_tp_cover:'1',commission_basis:'OD_PREMIUM',commission_percent:'0',gross_commission:'0',customer_discount:'0',agent:'',agent_commission:'0',long_term_tp_policy_number:'',long_term_tp_expiry:'',remark:''};
const emptyCalculation:InsuranceCalculation={has_od_cover:true,has_tp_cover:true,od_premium:0,tp_premium:0,addon_premium:0,net_premium:0,gst_percent:18,gst_amount:0,other_charges:0,gross_premium:0,customer_discount:0,customer_pay:0,commission_basis:'OD_PREMIUM',commission_base:0,commission_percent:0,gross_commission:0};
const money=(v:number)=>`₹${Number(v||0).toFixed(2)}`;

export default function Page(){
 const {vehicleId}=useParams<{vehicleId:string}>();const [vehicle,setVehicle]=useState<Vehicle|null>(null),[companies,setCompanies]=useState<InsuranceCompany[]>([]),[sources,setSources]=useState<PurchaseSource[]>([]),[policies,setPolicies]=useState<VehicleInsurancePolicy[]>([]),[form,setForm]=useState({...empty}),[calculation,setCalculation]=useState<InsuranceCalculation>(emptyCalculation),[file,setFile]=useState<File|null>(null),[editing,setEditing]=useState<string>(),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[reading,setReading]=useState(false),[expiryManual,setExpiryManual]=useState(false),[companyModal,setCompanyModal]=useState(false),[sourceModal,setSourceModal]=useState(false),[quickSaving,setQuickSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [purchases,setPurchases]=useState<Purchase[]>([]);
 useEffect(()=>{void(async()=>{try{const [v,c,s,p]=await Promise.all([vehicleApi.get(vehicleId),insuranceAccountingApi.companies(),insuranceAccountingApi.purchaseSources(),vehicleInsuranceApi.list(vehicleId)]);setVehicle(v);setCompanies(c.filter(x=>x.status==='active'));setSources(s.filter(x=>x.is_active));setPolicies(p);setPurchases(JSON.parse(localStorage.getItem('raj_erp_purchase_forms')||'[]'))}catch(e){setError(e instanceof Error?e.message:'Unable to load insurance data')}finally{setLoading(false)}})()},[vehicleId]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!quickSaving){setCompanyModal(false);setSourceModal(false)}};addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[quickSaving]);
 const n=(k:string)=>Number(form[k]||0),set=(k:string,v:string)=>setForm(x=>({...x,[k]:v})),checked=(k:string)=>form[k]==='1';
 useEffect(()=>{if(!vehicle)return;let cancelled=false;const timer=setTimeout(()=>{void vehicleInsuranceApi.calculate(vehicleId,{insurance_type:form.insurance_type,has_od_cover:checked('has_od_cover'),has_tp_cover:checked('has_tp_cover'),od_premium:n('od_premium'),tp_premium:n('tp_premium'),addon_premium:n('addon_premium'),other_charges:n('other_charges'),customer_discount:n('customer_discount'),gst_percent:n('gst_percent')||18,commission_basis:form.commission_basis,commission_percent:n('commission_percent'),manual_commission_amount:n('gross_commission')}).then(value=>{if(!cancelled)setCalculation(value)}).catch(()=>undefined)},200);return()=>{cancelled=true;clearTimeout(timer)}},[vehicle,vehicleId,form]);
 const managedMotor=['private_car','two_wheeler'].includes(vehicle?.vehicle_type||'');
 const years=vehicle?.vehicle_type==='private_car'?3:vehicle?.vehicle_type==='two_wheeler'?5:0;
 const longTerm=useMemo(()=>{if(!years||!vehicle?.registration_date)return false;const d=new Date(vehicle.registration_date);if(isNaN(d.getTime()))return false;d.setFullYear(d.getFullYear()+years);return new Date()<d||!!form.long_term_tp_policy_number||!!form.long_term_tp_expiry},[years,vehicle,form.long_term_tp_policy_number,form.long_term_tp_expiry]);
 function defaults(type:string){setForm(x=>({...x,insurance_type:type,has_od_cover:type==='third_party'?'0':'1',has_tp_cover:type==='standalone_od'?'0':'1',od_premium:type==='third_party'?'0':x.od_premium,tp_premium:type==='standalone_od'?'0':x.tp_premium,commission_basis:managedMotor&&type==='comprehensive'?'OD_PREMIUM':'NET_PREMIUM'}))}
 function policyStart(value:string){setForm(x=>{if(expiryManual||!value)return {...x,policy_date:value};const [year,month,day]=value.split('-').map(Number),next=new Date(year+1,month-1,day);if(Number.isNaN(next.getTime()))return {...x,policy_date:value};next.setDate(next.getDate()-1);const expiry=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-${String(next.getDate()).padStart(2,'0')}`;return {...x,policy_date:value,expiry_date:expiry}})}
 async function ocr(){if(!file)return;setReading(true);setError('');try{const r=await scanDocument('insurance_policy',[file]);let count=0;setForm(old=>{const next={...old};Object.entries(r.fields).forEach(([k,v])=>{if(v&&k in next){next[k]=v;count++}});return next});if(r.fields.insurance_type)defaults(r.fields.insurance_type);const name=r.fields.company_name?.toLowerCase();const c=name&&companies.find(x=>name.includes(x.company_name.toLowerCase())||x.company_name.toLowerCase().includes(name));if(c)set('company_id',c.id);setMessage(`${count} reliable fields extracted. Please verify all values.`)}catch(e){setError(`${e instanceof Error?e.message:'OCR failed'} Manual entry remains available.`)}finally{setReading(false)}}
 async function quickCompany(e:FormEvent<HTMLFormElement>){e.preventDefault();if(quickSaving)return;setQuickSaving(true);setError('');const fd=new FormData(e.currentTarget);try{const created=await insuranceAccountingApi.addCompany({company_name:fd.get('company_name'),short_code:fd.get('short_code'),agency_code_name:fd.get('agency_code_name'),tds_percent:Number(fd.get('tds_percent')||0),default_commission_percent:0,settlement_days:30,contact_person:fd.get('contact_person'),mobile:fd.get('mobile'),email:fd.get('email'),notes:fd.get('notes')});setCompanies(await insuranceAccountingApi.companies());set('company_id',created.id);setCompanyModal(false);setMessage('Insurance company added and selected.')}catch(e){setError(e instanceof Error?e.message:'Company add nahi hui.')}finally{setQuickSaving(false)}}
 async function quickSource(e:FormEvent<HTMLFormElement>){e.preventDefault();if(quickSaving)return;setQuickSaving(true);setError('');const fd=new FormData(e.currentTarget);try{const created=await insuranceAccountingApi.addPurchaseSource({name:fd.get('name'),source_type:fd.get('source_type'),mobile:fd.get('mobile'),email:fd.get('email'),linked_company_id:fd.get('linked_company_id')||null,tds_applicable:false,tds_percent:0,is_active:true,notes:fd.get('notes')});setSources((await insuranceAccountingApi.purchaseSources()).filter(x=>x.is_active));set('purchase_source_id',created.id);setSourceModal(false);setMessage('Purchase source added and selected.')}catch(e){setError(e instanceof Error?e.message:'Purchase source add nahi hua.')}finally{setQuickSaving(false)}}
 async function submit(e:FormEvent){e.preventDefault();setError('');const company=companies.find(x=>x.id===form.company_id),source=sources.find(x=>x.id===form.purchase_source_id);if(!company)return setError('Insurance company is required.');if(form.purchase_from_type==='agent'&&!source)return setError('Purchase source is required.');if(!checked('has_od_cover')&&!checked('has_tp_cover'))return setError('Select at least one cover.');if(n('customer_discount')>calculation.gross_premium)return setError('Customer discount cannot exceed gross premium.');if(n('agent_commission')>calculation.gross_commission)return setError('Agent commission cannot exceed gross commission.');setSaving(true);try{const data:Record<string,unknown>={...form,insurance_company_id:company.id,company_name:company.company_name,company_code:company.agency_code_name||company.short_code||'',purchase_from:form.purchase_from_type==='agent'?source!.name:company.company_name,payment_details:{}};delete data.company_id;delete data.purchase_id;['od_premium','tp_premium','addon_premium','gst_percent','other_charges','commission_percent','gross_commission','customer_discount','agent_commission'].forEach(k=>data[k]=n(k));['has_od_cover','has_tp_cover'].forEach(k=>data[k]=checked(k));const fd=new FormData();Object.entries(data).forEach(([k,v])=>{if(v!=='')fd.append(k,typeof v==='object'?JSON.stringify(v):typeof v==='boolean'?(v?'1':'0'):String(v))});if(file)fd.append('policy_document',file);const saved=await vehicleInsuranceApi.saveForm(vehicleId,fd,editing);setPolicies(x=>editing?x.map(p=>p.id===saved.id?saved:p):[saved,...x]);setForm({...empty});setFile(null);setEditing(undefined);setExpiryManual(false);setMessage('Insurance policy saved successfully.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 function edit(p:VehicleInsurancePolicy){const v=(k:keyof VehicleInsurancePolicy,fallback:unknown='')=>String(p[k]??fallback),legacyBasis=String(p.commission_basis||'').toUpperCase(),basis=['OD_PREMIUM','NET_PREMIUM','MANUAL'].includes(legacyBasis)?legacyBasis:(p.commission_on_od?'OD_PREMIUM':'NET_PREMIUM'),rate=p.commission_percent||p.od_commission_percent||0;setForm({...empty,company_id:p.insurance_company_id||'',purchase_from_type:p.purchase_from_type||'direct_company',purchase_source_id:p.purchase_source_id||'',policy_number:p.policy_number,policy_date:p.policy_date||'',issue_date:p.issue_date,expiry_date:p.expiry_date,status:p.status,insurance_type:p.insurance_type,od_premium:v('od_premium',0),tp_premium:v('tp_premium',0),addon_premium:v('addon_premium',0),gst_percent:v('gst_percent',18),other_charges:v('other_charges',0),has_od_cover:p.has_od_cover?'1':'0',has_tp_cover:p.has_tp_cover?'1':'0',commission_basis:basis,commission_percent:String(rate),gross_commission:v('gross_commission',0),customer_discount:v('customer_discount',0),agent:p.agent||'',agent_commission:v('agent_commission',0),long_term_tp_policy_number:p.long_term_tp_policy_number||'',long_term_tp_expiry:p.long_term_tp_expiry||'',remark:p.remark||''});setExpiryManual(true);setEditing(p.id);scrollTo({top:0,behavior:'smooth'})}
 if(loading)return <main className="p-6">Loading insurance…</main>;if(!vehicle)return <main className="p-6 text-red-700">{error||'Vehicle not found'}</main>;
 return <main className="space-y-6 p-4 md:p-6"><header className="rounded-3xl bg-gradient-to-r from-slate-950 to-blue-700 p-7 text-white"><p className="text-xs font-bold tracking-[.2em] text-blue-200">POLICY MANAGEMENT</p><h1 className="mt-2 text-3xl font-black">{vehicle.vehicle_number}</h1><p>{vehicle.customer?.first_name} {vehicle.customer?.last_name} · {vehicle.customer?.mobile}</p></header>{error&&<Notice red>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Policy Upload</h2><p className="mt-1 text-sm text-slate-500">PDF, JPG, PNG or WEBP · maximum 15 MB. OCR never blocks manual entry.</p><div className="mt-4 flex flex-wrap items-center gap-3"><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>setFile(e.target.files?.[0]||null)} className="max-w-full rounded-xl border p-3"/><button type="button" disabled={!file||reading} onClick={()=>void ocr()} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-40">{reading?'Reading policy…':'Read Policy Details'}</button>{file&&<span className="text-sm font-semibold">{file.name}</span>}</div>{file?.type.startsWith('image/')&&<img src={URL.createObjectURL(file)} alt="Policy preview" className="mt-4 max-h-56 rounded-xl border object-contain"/>}</section>
 <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[.9fr_1.45fr_1.05fr]"><Card title="Vehicle Snapshot"><Info label="Vehicle" value={vehicle.vehicle_number}/><Info label="Registration" value={vehicle.registration_date}/><Info label="Type" value={vehicle.vehicle_type}/><Info label="Chassis" value={vehicle.chassis_number}/><Info label="Engine" value={vehicle.engine_number}/></Card>
 <Card title="Policy Details"><div className="grid gap-4 md:grid-cols-2"><div><Select label="Insurance Company" value={form.company_id} set={v=>set('company_id',v)} options={companies.map(x=>[x.id,x.company_name])}/><button type="button" onClick={()=>setCompanyModal(true)} className="mt-2 text-sm font-bold text-blue-700">+ Add Company</button></div><ReadText label="Company / Agency Code" value={companies.find(x=>x.id===form.company_id)?.agency_code_name||companies.find(x=>x.id===form.company_id)?.short_code||'—'}/><Select label="Purchase From" value={form.purchase_from_type} set={v=>setForm(x=>({...x,purchase_from_type:v,purchase_source_id:v==='agent'?x.purchase_source_id:''}))} options={[['direct_company','Direct Company'],['agent','Agent / Intermediary']]}/>{form.purchase_from_type==='agent'&&<div><Select label="Purchase Source" value={form.purchase_source_id} set={v=>set('purchase_source_id',v)} options={sources.map(x=>[x.id,`${x.name} (${x.source_type.replaceAll('_',' ')})`])}/><button type="button" onClick={()=>setSourceModal(true)} className="mt-2 text-sm font-bold text-blue-700">+ Add Purchase Source</button></div>}<Input label="Policy Number" value={form.policy_number} set={v=>set('policy_number',v.toUpperCase())}/><Select label="Policy Type" value={form.insurance_type} set={defaults} options={['comprehensive','third_party','standalone_od','commercial_package'].map(x=>[x,x.replaceAll('_',' ')])}/><Input label="Policy Start" type="date" value={form.policy_date} set={policyStart}/><Input label="Issue Date" type="date" value={form.issue_date} set={v=>set('issue_date',v)}/><Input label="Policy Expiry" type="date" value={form.expiry_date} set={v=>{setExpiryManual(true);set('expiry_date',v)}}/><Select label="Status" value={form.status} set={v=>set('status',v)} options={['running','pending','expired','cancelled'].map(x=>[x,x])}/></div><div className="mt-5 flex gap-5"><Toggle label="OD Cover" on={checked('has_od_cover')} set={v=>set('has_od_cover',v?'1':'0')}/><Toggle label="TP Cover" on={checked('has_tp_cover')} set={v=>set('has_tp_cover',v?'1':'0')}/></div>{longTerm&&<div className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-4"><h3 className="font-black">Bundled / Long-Term TP Details</h3><p className="mb-4 text-xs text-blue-700">{years}-year TP eligibility based on the exact registration anniversary.</p><div className="grid gap-4 md:grid-cols-2"><Input label="Long-Term TP Policy No." value={form.long_term_tp_policy_number} set={v=>set('long_term_tp_policy_number',v)}/><Input label="Long-Term TP Expiry" type="date" value={form.long_term_tp_expiry} set={v=>set('long_term_tp_expiry',v)}/></div></div>}</Card>
 <Card title="Premium & Earnings"><div className="grid gap-4 md:grid-cols-2"><Input type="number" label="OD Premium" value={form.od_premium} set={v=>set('od_premium',v)}/><Input type="number" label="TP Premium" value={form.tp_premium} set={v=>set('tp_premium',v)}/><Input type="number" label="Add-on Premium" value={form.addon_premium} set={v=>set('addon_premium',v)}/><Input type="number" label="Other Charges" value={form.other_charges} set={v=>set('other_charges',v)}/><Input type="number" label="Customer Discount" value={form.customer_discount} set={v=>set('customer_discount',v)}/><Read label="Net Premium" value={calculation.net_premium}/><Read label={`GST ${calculation.gst_percent}%`} value={calculation.gst_amount}/><Read label="Gross Premium" value={calculation.gross_premium}/><Read label="Customer Pay" value={calculation.customer_pay}/></div><h3 className="mt-5 font-black">Commission</h3><div className="mt-3 grid gap-4 md:grid-cols-2"><Select label="Commission Basis" value={form.commission_basis} set={v=>set('commission_basis',v)} options={[['OD_PREMIUM','OD Premium'],['NET_PREMIUM','Net Premium'],['MANUAL','Manual']]}/>{form.commission_basis==='MANUAL'?<Input type="number" label="Manual Commission Amount" value={form.gross_commission} set={v=>set('gross_commission',v)}/>:<Input type="number" label="Commission %" value={form.commission_percent} set={v=>set('commission_percent',v)}/>}<Read label="Commission Base" value={calculation.commission_base}/><Read label="Gross Commission" value={calculation.gross_commission}/><Input label="Sales Agent / Sub-Agent" value={form.agent} set={v=>set('agent',v)}/><Input type="number" label="Agent Commission" value={form.agent_commission} set={v=>set('agent_commission',v)}/></div><div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold">{calculation.commission_basis.replaceAll('_',' ')} base {money(calculation.commission_base)} = Gross Commission {money(calculation.gross_commission)}</div><button disabled={saving} className="mt-5 w-full rounded-xl bg-blue-800 p-3 font-bold text-white">{saving?'Saving…':editing?'Update Policy':'Save Policy'}</button></Card></form>
<section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Company','Policy','Type','Expiry','Premium','Commission','Document','Action'].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{policies.map(p=><tr className="border-t" key={p.id}><td className="p-4">{p.company_name}</td><td>{p.policy_number}</td><td>{p.insurance_type}</td><td>{p.expiry_date}</td><td>{money(p.gross_premium)}</td><td>{money(p.gross_commission)}</td><td>{p.policy_document_file_id&&<a className="text-blue-700 underline" href={apiUrl(`/vehicles/${vehicleId}/insurances/${p.id}/document`)}>Download</a>}</td><td><button type="button" onClick={()=>edit(p)} className="rounded-lg border px-3 py-2">Edit</button></td></tr>)}</tbody></table></section>{companyModal&&<QuickModal title="Add Insurance Company" saving={quickSaving} cancel={()=>setCompanyModal(false)}><form onSubmit={quickCompany} className="grid gap-4 md:grid-cols-2"><QuickInput name="company_name" label="Company Name" required/><QuickInput name="short_code" label="Short Name"/><QuickInput name="agency_code_name" label="Agency Code / Code Name"/><QuickInput name="tds_percent" label="TDS Percentage" type="number"/><QuickInput name="contact_person" label="Contact Person"/><QuickInput name="mobile" label="Mobile"/><QuickInput name="email" label="Email" type="email"/><QuickInput name="notes" label="Notes"/><ModalActions saving={quickSaving} cancel={()=>setCompanyModal(false)} label="Save Company"/></form></QuickModal>}{sourceModal&&<QuickModal title="Add Purchase Source" saving={quickSaving} cancel={()=>setSourceModal(false)}><form onSubmit={quickSource} className="grid gap-4 md:grid-cols-2"><QuickInput name="name" label="Name" required/><label className="text-sm font-semibold">Source Type<select name="source_type" className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="individual_agent">Individual Agent</option><option value="insurance_broker">Insurance Broker</option><option value="agency">Agency</option><option value="other">Other</option></select></label><QuickInput name="mobile" label="Mobile"/><QuickInput name="email" label="Email" type="email"/><label className="text-sm font-semibold">Linked Insurance Company<select name="linked_company_id" className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">None</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><QuickInput name="notes" label="Notes"/><p className="text-sm text-slate-500 md:col-span-2">TDS defaults to Not Applicable (0%).</p><ModalActions saving={quickSaving} cancel={()=>setSourceModal(false)} label="Save Source"/></form></QuickModal>}</main>
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-5 text-xl font-black">{title}</h2>{children}</section>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="text-sm font-semibold capitalize">{label}<input type={type} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>}
function Read({label,value}:{label:string;value:number}){return <label className="text-sm font-semibold">{label}<div className="mt-2 rounded-xl border bg-slate-100 px-4 py-3 font-black">{money(value)}</div></label>}
function ReadText({label,value}:{label:string;value:string}){return <label className="text-sm font-semibold">{label}<div className="mt-2 rounded-xl border bg-slate-100 px-4 py-3 font-bold">{value}</div></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return <label className="text-sm font-semibold">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Select</option>{options.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>}
function Toggle({label,on,set}:{label:string;on:boolean;set:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={on} onChange={e=>set(e.target.checked)} className="h-5 w-5"/>{label}</label>}
function Info({label,value}:{label:string;value?:string|number}){return <div className="border-b py-3"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="font-semibold capitalize">{value||'—'}</p></div>}
function Notice({children,red=false}:{children:React.ReactNode;red?:boolean}){return <div className={`rounded-xl border p-4 ${red?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</div>}
function QuickModal({title,children,cancel,saving}:{title:string;children:React.ReactNode;cancel:()=>void;saving:boolean}){return <div onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)cancel()}} className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4"><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{title}</h2><button type="button" disabled={saving} onClick={cancel}>✕</button></div>{children}</section></div>}
function QuickInput({name,label,type='text',required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input name={name} required={required} type={type} min={type==='number'?0:undefined} max={type==='number'?100:undefined} step={type==='number'?'0.001':undefined} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>}
function ModalActions({saving,cancel,label}:{saving:boolean;cancel:()=>void;label:string}){return <div className="flex justify-end gap-2 md:col-span-2"><button type="button" disabled={saving} onClick={cancel} className="rounded-xl border px-5 py-3">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{saving?'Saving…':label}</button></div>}
