'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {Vehicle,vehicleApi} from '@/lib/vehicles';
import {InsuranceCompany,PurchaseSource,insuranceAccountingApi} from '@/lib/insurance-accounting';
import {InsuranceCalculation,VehicleInsurancePolicy,vehicleInsuranceApi} from '@/lib/vehicle-insurance';
import {scanDocument} from '@/lib/ocr';
import {apiUrl} from '@/lib/api-url';

const empty:Record<string,string>={company_id:'',purchase_from_type:'direct_company',purchase_source_id:'',policy_number:'',policy_date:'',issue_date:'',expiry_date:'',status:'running',insurance_type:'comprehensive',od_premium:'0',tp_premium:'0',addon_premium:'0',gst_percent:'18',other_charges:'0',has_od_cover:'1',has_tp_cover:'1',commission_basis:'OD_PREMIUM',commission_percent:'0',gross_commission:'0',customer_discount:'0',agent:'',agent_commission:'0',long_term_tp_policy_number:'',long_term_tp_expiry:'',remark:''};
const emptyCalculation:InsuranceCalculation={has_od_cover:true,has_tp_cover:true,od_premium:0,tp_premium:0,addon_premium:0,net_premium:0,gst_percent:18,gst_amount:0,other_charges:0,gross_premium:0,customer_discount:0,customer_pay:0,commission_basis:'OD_PREMIUM',commission_base:0,commission_percent:0,gross_commission:0};
const money=(v:number)=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function Page(){
 const {vehicleId}=useParams<{vehicleId:string}>();
 const [vehicle,setVehicle]=useState<Vehicle|null>(null);
 const [companies,setCompanies]=useState<InsuranceCompany[]>([]);
 const [sources,setSources]=useState<PurchaseSource[]>([]);
 const [policies,setPolicies]=useState<VehicleInsurancePolicy[]>([]);
 const [form,setForm]=useState({...empty});
 const [calculation,setCalculation]=useState<InsuranceCalculation>(emptyCalculation);
 const [file,setFile]=useState<File|null>(null);
 const [editing,setEditing]=useState<string>();
 const [formOpen,setFormOpen]=useState(false);
 const [loading,setLoading]=useState(true);
 const [saving,setSaving]=useState(false);
 const [reading,setReading]=useState(false);
 const [expiryManual,setExpiryManual]=useState(false);
 const [companyModal,setCompanyModal]=useState(false);
 const [sourceModal,setSourceModal]=useState(false);
 const [cancelTarget,setCancelTarget]=useState<VehicleInsurancePolicy|null>(null);
 const [quickSaving,setQuickSaving]=useState(false);
 const [message,setMessage]=useState('');
 const [error,setError]=useState('');

 useEffect(()=>{void(async()=>{try{const [v,c,s,p]=await Promise.all([vehicleApi.get(vehicleId),insuranceAccountingApi.companies(),insuranceAccountingApi.purchaseSources(),vehicleInsuranceApi.list(vehicleId)]);setVehicle(v);setCompanies(c.filter(x=>x.status==='active'));setSources(s.filter(x=>x.is_active));setPolicies(p)}catch(e){setError(e instanceof Error?e.message:'Unable to load insurance data')}finally{setLoading(false)}})()},[vehicleId]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!quickSaving){setCompanyModal(false);setSourceModal(false)}};addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[quickSaving]);
 const n=(k:string)=>Number(form[k]||0),set=(k:string,v:string)=>setForm(x=>({...x,[k]:v})),checked=(k:string)=>form[k]==='1';
 useEffect(()=>{if(!vehicle||!formOpen)return;let cancelled=false;const timer=setTimeout(()=>{void vehicleInsuranceApi.calculate(vehicleId,{insurance_type:form.insurance_type,has_od_cover:checked('has_od_cover'),has_tp_cover:checked('has_tp_cover'),od_premium:n('od_premium'),tp_premium:n('tp_premium'),addon_premium:n('addon_premium'),other_charges:n('other_charges'),customer_discount:n('customer_discount'),gst_percent:n('gst_percent')||18,commission_basis:form.commission_basis,commission_percent:n('commission_percent'),manual_commission_amount:n('gross_commission')}).then(value=>{if(!cancelled)setCalculation(value)}).catch(()=>undefined)},180);return()=>{cancelled=true;clearTimeout(timer)}},[vehicle,vehicleId,form,formOpen]);
 const managedMotor=['private_car','two_wheeler'].includes(vehicle?.vehicle_type||'');
 const goodsCarriage=['lgv','lcv','hgv','goods_carrier','goods_carriage'].includes((vehicle?.vehicle_type||'').toLowerCase());
 const years=vehicle?.vehicle_type==='private_car'?3:vehicle?.vehicle_type==='two_wheeler'?5:0;
 const longTerm=useMemo(()=>{if(!years||!vehicle?.registration_date)return false;const d=new Date(vehicle.registration_date);if(isNaN(d.getTime()))return false;d.setFullYear(d.getFullYear()+years);return new Date()<d||!!form.long_term_tp_policy_number||!!form.long_term_tp_expiry},[years,vehicle,form.long_term_tp_policy_number,form.long_term_tp_expiry]);
 const current=useMemo(()=>policies.filter(p=>!p.archived_at&&p.status!=='cancelled').sort((a,b)=>String(b.expiry_date).localeCompare(String(a.expiry_date)))[0]??null,[policies]);

 function defaults(type:string){setForm(x=>({...x,insurance_type:type,has_od_cover:type==='third_party'?'0':'1',has_tp_cover:type==='standalone_od'?'0':'1',od_premium:type==='third_party'?'0':x.od_premium,tp_premium:type==='standalone_od'?'0':x.tp_premium,commission_basis:managedMotor&&type==='comprehensive'?'OD_PREMIUM':'NET_PREMIUM'}))}
 function policyStart(value:string){setForm(x=>{if(expiryManual||!value)return {...x,policy_date:value};const [year,month,day]=value.split('-').map(Number),next=new Date(year+1,month-1,day);if(Number.isNaN(next.getTime()))return {...x,policy_date:value};next.setDate(next.getDate()-1);const expiry=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-${String(next.getDate()).padStart(2,'0')}`;return {...x,policy_date:value,expiry_date:expiry}})}
 function openNew(){setForm({...empty});setFile(null);setEditing(undefined);setExpiryManual(false);setMessage('');setError('');setFormOpen(true);setTimeout(()=>document.getElementById('policy-form')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
 function closeForm(){if(saving)return;setForm({...empty});setFile(null);setEditing(undefined);setExpiryManual(false);setFormOpen(false);setError('')}
 function edit(p:VehicleInsurancePolicy){const v=(k:keyof VehicleInsurancePolicy,fallback:unknown='')=>String(p[k]??fallback),legacyBasis=String(p.commission_basis||'').toUpperCase(),basis=['OD_PREMIUM','NET_PREMIUM','MANUAL'].includes(legacyBasis)?legacyBasis:(p.commission_on_od?'OD_PREMIUM':'NET_PREMIUM'),rate=p.commission_percent||p.od_commission_percent||0;setForm({...empty,company_id:p.insurance_company_id||'',purchase_from_type:p.purchase_from_type||'direct_company',purchase_source_id:p.purchase_source_id||'',policy_number:p.policy_number,policy_date:p.policy_date||'',issue_date:p.issue_date,expiry_date:p.expiry_date,status:p.status,insurance_type:p.insurance_type,od_premium:v('od_premium',0),tp_premium:v('tp_premium',0),addon_premium:v('addon_premium',0),gst_percent:v('gst_percent',18),other_charges:v('other_charges',0),has_od_cover:p.has_od_cover?'1':'0',has_tp_cover:p.has_tp_cover?'1':'0',commission_basis:basis,commission_percent:String(rate),gross_commission:v('gross_commission',0),customer_discount:v('customer_discount',0),agent:p.agent||'',agent_commission:v('agent_commission',0),long_term_tp_policy_number:p.long_term_tp_policy_number||'',long_term_tp_expiry:p.long_term_tp_expiry||'',remark:p.remark||''});setExpiryManual(true);setEditing(p.id);setFormOpen(true);setError('');setMessage('');setTimeout(()=>document.getElementById('policy-form')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
 async function ocr(){if(!file)return;setReading(true);setError('');try{const r=await scanDocument('insurance_policy',[file]);let count=0;setForm(old=>{const next={...old};Object.entries(r.fields).forEach(([k,v])=>{if(v&&k in next){next[k]=v;count++}});return next});if(r.fields.insurance_type)defaults(r.fields.insurance_type);const name=r.fields.company_name?.toLowerCase();const c=name&&companies.find(x=>name.includes(x.company_name.toLowerCase())||x.company_name.toLowerCase().includes(name));if(c)set('company_id',c.id);setMessage(`${count} policy fields extracted. Please verify before saving.`)}catch(e){setError(`${e instanceof Error?e.message:'OCR failed'} Manual entry remains available.`)}finally{setReading(false)}}
 async function submit(e:FormEvent){e.preventDefault();setError('');const company=companies.find(x=>x.id===form.company_id),source=sources.find(x=>x.id===form.purchase_source_id);if(!company)return setError('Insurance company is required.');if(form.purchase_from_type==='agent'&&!source)return setError('Purchase source is required.');if(!checked('has_od_cover')&&!checked('has_tp_cover'))return setError('Select at least one cover.');if(n('customer_discount')>calculation.gross_premium)return setError('Customer discount cannot exceed gross premium.');setSaving(true);try{const data:Record<string,unknown>={...form,insurance_company_id:company.id,company_name:company.company_name,company_code:company.agency_code_name||company.short_code||'',purchase_from:form.purchase_from_type==='agent'?source!.name:company.company_name,payment_details:{}};delete data.company_id;['od_premium','tp_premium','addon_premium','gst_percent','other_charges','commission_percent','gross_commission','customer_discount','agent_commission'].forEach(k=>data[k]=n(k));['has_od_cover','has_tp_cover'].forEach(k=>data[k]=checked(k));const fd=new FormData();Object.entries(data).forEach(([k,v])=>{if(v!=='')fd.append(k,typeof v==='object'?JSON.stringify(v):typeof v==='boolean'?(v?'1':'0'):String(v))});if(file)fd.append('policy_document',file);await vehicleInsuranceApi.saveForm(vehicleId,fd,editing);setPolicies(await vehicleInsuranceApi.list(vehicleId));setForm({...empty});setFile(null);setEditing(undefined);setExpiryManual(false);setFormOpen(false);setMessage(editing?'Policy updated successfully.':'Policy added successfully.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 async function removePolicy(p:VehicleInsurancePolicy){if(!confirm(`Delete policy ${p.policy_number}? This is only allowed when no linked financial/document records exist.`))return;setError('');try{await vehicleInsuranceApi.remove(vehicleId,p.id);setPolicies(await vehicleInsuranceApi.list(vehicleId));setMessage('Policy deleted successfully.')}catch(e){setError(e instanceof Error?e.message:'Policy could not be deleted.')}}
 async function archivePolicy(p:VehicleInsurancePolicy){if(!confirm(`Archive policy ${p.policy_number}?`))return;setError('');try{await vehicleInsuranceApi.archive(vehicleId,p.id);setPolicies(await vehicleInsuranceApi.list(vehicleId));setMessage('Policy archived successfully.')}catch(e){setError(e instanceof Error?e.message:'Policy could not be archived.')}}
 async function cancelPolicy(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!cancelTarget||quickSaving)return;setQuickSaving(true);setError('');const fd=new FormData(e.currentTarget);try{await vehicleInsuranceApi.cancel(vehicleId,cancelTarget.id,{cancellation_date:String(fd.get('cancellation_date')),cancellation_reason:String(fd.get('cancellation_reason')),refund_amount:Number(fd.get('refund_amount')||0),cancellation_charges:Number(fd.get('cancellation_charges')||0),confirmed:fd.get('confirmed')==='on'});setPolicies(await vehicleInsuranceApi.list(vehicleId));setCancelTarget(null);setMessage('Policy cancelled successfully.')}catch(caught){setError(caught instanceof Error?caught.message:'Policy could not be cancelled.')}finally{setQuickSaving(false)}}
 async function quickCompany(e:FormEvent<HTMLFormElement>){e.preventDefault();if(quickSaving)return;setQuickSaving(true);const fd=new FormData(e.currentTarget);try{const created=await insuranceAccountingApi.addCompany({company_name:fd.get('company_name'),short_code:fd.get('short_code'),agency_code_name:fd.get('agency_code_name'),tds_percent:Number(fd.get('tds_percent')||0),default_commission_percent:0,settlement_days:30,contact_person:fd.get('contact_person'),mobile:fd.get('mobile'),email:fd.get('email'),notes:fd.get('notes')});setCompanies((await insuranceAccountingApi.companies()).filter(x=>x.status==='active'));set('company_id',created.id);setCompanyModal(false)}catch(e){setError(e instanceof Error?e.message:'Company could not be added.')}finally{setQuickSaving(false)}}
 async function quickSource(e:FormEvent<HTMLFormElement>){e.preventDefault();if(quickSaving)return;setQuickSaving(true);const fd=new FormData(e.currentTarget);try{const created=await insuranceAccountingApi.addPurchaseSource({name:fd.get('name'),source_type:fd.get('source_type'),mobile:fd.get('mobile'),email:fd.get('email'),linked_company_id:fd.get('linked_company_id')||null,tds_applicable:false,tds_percent:0,is_active:true,notes:fd.get('notes')});setSources((await insuranceAccountingApi.purchaseSources()).filter(x=>x.is_active));set('purchase_source_id',created.id);setSourceModal(false)}catch(e){setError(e instanceof Error?e.message:'Purchase source could not be added.')}finally{setQuickSaving(false)}}

 if(loading)return <main className="p-6 text-sm text-slate-500">Loading insurance…</main>;
 if(!vehicle)return <main className="p-6 text-red-700">{error||'Vehicle not found'}</main>;
 return <main className="min-h-screen bg-[#f4f7fc] p-3 text-[#081a3a] sm:p-5 md:p-7"><div className="mx-auto max-w-7xl space-y-4">
  <section className="relative overflow-hidden rounded-[28px] border border-[#173d78] bg-[#071a3c] p-5 text-white shadow-[0_24px_70px_rgba(7,26,60,.20)] sm:p-7"><div className="absolute inset-0 bg-[radial-gradient(circle_at_90%_10%,rgba(43,117,255,.48),transparent_34%),linear-gradient(135deg,#06152f,#0a2555_60%,#0c3478)]"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><a href={`/vehicles/${vehicleId}`} className="text-xs font-bold text-blue-200">← Vehicle Profile</a><p className="mt-5 text-[9px] font-black uppercase tracking-[.24em] text-cyan-300">Insurance</p><h1 className="mt-1 text-3xl font-black">{current?'Current Policy':'Insurance'}</h1><p className="mt-2 max-w-2xl text-xs text-blue-100/70">Policy summary first. Detailed premium, GST and commission fields open only when you add or edit a policy.</p></div><button type="button" onClick={openNew} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/10 px-5 text-sm font-black text-white backdrop-blur hover:bg-white/15"><span className="text-xl">＋</span>{current?'Add / Renew Policy':'Add Policy'}</button></div></section>
  {error&&<Notice red>{error}</Notice>}{message&&<Notice>{message}</Notice>}

  {current?<section className="overflow-hidden rounded-[28px] border border-[#d9e5f7] bg-white shadow-[0_14px_40px_rgba(26,64,120,.07)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 sm:px-6"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-blue-500">Policy summary</p><h2 className="mt-1 text-xl font-black">Active insurance</h2></div><Status value={current.status}/></div><div className="grid sm:grid-cols-2 lg:grid-cols-3"><Summary label="Insurance Company" value={current.company_name}/><Summary label="Policy Number" value={current.policy_number}/><Summary label="Policy Type" value={pretty(current.insurance_type)}/><Summary label="Expiry Date" value={formatDate(current.expiry_date)}/><Summary label="Customer Pay" value={money(Number(current.customer_pay??current.gross_premium??0))}/><Summary label="Status" value={pretty(current.status)}/></div><div className="flex flex-wrap gap-2 border-t border-slate-100 bg-[#f8fbff] p-4 sm:px-6"><button type="button" onClick={()=>edit(current)} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-blue-700">✎ Edit / Manage</button>{current.policy_document_file_id&&<a className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-700" href={apiUrl(`/vehicles/${vehicleId}/insurances/${current.id}/document`)}>↓ Policy PDF</a>}<button type="button" onClick={()=>setCancelTarget(current)} className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-2.5 text-xs font-black text-amber-700">Cancel</button><button type="button" onClick={()=>void archivePolicy(current)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-600">Archive</button><button type="button" onClick={()=>void removePolicy(current)} className="ml-auto rounded-xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-xs font-black text-rose-700">Delete</button></div></section>:<section className="rounded-[24px] border border-dashed border-blue-200 bg-white p-8 text-center"><div className="text-4xl">🛡️</div><h2 className="mt-3 text-xl font-black">No policy added</h2><p className="mt-1 text-sm text-slate-500">Add the current policy to start expiry and premium tracking.</p><button type="button" onClick={openNew} className="mt-5 rounded-2xl bg-blue-700 px-5 py-3 text-sm font-black text-white">＋ Add Policy</button></section>}

  {!formOpen&&policies.length>1&&<section className="overflow-hidden rounded-[24px] border border-[#d9e5f7] bg-white"><div className="border-b border-slate-100 px-5 py-4"><p className="text-[9px] font-black uppercase tracking-[.2em] text-slate-400">History</p><h2 className="mt-1 text-lg font-black">Previous Policies</h2></div><div className="divide-y divide-slate-100">{policies.filter(p=>p.id!==current?.id).slice(0,8).map(p=><div key={p.id} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{p.company_name} · {p.policy_number}</p><p className="mt-1 text-xs font-semibold text-slate-400">{pretty(p.insurance_type)} · Expiry {formatDate(p.expiry_date)}</p></div><div className="flex gap-2"><button type="button" onClick={()=>edit(p)} className="rounded-lg border px-3 py-2 text-xs font-black">Edit</button>{p.policy_document_file_id&&<a href={apiUrl(`/vehicles/${vehicleId}/insurances/${p.id}/document`)} className="rounded-lg border px-3 py-2 text-xs font-black">PDF</a>}</div></div>)}</div></section>}

  {formOpen&&<form id="policy-form" onSubmit={submit} className="overflow-hidden rounded-[28px] border border-[#d9e5f7] bg-white shadow-[0_18px_50px_rgba(26,64,120,.09)]"><div className="flex items-center justify-between border-b border-slate-100 bg-gradient-to-r from-white to-blue-50/60 px-5 py-4 sm:px-6"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-blue-500">{editing?'Edit policy':'New policy'}</p><h2 className="mt-1 text-xl font-black">{editing?'Update Insurance':'Add Insurance'}</h2></div><button type="button" onClick={closeForm} className="grid h-10 w-10 place-items-center rounded-xl border bg-white text-lg font-black text-slate-500">×</button></div>
   <div className="grid gap-5 p-5 lg:grid-cols-2 sm:p-6"><section className="space-y-4"><h3 className="font-black">Policy Details</h3><div className="grid gap-4 sm:grid-cols-2"><div><Select label="Insurance Company" value={form.company_id} set={v=>set('company_id',v)} options={companies.map(x=>[x.id,x.company_name])}/><button type="button" onClick={()=>setCompanyModal(true)} className="mt-2 text-xs font-black text-blue-700">＋ Add Company</button></div><Select label="Policy Type" value={form.insurance_type} set={defaults} options={['comprehensive','third_party','standalone_od','commercial_package'].map(x=>[x,pretty(x)])}/><Input label="Policy Number" value={form.policy_number} set={v=>set('policy_number',v.toUpperCase())}/><Input label="Policy Start" type="date" value={form.policy_date} set={policyStart}/><Input label="Issue Date" type="date" value={form.issue_date} set={v=>set('issue_date',v)}/><Input label="Policy Expiry" type="date" value={form.expiry_date} set={v=>{setExpiryManual(true);set('expiry_date',v)}}/><Select label="Purchase From" value={form.purchase_from_type} set={v=>setForm(x=>({...x,purchase_from_type:v,purchase_source_id:v==='agent'?x.purchase_source_id:''}))} options={[['direct_company','Direct Company'],['agent','Agent / Intermediary']]}/>{form.purchase_from_type==='agent'&&<div><Select label="Purchase Source" value={form.purchase_source_id} set={v=>set('purchase_source_id',v)} options={sources.map(x=>[x.id,x.name])}/><button type="button" onClick={()=>setSourceModal(true)} className="mt-2 text-xs font-black text-blue-700">＋ Add Source</button></div>}</div><div className="flex gap-5"><Toggle label="OD Cover" on={checked('has_od_cover')} set={v=>set('has_od_cover',v?'1':'0')}/><Toggle label="TP Cover" on={checked('has_tp_cover')} set={v=>set('has_tp_cover',v?'1':'0')}/></div>{longTerm&&<div className="grid gap-4 rounded-xl border border-blue-100 bg-blue-50 p-4 sm:grid-cols-2"><Input label="Long-Term TP Policy No." value={form.long_term_tp_policy_number} set={v=>set('long_term_tp_policy_number',v)}/><Input label="Long-Term TP Expiry" type="date" value={form.long_term_tp_expiry} set={v=>set('long_term_tp_expiry',v)}/></div>}<div className="rounded-xl border border-dashed p-4"><p className="text-xs font-black uppercase text-slate-400">Policy Document</p><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-3 max-w-full text-sm"/><button type="button" disabled={!file||reading} onClick={()=>void ocr()} className="mt-3 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-blue-700 disabled:opacity-40">{reading?'Reading…':'Read Policy Details'}</button></div></section>
    <section className="space-y-4"><h3 className="font-black">Premium & Earnings</h3>{goodsCarriage&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-semibold text-amber-900"><b>LGV:</b> Basic TP is the 5% GST bucket. OD + Add-on/PA/LL are in the 18% bucket.</div>}<div className="grid gap-4 sm:grid-cols-2"><Input type="number" label="OD Premium" value={form.od_premium} set={v=>set('od_premium',v)}/><Input type="number" label={goodsCarriage?'Basic TP Premium (5% GST)':'TP Premium'} value={form.tp_premium} set={v=>set('tp_premium',v)}/><Input type="number" label={goodsCarriage?'Add-on / PA / LL (18% GST)':'Add-on Premium'} value={form.addon_premium} set={v=>set('addon_premium',v)}/><Input type="number" label="Other Charges" value={form.other_charges} set={v=>set('other_charges',v)}/><Input type="number" label="Customer Discount" value={form.customer_discount} set={v=>set('customer_discount',v)}/><Read label="Net Premium" value={calculation.net_premium}/><Read label="GST" value={calculation.gst_amount}/><Read label="Customer Pay" value={calculation.customer_pay}/></div><div className="border-t pt-4"><h4 className="text-sm font-black">Commission</h4><div className="mt-3 grid gap-4 sm:grid-cols-2"><Select label="Commission Basis" value={form.commission_basis} set={v=>set('commission_basis',v)} options={[['OD_PREMIUM','OD Premium'],['NET_PREMIUM','Net Premium'],['MANUAL','Manual']]}/>{form.commission_basis==='MANUAL'?<Input type="number" label="Commission Amount" value={form.gross_commission} set={v=>set('gross_commission',v)}/>:<Input type="number" label="Commission %" value={form.commission_percent} set={v=>set('commission_percent',v)}/>}<Input label="Sales Agent / Sub-Agent" value={form.agent} set={v=>set('agent',v)}/><Input type="number" label="Agent Commission" value={form.agent_commission} set={v=>set('agent_commission',v)}/></div></div></section></div>
   <div className="flex flex-col gap-3 border-t border-slate-100 bg-[#f8fbff] p-4 sm:flex-row sm:items-center sm:justify-end sm:px-6"><button type="button" onClick={closeForm} className="rounded-xl border bg-white px-5 py-3 text-sm font-black">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-800 px-6 py-3 text-sm font-black text-white disabled:opacity-50">{saving?'Saving…':editing?'Update Policy':'Save Policy'}</button></div></form>}

  {cancelTarget&&<QuickModal title={`Cancel Policy ${cancelTarget.policy_number}`} saving={quickSaving} cancel={()=>setCancelTarget(null)}><form onSubmit={cancelPolicy} className="grid gap-4 md:grid-cols-2"><QuickInput name="cancellation_date" label="Cancellation Date" type="date" required/><label className="text-sm font-semibold md:col-span-2">Cancellation Reason<textarea name="cancellation_reason" required className="mt-2 min-h-24 w-full rounded-xl border px-4 py-3"/></label><QuickInput name="refund_amount" label="Refund Amount" type="number"/><QuickInput name="cancellation_charges" label="Cancellation Charges" type="number"/><label className="flex gap-2 text-sm md:col-span-2"><input required name="confirmed" type="checkbox"/>Confirm cancellation and reversal entries.</label><ModalActions saving={quickSaving} cancel={()=>setCancelTarget(null)} label="Cancel Policy"/></form></QuickModal>}
  {companyModal&&<QuickModal title="Add Insurance Company" saving={quickSaving} cancel={()=>setCompanyModal(false)}><form onSubmit={quickCompany} className="grid gap-4 md:grid-cols-2"><QuickInput name="company_name" label="Company Name" required/><QuickInput name="short_code" label="Short Name"/><QuickInput name="agency_code_name" label="Agency Code / Code Name"/><QuickInput name="tds_percent" label="TDS Percentage" type="number"/><QuickInput name="contact_person" label="Contact Person"/><QuickInput name="mobile" label="Mobile"/><QuickInput name="email" label="Email" type="email"/><QuickInput name="notes" label="Notes"/><ModalActions saving={quickSaving} cancel={()=>setCompanyModal(false)} label="Save Company"/></form></QuickModal>}
  {sourceModal&&<QuickModal title="Add Purchase Source" saving={quickSaving} cancel={()=>setSourceModal(false)}><form onSubmit={quickSource} className="grid gap-4 md:grid-cols-2"><QuickInput name="name" label="Name" required/><label className="text-sm font-semibold">Source Type<select name="source_type" className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="individual_agent">Individual Agent</option><option value="insurance_broker">Insurance Broker</option><option value="agency">Agency</option><option value="other">Other</option></select></label><QuickInput name="mobile" label="Mobile"/><QuickInput name="email" label="Email" type="email"/><label className="text-sm font-semibold">Linked Insurance Company<select name="linked_company_id" className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">None</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><QuickInput name="notes" label="Notes"/><ModalActions saving={quickSaving} cancel={()=>setSourceModal(false)} label="Save Source"/></form></QuickModal>}
 </div></main>
}

function Summary({label,value}:{label:string;value?:string|number}){return <div className="border-b border-r border-slate-100 p-5 last:border-r-0"><p className="text-[9px] font-black uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-2 break-words text-sm font-black text-slate-900 sm:text-base">{value||'—'}</p></div>}
function Status({value}:{value:string}){const good=['running','active','valid'].includes(String(value).toLowerCase());return <span className={`rounded-full px-3 py-1.5 text-[9px] font-black uppercase ${good?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{pretty(value)}</span>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="text-sm font-semibold">{label}<input type={type} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal outline-none focus:border-blue-400 focus:bg-white"/></label>}
function Read({label,value}:{label:string;value:number}){return <label className="text-sm font-semibold">{label}<div className="mt-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-black">{money(value)}</div></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return <label className="text-sm font-semibold">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">Select</option>{options.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>}
function Toggle({label,on,set}:{label:string;on:boolean;set:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={on} onChange={e=>set(e.target.checked)} className="h-5 w-5"/>{label}</label>}
function Notice({children,red=false}:{children:React.ReactNode;red?:boolean}){return <div className={`rounded-xl border p-4 text-sm font-semibold ${red?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</div>}
function QuickModal({title,children,cancel,saving}:{title:string;children:React.ReactNode;cancel:()=>void;saving:boolean}){return <div onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)cancel()}} className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4"><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{title}</h2><button type="button" disabled={saving} onClick={cancel}>✕</button></div>{children}</section></div>}
function QuickInput({name,label,type='text',required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input name={name} required={required} type={type} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>}
function ModalActions({saving,cancel,label}:{saving:boolean;cancel:()=>void;label:string}){return <div className="flex justify-end gap-2 md:col-span-2"><button type="button" disabled={saving} onClick={cancel} className="rounded-xl border px-5 py-3">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{saving?'Saving…':label}</button></div>}
function pretty(v?:string){return v?v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()):'—'}
function formatDate(v?:string){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
